### ISSUE TITLE
MPR Fails if initiated from viewport that was not populated by drag-n-drop

### ISSUE THREAD

**Issue by caoer** [OHIF/Viewers#1022]
> **Before Creating an issue**
>
> - Are you running the latest version? YES
> - Are you reporting to the correct repository? YES
> - Did you search existing issues? YES

## Bug Report

I'm using the official web url [https://viewer.ohif.org/viewer/1.3.6.1.4.1.14519.5.2.1.2744.7002.373729467545468642229382466905](https://viewer.ohif.org/viewer/1.3.6.1.4.1.14519.5.2.1.2744.7002.373729467545468642229382466905)

### Describe the Bug

trying to adjust slab thinkness, screen became black. 

### What steps can we follow to reproduce the bug?

please see screen recording at: https://kapture-fugspsudqf.now.sh

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by dannyrb** [comment]
@caoer, thanks for the report. It looks like if you click `2D MPR`, what we're seeing are actually `cornerstone` viewports and not `vtk` viewports. 

If I drag and drop that same series into the first viewport, and then click `2D MPR`, everything works as expected. We don't notice this in most of our other studies because they tend to have a pilot (single image series, can't reconstruct) so you're forced to drag a series before initiating MPR.

The thumbnail drag-n-drop probably updates our `viewportSpecificData` with properties that our viewport "autofill" (for empty viewports) does not.

This is related to: https://github.com/OHIF/Viewers/issues/1005
