### ISSUE TITLE
Cannot View Image in Production Mode

### ISSUE THREAD

**Issue by shtl23** [OHIF/Viewers#107]
Hi,
While Building OHIF for Production, The Images are loaded in the Viewer Grid from the Orthanc Server, but I cannot View the image;
DICOM Server is added manually to the Viewer as shown below in the screenshot:
![serverinfo_ohif_production](https://user-images.githubusercontent.com/25497905/29774672-f626529c-8c1f-11e7-9137-8419dff67590.png)
![ohif_prod_command_screenshot](https://user-images.githubusercontent.com/25497905/29774682-fad98bba-8c1f-11e7-9f7c-5b1743097375.png)
Below is the Screenshot for the Viewer
![ohif_prod_viewer1](https://user-images.githubusercontent.com/25497905/29774710-291028a4-8c20-11e7-80a3-44c6c543aa77.png)
How Do I fix this issue?

**Comment by swederik** [comment]
It looks like you must have built for production with the wrong ROOT_URL, since the viewer is trying to load the assets from http://localhost instead of http://localhost:3000. Try rebuilding and using ROOT_URL=http://localhost:3000

If you are running this with node, maybe you are missing the PORT environment variable?

**Comment by shtl23** [comment]
Thanks, it worked for me.
I Rebuilt and used ROOT_URL=http://localhost:3000
