### ISSUE TITLE
Search fields only searches for full string and are case sensitive

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1114]
### Description

`Patient Name`, `MRN`,  `Accession` and `Description` fields are case sensitive and only searches for complete string (partial string i.e: First Name, doesn't find results).

**No results found by searching partial string:**
![bug-search-name3](https://user-images.githubusercontent.com/13245529/67709911-b39b6c80-f99d-11e9-8482-3ca2d3159724.gif)

**No results found by searching lower case:**
![bug-search-name2](https://user-images.githubusercontent.com/13245529/67707269-f149c680-f998-11e9-8edd-260f2c47f4a7.gif)

### What steps can we follow to reproduce the bug?

Scenario 1:
1. On study list page, search for Patient Name: `neptune`
2. Verify that no results were found
3. Search for Patient Name: `Neptune`
4. Verify that 3 results were found

Scenario 2:
1. Search for Patient Name: `Fall`
2. Verify that no results were found
3. Search for Patient Name: `Fall 1`
4. Verify that 1 result was found

Scenario 3:
1. Search for Description: `ct`, `CT` or `CT abdomen`
2. Verify that no results were found
3. Search for Description: `CT ABDOMEN` or `CT Abdomen`
4. Verify that 1 result was found

Scenario 4:
1. Search for Patient Name: `Mister` or `mister`
2. Verify that no results were found
3. Search for Patient Name: `MISTER`
4. Verify that 5 different results were found. In this case, substring was returned.

### Actual result

The search only returns results when we complete string matches the database. The fields are case sensitive and don't return results if the case is not the same as the database.

### Expected result

1. All search fields should not be case sensitive. User should be able to find the same results by searching with lower case, upper case, camel case, etc.

2. `Patient Name` and `Description` fields should return values that match a partial string (substring). User should be able to search patients only by their First Name, Last Name, or a Part of the description.
2.1. `MRN` and `Accession` fields should not search for substrings, only complete strings.

**Comment by dannyrb** [comment]
This is tricky, because we're testing two things here.

1. The client's ability to create requests.
2. The server's ability to search/filter/return our expected result sets.

By default, our application communicates with DICOMWeb conformant APIs. DICOMWeb allows for servers to optionally support a parameter named `fuzzymatching`. You can read more about what we have the ability to [query here (QIDO-RS)](https://www.dicomstandard.org/dicomweb/query-qido-rs/).

So... What does `fuzzymatching` do, if the server we're hitting supports it? You can read more about that here: [8.3.4.2 Fuzzy Matching of Person Names](http://dicom.nema.org/medical/dicom/current/output/html/part18.html).

> If extended negotiation of fuzzy semantic matching rather than literal matching of PN VR is successful, not only may matching be insensitive to case, position, accent, and character encoding (including combining characters), but in addition other techniques such as phonetic matching may be applied.

What's interesting is that I don't think we can guarantee how the server's `fuzzymatching` works, but we _should_ be able to indicate if it's available/set for the current server.

--------

Outside the scope of this ticket, it's worth mentioning that we eventually want better support for users to use the filter values to create a request URL that works for _<insert server implementation here>_, and then maps the result to the format the table templates expect.

I hope this helps provide some context. I'm not 100% sure how this influences our testing. We may not want to test these features specifically, but may want to test a query "with fuzzymatching" versus one "without fuzzymatching", should we eventually expose that option.

**Comment by Y4kuz4** [comment]
What is the diference with lesiontracker? Lesion tracker demo is not case sensitive and work fine.

**Comment by dannyrb** [comment]
@Y4kuz4 the previous version of OHIF had a "server side" implementation. The current viewer is limited to the filtering supported by DICOMWeb and the PACS that implement it.

**Comment by Y4kuz4** [comment]
> @Y4kuz4 the previous version of OHIF had a "server side" implementation. The current viewer is limited to the filtering supported by DICOMWeb and the PACS that implement it.

I understand, thx!!

**Comment by dannyrb** [comment]
We have some updated guidance on how to improve filtering/sorting, but we'll capture them outside of this ticket.

**Comment by chaitanyaappno** [comment]
Hello,

I just have started working on OHIF for my project, following the documentation and also able to run my project locally. However, I am not able to get the data instead showing no result found. can anybody help me to set up this project locally? I have been working on VIEWERS repo.
![Screen Shot 2022-08-09 at 10 23 58 AM](https://user-images.githubusercontent.com/84988841/183675099-07ed3775-d2c0-4460-9b47-0359b9f746a4.png)
