### ISSUE TITLE
Sync Measurement table and measurement drawings shown on image

### ISSUE THREAD

**Issue by tiimoS** [OHIF/Viewers#1115]
I have implemented a mongo db backend to save ArrowAnnotations and retrieve them again once the study viewer page is reloaded. After the reload, I get the saved annotations from the db and add them again using the addMeasurement method in the MeasurementApi. The measurements are added to the measurement table. 

The only issue that I have now is, that after the page reload, the drawing (visual representation of the measurement on the image itself) is only displayed after selecting the Annotate button in the toolbar. Then all the yellow measurements appear as expected on the canvas. 

So my question would be: is there a way to trigger the sync of the measurements in the measurement table and draw them again on the images automatically after the page reloads, i.e. without first selecting the annotate button?

**Comment by dannyrb** [comment]
I believe we resolve this in an in-progress PR where we're trying to persist/restore annotations using DICOM SR. The crux of the issue is that all tools default to `disabled` (not rendered, not interactable). Selecting a tool sets it to `active` (rendered, can create, can modify existing), and selecting a different tool would shift the previously selected tool to `passive` (rendered, can modify existing).

What we need, and I think we ended up doing, is defaulting all `annotation` tools to "passive" at application start.

CC: @galelis

**Comment by dannyrb** [comment]
The magic: https://github.com/OHIF/Viewers/pull/954/files#diff-806887a626bd3398754ce85497537abaR102-R111

If you have more pointed feedback around how we can improve `extension` configuration or data persistence/restore mechanisms, please don't hesitate to create a new issue. We are incredibly interested in contributor insights in these areas.
