### ISSUE TITLE
how to use cornerstone load imageIds from Orthanc

### ISSUE THREAD

**Issue by longerking** [OHIF/Viewers#1196]
I tried to use *cornerstoneWADOImageLoader* to laod dicom ImageIds from Orthanc,  but failed with CORS errors.
I access the following imageIds by *postman* correctly.
Appreciate to any response

```vuejs
            const imageIds = "wadouri:"+"http://127.0.0.1:8042/instances/8a327cd3-08cb5ede-20364c8c-01a0139b-cdbd2282/file"
            const element = this.$refs.act;
            cornerstone.enable(element);
            cornerstone.loadImage(imageIds).then(
                (image) => {
                        cornerstone.displayImage(element, image);
                    }
                )
```

**Comment by swederik** [comment]
It seems you have already identified the issue. You are getting CORS errors because CORS is not enabled on Orthanc. You need to put a proxy in front of Orthanc.

http://chafey.blogspot.com/2014/09/working-around-cors.html

One other thing: This issue is not related to this repository. For issues regarding the WADO Image Loader, you can post on the Issue Tracker for that project: https://github.com/cornerstonejs/cornerstoneWADOImageLoader

**Comment by dannyrb** [comment]
We do support passing in a URL to proxy as part of the dev server (this only works for dev, not production usage): (`PROXY_DOMAIN`)

- https://docs.ohif.org/essentials/data-source.html#running-orthanc

More on using `NGINX` in production to address CORS issues:

https://docs.ohif.org/deployment/recipes/nginx--image-archive.html#cors-issues
