### ISSUE TITLE
Brush radius as a percentage of viewport size

### ISSUE THREAD

**Issue by dannyrb** [OHIF/Viewers#1236]
The current brush tool uses a brush radius defined in pixels. At first glance, this seems okay, but it causes a large number of odd usability issues.

- Switching between different viewports changes brush cursor size
- Zooming causes brush to scale
- etc.

The brush tool is currently only available in the segmentation extension branch.

**Comment by pieper** [comment]
In slicer it works well to have a brush size that is a constant size in screen space (e.g. 3% of the size of the viewport).  This turns out to be very convenient because you end up using the zoom to control the brush size, which makes sense because when you are zoomed in you segment smaller features and zoomed out you segment larger ones.

**Comment by sedghi** [comment]
We opted for fixed size in mm as slicer. 
Read https://ohif.org/release-notes/3p7/
