### ISSUE TITLE
Measuring length function does not work under certain circumstances

### ISSUE THREAD

**Issue by Adaxuan** [OHIF/Viewers#1269]
### Describe the Bug

_A clear and concise description of what the bug is._

Under a muti-map layout ，after Levels、Pan operations in turn length function does not work  in  addition to Figure 1

### What steps can we follow to reproduce the bug?

1.  click ”Layout“button and choice more than two dicom picture
2.  click  “Levels” button and perform in every picture in turn
3.  click  “Pan” button and perform in every picture in turn
4.  click“Length”button and perform in every picture in turn，it dose not work in  addition to Figure 1

**Comment by dannyrb** [comment]
@Adaxuan, are you able to provide a video or GIF of this behavior? AFAIK, `length` tool only doesn't work if you're trying to annotate off the image. You can't start or complete a length annotation off the image, or else the resulting annotation will be removed.

**Comment by Adaxuan** [comment]
[lengthtool](https://github.com/Adaxuan/GIF/blob/master/length.gif)

**Comment by dannyrb** [comment]
Oh. That's really odd.
I was able to reproduce this issue on `production` and `dev` (latest).

- I don't see any console warnings/errors.
- It's interesting that the `cursor` shows as the `length` tool in the second viewport
- It's odd that this only impacts the second viewport
- This seems to only happen if we do `level`, `pan`, `length`
    - I can't recreate with other combinations
    - It's worth noting that `levels` is the default left click
    - It's worth noting that `pan` is the default middle click

I can see a similar behavior if I do: `zoom`, `pan`, `length`; only instead of defaulting to `levels`, we see the `length` cursor with `zoom` behavior.

If I inspect `cornerstone-tools` state (`cornerstoneTools.store.state.tools`), I can see all of the tools, their associated enabledElements, and their current bindings.

The first instance of `Zoom` has the following options set:

```js
{
  isMouseActive: true,
  isTouchActive: false,
  mouseButtonMask: [2],
}
```

The second instance of `Zoom` has the following options set:

```js
{
  isMouseActive: true,
  isTouchActive: false,
  mouseButtonMask: [1, 2],
}
```

It's `length` tool has the expected bindings, but the incorrect `mouseButtonMask` values for the `Zoom` tool steal the click event before it can reach the `length` tool.

This is most likely an issue within `cornerstone-tools`. More specifically, with how we resolve "input conflicts" when setting a new tool active. There are "resolvers" that tidy up a tool's `options` as new tools are activated.

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/store/setToolMode.js#L53-L79

**Comment by arthur-miller** [comment]
Hi!

I was able to reproduce the issue on [viewer.ohif.org](https://viewer.ohif.org/) (v2.9.0), but not on master (v3.7.1).
I also tried several different combinations from the ones you mentioned and everything seems to be working fine now.

**Comment by arthur-miller** [comment]
@dannyrb, can you try to reproduce this issue again, please?

**Comment by dannyrb** [comment]
@arthur-miller, I am unable to reproduce. I'm not sure why/how this was resolved, but I'll take the win ^_^
