### ISSUE TITLE
Support for window level presets

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1289]
Almost all dicom viewers offer a feature that allows predefined window levels to be set. For example for CT scans CT Abdomen,CT Angio,CT Bone,CT Brain,CT Chest,CT Lungs presets are available. This feature would be very useful in diagnosis. Perhaps some guidance on implementation can be had from here >>> https://www.radiantviewer.com/dicom-viewer-manual/change_brightness_contrast.htm

**Comment by swederik** [comment]
Yes we had that in the Meteor version but they haven't been added in the React UI yet. See https://viewer-legacy.ohif.org/

**Comment by ranasrule** [comment]
> 
> 
> Yes we had that in the Meteor version but they haven't been added in the React UI yet. See https://viewer-legacy.ohif.org/

I cant seem to find the feature in the Meteor version at the link you provided. Am I missing something?

**Comment by swederik** [comment]
It's in User Preferences

![Screenshot 2019-12-12 15 10 00](https://user-images.githubusercontent.com/607793/70718951-827abf80-1cf1-11ea-8880-29b20a386fbe.png)

**Comment by ranasrule** [comment]
> 
> 
> It's in User Preferences
> 
> ![Screenshot 2019-12-12 15 10 00](https://user-images.githubusercontent.com/607793/70718951-827abf80-1cf1-11ea-8880-29b20a386fbe.png)

how do we apply them to a window?

**Comment by ranasrule** [comment]
ok got it...via the numeric keys

**Comment by dannyrb** [comment]
Mentioned here: https://github.com/OHIF/Viewers/issues/1287

But this is a better tracking issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
