### ISSUE TITLE
How can implement login Authentication in Meteor based OHIF Viewer?

### ISSUE THREAD

**Issue by Vishal568** [OHIF/Viewers#1308]
Hello,

I want to log in authentication in meteor based ohif viewer so what I should. Is it already available in ohif?

**Comment by dannyrb** [comment]
👋 Hello @Vishal568, the core team no longer actively provides support for the previous Meteor version of this application. Given our limited resources, we've made this decision to better focus on improving the React version of the OHIF Viewer as we move forward.

We do have some guidance on setting up User Account Control w/ the OHIF Viewer and Keycloak:

https://docs.ohif.org/deployment/recipes/user-account-control.html

If you encounter any issues with that documentation, please let me know. It's been a while since I've given it a run through, but I'm more than happy to answer related questions and fix anything that may no longer be correct.
