### ISSUE TITLE
Docs (Whitelabelling) - example in docs assumes React is available in the global scope

### ISSUE THREAD

**Issue by whage** [OHIF/Viewers#1407]
[The part about whitelabelling](https://docs.ohif.org/viewer/themeing.html#white-labeling) (changing the logo on the UI) gives a code sample that calls `React.createElement()`. `React` however is not available in the context of the global configuration object and so the browser throws an error if I add that example to my `window.config` object.
It also shows a `props` object in the same code example but there is no mention of what it is.

What is the `props` object and how is it related to the global configuration or the `React` object?
How can I get a reference to the `React` object to create a custom element in place of the logo?

I'm using the ohif/viewer:v3.3.4.8766 docker image to run the viewer.

**Comment by dannyrb** [comment]
@whage, I think this is something we'll need to address with a PR. `window.config` can also be a function; we can provide the white-labeling function that returns a React element with `React`. If it's not a function, we can update `whiteLabelling` to support more values that could be used as props for a generic component (SVG resource uri, url, etc?)

**Comment by whage** [comment]
Can we expect a PR with a fix anytime soon?

**Comment by dannyrb** [comment]
@whage this is an Open Source project. Issues are addressed as individuals and organizations donate their time/resources, often dependent on their internal priorities. While someone will likely address this PR, I'm unsure of when.

If this is an issue you're interested in championing (or that is time-sensitive), but you're unsure of where to get started, I can provide brief technical guidance/scope so that you can draft a PR, or put you in contact with a contractor that could expedite/complete the work on your behalf.

**Comment by whage** [comment]
@dannyrb , understood. I'd like to help but I don't know React at all.

**Comment by whage** [comment]
@dannyrb , I drafted a quick & dirty fox, please take a look: https://github.com/OHIF/Viewers/pull/1465

**Comment by ZHEL12** [comment]
加上qq群；933241376

**Comment by dannyrb** [comment]
Fixed here: https://github.com/OHIF/Viewers/pull/1659
