### ISSUE TITLE
mouse wheel scrolling through study images broken?

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1435]
Scrolling through images of a series via the mouse wheel seems to be broken.

Im using version 3.6.1

Steps top reproduce:

1) open a study
2) open a series and use mouse wheel to scroll up and down. Scrolling dowb works but scrolling up does not.

**Comment by ranasrule** [comment]
anyone else notice this?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
