### ISSUE TITLE
Segmentation Settings UI - Phase 2

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1458]
Second part of #1370.

Now #1392 is complete, we need two more features from the original ticket:

## Overview:
- There needs to be a hide/show button for each segment on the segmentation.
- Clicking on the left of the panel should jump to the ticket.

Example: Eye icon on the right of the panel to toggle visibility. clicking on left panel containing color and number will jump to segment:
![Screenshot 2020-03-17 at 11 15 07](https://user-images.githubusercontent.com/25818497/76851350-06889a00-6841-11ea-8f90-88911e477a8e.png)

## Implementation Details:

- There should be UI to hide and show each segment within a segmentation.
This should hook up to the following cornerstoneTools segmentation module endpoints:

```js
setters.toggleSegmentVisibility(
  elementOrEnabledElementUID,
  segmentIndex,
  labelmapIndex
);

isSegmentVisible(
  elementOrEnabledElementUID,
  segmentIndex,
  labelmapIndex
)
```

- Clicking on the left of this panel should jump to the centre of the segment. For cornerstone: this can be done by the following procedure:

For a given segment Index:
- In the relevant `labelmap3D` Check if the segment is on each `labelmap2D` using the `segmentsOnLabelmap2D` array, store a list of all the indicies of these `labelmap2D` objects.
- Given the list of labelmap2D indicies, get the minimum and the maximum index and take the average.
- The index in the array closest to this average is the slice to jump to.

vtkjs specific logic shall be a seperate ticket:

**Comment by JamesAPetts** [comment]
On hold until further discussion about timeline for new OHIF UI.

**Comment by JamesAPetts** [comment]
@pieper @fedorov Is the desired functionality here correct?

**Comment by fedorov** [comment]
@JamesAPetts yes, this looks fine to me. Sorry for the delay, I missed the mention.

**Comment by fedorov** [comment]
The screencast below demonstrates some of the issues with the current interface:

It is basically not clear whether segmentations are available for a given study. Segmentations list shows as empty, and looks like one needs to load imaging series that has segmentations first before segmentations list is populated. And even after that there seems to be a delay in that list being populated. See screencast here:

https://www.screencast.com/t/g6wzeltT

The URL for that screencast is here: https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us-central1/datasets/lidc-idri-seg-sr-dcm/dicomStores/lidc-idri-seg-sr-dcm/study/1.3.6.1.4.1.14519.5.2.1.6279.6001.131383203689189807643685075952&sa=D&ust=1586369794567000&usg=AFQjCNHVY4eaLmveYQCRHA98Hwr7lOXIVA

Per discussion with @JamesAPetts, it would be good to:
* indicate to the user when segmentations are in the process of loading (right now, the segmentations list looks empty)
* show all segments in the right panel, without having to require the user to first guess the correct image series, and load it into the viewer
* when segments do have references to the image series they segment, it might be useful to be able to drag segment into the viewer, and automatically populate the viewer with the image series
* when segments do NOT have references to the image series, it should still be possible to configure the viewer to compose selected image series with the selected segment(s)
* navigating to the center of the segment (which is already mentioned in this issue) is critical - it is very tricky to find those small segments in large FOVs

Does this make sense, anything I missed @JamesAPetts?

**Comment by pieper** [comment]
@fedorov 

@swederik noticed that the extra tracking parameters on the URL pasted above breaks with the following error:

```
Request URL: https://healthcare.googleapis.com/v1beta1/projects/idc-tcia/locations/us-central1/datasets/lidc-idri-seg-sr-dcm/dicomStores/lidc-idri-seg-sr-dcm/dicomWeb/studies/1.3.6.1.4.1.14519.5.2.1.6279.6001.131383203689189807643685075952&sa=D&ust=1586369794567000&usg=AFQjCNHVY4eaLmveYQCRHA98Hwr7lOXIVA/series/undefined/metadata
Request Method: GET
Status Code: 404 
```
This one works:
https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us-central1/datasets/lidc-idri-seg-sr-dcm/dicomStores/lidc-idri-seg-sr-dcm/study/1.3.6.1.
4.1.14519.5.2.1.6279.6001.131383203689189807643685075952

So something, maybe slack, added this tracking stuff to the end:
```
&sa=D&ust=1586369794567000&usg=AFQjCNHVY4eaLmveYQCRHA98Hwr7lOXIVA
```

**Comment by fedorov** [comment]
No idea really, but I am glad you figured it out...

**Comment by fedorov** [comment]
@pieper @swederik @JamesAPetts I am really confused, need your help!

1) when I select segment from the dropdown, the content of the list below does not change - is this expected behavior or a bug? Screencast here: https://www.screencast.com/t/5l5ttFLWo4T

2) when I tried this same study (linked by @pieper in the comment above) some time ago over weekend (perhaps with a different version of OHIF Viewer) I was able somehow to display segmentation for the nodule in the screenshot 1 below, but now I don't see it. I know it should be there, because I made a screenshot for the paper (see screenshot 2 below). I have render inactive enabled (see screenshot 3 below), so I would expect that all segmentations should be rendered.
![image](https://user-images.githubusercontent.com/313942/78919860-84b31780-7a60-11ea-8832-78c010c25d3f.png)
![image](https://user-images.githubusercontent.com/313942/78919915-9f858c00-7a60-11ea-811b-90dbf70cc3ce.png)
![image](https://user-images.githubusercontent.com/313942/78920071-da87bf80-7a60-11ea-8feb-dcf4f6fb3679.png)

3) there are some warnings/errors in the console - are those of any relevance? 
![image](https://user-images.githubusercontent.com/313942/78920032-ce036700-7a60-11ea-9618-79af207233a1.png)

**Comment by JamesAPetts** [comment]
I'll move @fedorov 's comments to a new ticket, lets merge and close this one.
