### ISSUE TITLE
Heap out of memory

### ISSUE THREAD

**Issue by trung1704ptit** [OHIF/Viewers#1466]
Hi, 
I still get this error in development mode. ref to the bug:[https://github.com/OHIF/Viewers/issues/1408
]( https://github.com/OHIF/Viewers/issues/1408)

So I think we need to do something to fix it.
node --max-old-space-size=8192 yourFile.js
in package.json when whe run yarn start command.

I don't know yourFile.js in this product when we run yarn start.
Can you tell us about this

**Comment by trung1704ptit** [comment]
Hi there, I think I will close this issue, the reason because I used Nodejs 10.15.x => solution update Nodejs to 12.16.x

**Comment by desprit** [comment]
All similar issues have been closed but none actually states any working solution.
I'm on Node v13.9.0 and getting memory error even with `--max-old-space-size=8192`.

**Comment by sinryang** [comment]
I'm, also, have similar issues. 
All my trials to import @ohif/* library in react was failed because of memory error even with 16GB RAM.

Is there any updates?

**Comment by chengviz** [comment]
Is there any solution for this error?
I'm trying to import @ohif/viewer package and getting the same error. 
Im on Node v14.17.0

**Comment by thiagoss** [comment]
Just ran into this one as well when I've upgraded to latest react-scripts and react.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
