### ISSUE TITLE
Measurements when only Imager Pixel Spacing is present.

### ISSUE THREAD

**Issue by nutzlastfan** [OHIF/Viewers#1490]
I have DX Images from a Canon System where only Imager Pixel Spacing is present.
So without mapping Imager Pixel Spacing to Pixel Spacing (which is what I have done at the moment) I can only measure in pixels.
So the question is: from what i can gather normally Imager Pixel Spacing should be used when present,
if it is not Pixel Spacing should be used, when both are present and are not the same than Imager Pixel Spacing.
Can some clear this up for me ?

**Comment by dannyrb** [comment]
There has been some discussion on this issue here:
- https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/261#issuecomment-499951878

I believe the consensus was:

- Use `pixelSpacing`
- Up to applications to optionally use `imagerPixelSpacing`, may wish to indicate/warn user

Personally, I have worked on viewers that go so far as to fallback to ultrasound regions as a fallback for pixelSpacing settings so that current cornerstone-tools continue to measure in `mm`. The issue is that it's non-standard, and should be opt-in product owner, and they should _probably_ indicate that they're using a non-standard value.

We have some metadata changes (by the lovely @JamesAPetts) coming soon that centralize and simplify our metadata usage. This will make it easier for us, as an application, to deviate from the standard and make these decisions/fallbacks as we deem appropriate.

I'm speaking off the cuff, but that should be the gist.

**Comment by nutzlastfan** [comment]
Thank you, that helped especially the linked discussion. So in the end the best thing would be to warn the user in those cases if the measurements might not be accurate and have the the possibility to calibrate against known object in the image if available.
