### ISSUE TITLE
Length tool in modalities CT, DX, MG show the units in pixels

### ISSUE THREAD

**Issue by christianvargasforero** [OHIF/Viewers#150]
I have been testing the length tool in different modalities and I see that only in CT shows the units in mm. The tests were done on the most recent version of the viewer and the configuration used is that of dcm4cheeDIMSE.

In the DX, CR, MG modes, the tool displays the units in pixels.

I send the samples so they can try.

**DX --> Units in pixels.**
![dx](https://user-images.githubusercontent.com/11984387/34783065-7f306fa4-f5f8-11e7-93de-e8b4cb2dcba8.png)
**DICOM Files:**
[IM-0001-0001-0001.dcm.zip](https://github.com/OHIF/Viewers/files/1619605/IM-0001-0001-0001.dcm.zip)

**CR --> Units in pixels.**
![cr](https://user-images.githubusercontent.com/11984387/34783136-b523ef3c-f5f8-11e7-91d4-d5036f99b969.png)
**DICOM Files:**
[IM-0001-0001-0001.dcm.zip](https://github.com/OHIF/Viewers/files/1619607/IM-0001-0001-0001.dcm.zip)

**MG --> Units in pixels.**
![mg](https://user-images.githubusercontent.com/11984387/34783185-dc7ae338-f5f8-11e7-8503-75c8082c3669.png)
**DICOM Files:**
https://drive.google.com/file/d/1t5pS4QPjhIbUPvCGGY6CtgmNU9LeWlwf/view?usp=sharing

**CT --> OK units in mm.**
![ct](https://user-images.githubusercontent.com/11984387/34782778-b220e66a-f5f7-11e7-863e-e4a89dfdb30c.png)
**DICOM Files:**
https://drive.google.com/file/d/1EcO_5Gt8JxGs10ICcjgri1cQJXkRH1Za/view?usp=sharing

Thank you very much, I remain attentive to your comments.

**Comment by lam0620** [comment]
I add more image type

MR --> OK units in mm
RF, RG,US -->units in pixels 

I tried print out value "imagePlaneModule' on CR and CT image.
(cornerstone.metaData.get('imagePlaneModule', imageId))

There is not "rowPixelSpacing" and "columnPixelSpacing" in CR, so "pixels" unit is used.

Does anybody know the root cause?

Result:
1.CR
frameOfReferenceUID:undefined
imageOrientationPatient:undefined
imagePositionPatient:undefined
pixelSpacing:(2) [0.1, 0.1]
sliceLocation:undefined
sliceThickness:undefined

2.CT
columnCosines:s {x: 0, y: 1, z: 0}
columnPixelSpacing:0.5
columns:512
frameOfReferenceUID:"1.2.392.200036.9123.100.11.12.500000065.3.2017052614085796.1"
imagePositionPatient:s {x: 0, y: -128, z: 236.3}
rowCosines:s {x: 0, y: 0, z: -1}
rowPixelSpacing:0.5
rows:512

**Comment by kuronae12** [comment]
Hi guys, also experiencing this issue on DX and MG modalities, anyone have comments on this?

**Comment by christianvargasforero** [comment]
Resolved

**Comment by UdayRiaz** [comment]
Hi Christian Vargas,
Can you please help me out to get the fixed code of this thread, Still the measurement tool showing in pixels for MG and DX modalities with the latest git version of the viewer code.

**Comment by dannyrb** [comment]
This happens if the DICOM does not have a pixelSpacing tag. We need it to convert pixel length to `mm`.
