### ISSUE TITLE
Color Doppler overlay from one image remains visible on other stack images

### ISSUE THREAD

**Issue by shlomgad** [OHIF/Viewers#151]
Please check the following demo standalone viewer I have set up:

https://test-dot-qa-rad-consults.appspot.com/pacsseeohif?url=https://storage.googleapis.com/ohif-qa/test_json.json

The viewer loads 3 ultrasound images, the last one has color Doppler overlay. While scrolling back to the previous images the color overlay remains visible. (How is this even possible? the Doppler overlay is part of the pixel data, isn't it?)

A different installation of the standalone viewer mentioned in [this ](https://github.com/OHIF/Viewers/issues/91) issue (probably an earlier build) doesn't demonstrate this bug while loading the same images from the same JSON manifest:

http://ohif-viewer.s3-website.eu-central-1.amazonaws.com/?url=https://storage.googleapis.com/ohif-qa/test_json.json

Is this a bug introduced sometime between the two builds?

**Comment by swederik** [comment]
I have seen this issue as well recently when displaying a false color
image. I'll look into it. Thanks for the report!

**Comment by galelis** [comment]
Hey @shlomgad,

I have tried to reproduce it locally but I couldn't. As this issue is from January and the libraries have being changed since then, we are suspecting that it can be caused because of old libraries. 
Can you please try to use the latest code and see if you are still reproducing? 
If yes, can you please share with me steps you are using, I will be glad to help you. 

Thanks for your report.

**Comment by rossetantoine** [comment]
I can also reproduce this problem. It occurs only with ultrasound images, containing colours.
