### ISSUE TITLE
[User Preferences/Hotkeys] `Previous Series` and `Next Series` are throwing Uncaught ReferenceError

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1548]
## Bug Description

Once we press any of the hotkeys (`PAGE UP` and `PAGE DOWN`) assigned to **Previous Series** and **Next Series** function, nothing happens on the viewport and the following error is thrown on the console.

```
Uncaught ReferenceError: utils is not defined
    at updateViewportDisplaySet (commandsModule.js?66a2:36)
    at CommandsManager.runCommand (CommandsManager.js?a87a:184)
    at eval (HotkeysManager.js?9c96:206)
    at _fireCallback (mousetrap.js?77f4:616)
    at Mousetrap.self._handleKey (mousetrap.js?77f4:677)
    at Mousetrap.handleKey (mousetrap.js?77f4:1008)
    at Mousetrap._handleKey (recordPlugin.js?cb27:59)
    at Mousetrap.handleKey (recordPlugin.js?cb27:214)
    at HTMLDocument._handleKeyEvent (mousetrap.js?77f4:737)
```

<img width="500" alt="Screen Shot 2020-03-23 at 14 19 22" src="https://user-images.githubusercontent.com/13245529/77344108-77ccbf00-6d11-11ea-8705-901d27a19328.png">

### Steps to Reproduce

1. Visit https://viewer-dev.ohif.org/viewer/1.3.46.670589.6.1.0.98511171.2001010909203006
2. Open the browser's console
3. Press keys `PAGE UP` and `PAGE DOWN`
4. Verify that nothing happens on the viewport and an error is thrown on the console

### Expected Result

1. By pressing key `PAGE UP`, user should be able to navigate to the Next Series in the list
2. By pressing key `PAGE DOWN`, user should be able to navigate to the Previous Series in the list

**Comment by Reminisque** [comment]
I took a look at the code that produced the error after following the steps to reproduce and trace in the browser console. Below is the code found in lines 36-38 in `commandsModule.js`.
```
const studyMetadata = utils.studyMetadataManager.get(
  activeViewport.StudyInstanceUID
);
```
It turns out that `utils` was never imported to `commandsModule.js`. A bit of digging around the project directory led me to the `utils` folder in the `core` where `utils`, `studyMetadataManager.js`, and `get` can all be found.  Below are the paths from the project root to `commandsModule.js` and `studyMetadataManager.js`.
```
/platform/viewer/src/appExtensions/GenericViewerCommands/commandsModule.js

/platform/core/src/utils/studyMetadataManager.js
```
Adding `utils` to the existing import from `core` on line 1 seems to have fixed the problem for me. I submitted a pull request for the change.

Tested with latest version of viewer (2.9.4 I think).
Tested on Chrome Version 81.0.4044.138 (Official Build) (64-bit).

**Comment by sedghi** [comment]
I don't think our latest master branch has this error, please re-open if you see the issue. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
