### ISSUE TITLE
Switch asyncComponent to React Lazy/Suspense

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1577]
Here's an up-for-grabs ticket for someone that wants to play with React Lazy and Suspense. We are currently using a component called AsyncComponent to dynamically import and use components in some extensions. React now supports this natively, so we can remove these unnecessary components:

See 
https://github.com/OHIF/Viewers/blob/c5a4860209bf3f04f667c902cb2e47e1e47d8ab4/extensions/dicom-pdf/src/asyncComponent.js#L10-L35

https://github.com/OHIF/Viewers/blob/c5a4860209bf3f04f667c902cb2e47e1e47d8ab4/extensions/dicom-pdf/src/index.js#L4-L7

Instead of using AsyncComponent, we can use React.Lazy and wrap the import in the React.Suspense HOC. See https://reactjs.org/docs/code-splitting.html#reactlazy

**Comment by ankitmhn** [comment]
I shall take this up.

**Comment by ankitmhn** [comment]
Alright, so this is how I have the index.js file in one of the extensions: 
````
const Component = React.lazy(() => {
  return import('./OHIFCornerstoneViewport');
});

function OHIFCornerstoneViewport() {
  return (
    <React.Suspense fallback={<div>Loading...</div>}>
      <Component />
    </React.Suspense>
  );
}
````
I have replaced the `AsyncComponent` with a call to `React.Lazy` and updated the component by wrapping `<React.Suspense>` around it. However, it now throws the following error: 

> OHIFCornerstoneViewport.js?6845:139 Uncaught TypeError: Cannot read property 'studies' of undefined

I continue to debug this error but since I'm not yet completely familiar with the codebase, any guidance would be appreciated.
