### ISSUE TITLE
Question: Anybody using OHIF for Covid-19 research?

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#1637]
Title says it all. We would love to hear about any usage of OHIF or Cornerstone in the fight against Covid-19. If you don't wish to share publicly, feel free to send me an email.

Thanks!

**Comment by swederik** [comment]
Here's a press release from Massachusetts General Hospital regarding our upcoming paper in the Journal of Clinical Oncology: Clinical Cancer Informatics: https://www.massgeneral.org/news/press-release/open-health-imaging-foundation. The paper is co-authored by @chafey, @pieper, @JamesAPetts, @dannyrb, @urbantrinity and PI Gordon Harris.

We mention a few companies using OHIF / Cornerstone for Covid-19 research or in clinical practice:
- [DetectEdX](https://www.detectedx.com/)
- [VUNO](https://www.vuno.co/)
- [NextCloud](https://nextcloud.com/)

**Comment by reubenwenisch** [comment]
Yes, we are working on a COVID solution that uses OHIF.

**Comment by dannyrb** [comment]
👋 Hello, @reubenwenisch. Are you able to speak more about your organization and it's solutions?

**Comment by lucasheriques** [comment]
👋 Hi everyone! I'm part of a team that is using Cornerstone to develop a DICOM Image Editor and Annotator. 

It's a project from [the laboratory I'm a member](http://www.patreo.dcc.ufmg.br/), where the goal is to build a deep learning model to help with the diagnosis of COVID-19.

Our main challenge at the moment is getting a large enough dataset of thoracic X-rays the feature COVID-19 induced pneumonia. One of the ways that we're looking to improve this is using interactive learning for our model to get annotated data as an input. That's why we're building the DICOM Editor, where our goal is to get help from radiologists to annotate on X-ray images and then input this image to our model.

I hope I was clear enough with the main aspects, let me know if you have any questions.

I'm really thankful for Cornerstone, since it is the main enabler for the editor we're building. I would love to contribute to the project, if you guys need any help with the maintenance, since I believe it's of vital importance for current and future software focused on healthcare. If possible, I would love to get some pointers about a inicial simple issue that I would be able to help with.

[Here's a preview of the editor](https://lucasheriques.github.io/cadcovid19-dicom-editor/) (it's really simple at the moment, only basic tools implemented), and [here's a public page](https://cadcovid19.surge.sh/) about the project. It is in Portuguese, however.

**Comment by kzgrzendek** [comment]
Hello @swederik, I just saw the issue while brothing the Github, 

Yes, at EDS (APHP) we are currently working on a research project in correlation with COVID-19 called Neurocovid. Don't hesitate to contact me if you wish to know more about it, you have my mail address I believe :)

![image](https://user-images.githubusercontent.com/50668672/112877501-2050f400-90c7-11eb-9de5-bbf380d2439c.png)

Cheers

Kévin ZGRZENDEK
