### ISSUE TITLE
UI/UX - Double click viewport to toggle between full size and grid layout

### ISSUE THREAD

**Issue by eolasd** [OHIF/Viewers#1686]
In most commercial PACS viewers you can double click an image (a single viewport) to toggle between the grid layout (eg. 4x4) and full size (single viewport) on that image.

Is this currently possible in OHIF Viewer? 

I had a look through previous issues and code, but could not find any reference to this, and testing latest build does not seem have this function.

Happy to contribute this myself if its deemed an appropriate feature. I would just need some direction as to where to start - ie. in the UI components, or the VIEWER package? Or in the Cornerstone extension? Not sure yet how to get the props with the current viewport info.

Thanks!

**Comment by trung1704ptit** [comment]
I have alo the same proplem, how do you implement this? @eolasd

**Comment by sedghi** [comment]
This is already implemented in the master branch 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
