### ISSUE TITLE
save measurements format

### ISSUE THREAD

**Issue by fiona3668** [OHIF/Viewers#1705]
Dear developer：
Hi~ 
I  am trying this viewer recently, and I have some questions.
When we click the 'save measurements' bottom, what kind of data we are saving. And where is the directory of that saved measurements?
![image](https://user-images.githubusercontent.com/57859067/80831472-c0448b80-8b9f-11ea-94dd-e19fa8e63bf8.png)

**Comment by dannyrb** [comment]
👋 that particular save creates a "DICOM SR" (structured report) file and pushes it back to the configured DICOMWeb Server. This adds a DICOM file to the study.

We do this because OHIF is a simple web client and it makes for an easier demo, but creating a file for each incremental save is a bit odd. In real-world use, you might persist measurements in a database, then use DICOM SR as a way to encode a report, or as a more interoperable format for exporting and sharing a report with others.

Hopefully this answer helps. Let me know if you have any other questions or if you need clarification.
