### ISSUE TITLE
Measurements being stored as seperate study 

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1707]
I'm using the latest version of OHIF (built from source) and Orthanc. The bug can be reproduced as follows:

1) open study from studylist
2) make a measurement
3) save the measurement
4) open Orthanc explorer which will show that the measurements are not saved in the study but as a separate study
5) Also study can no longer be opened in OHIF viewer until the study with measurements is deleted.

![Annotation 2020-05-04 021303](https://user-images.githubusercontent.com/5023419/80925865-d7a49400-8dac-11ea-9225-9675fc7fae03.png)

**Comment by dannyrb** [comment]
They have the same studyInstanceUid, so that's odd. Unfortunately, the core team doesn't have funding/bandwidth (via the U24 Grant) for (most) fixes for this major version of OHIF. Hopefully a fix will be rolled up in the next major release.

If this is a major blocker for you, you can:

- draft a PR
- work with a consultant/consultancy to draft a PR
- Use a prior "known good" release

Thank you for your report!

**Comment by rlaxodnjs199** [comment]
I have the same issue. @dannyrb , if you don't mind, would you please suggest a "known good" release of this feature and how I can get it?

**Comment by ranasrule** [comment]
anyone find a resolution to this issue?

**Comment by james-hanks** [comment]
@jbocce to reproduce in current version and close if no longer an issue

**Comment by jbocce** [comment]
No longer able to reproduce this based on the steps outlined above in master 3.8.0-beta.6. The measurement SRs are being saved as separate series in the same study they were placed on.
