### ISSUE TITLE
Standalone client build i.promise.then is not a function

### ISSUE THREAD

**Issue by yehudahkay** [OHIF/Viewers#172]
Hi, I tried making a standalone client build but I get this error

![image](https://user-images.githubusercontent.com/9964988/37779253-a8c766fe-2df4-11e8-9417-92aa626d6399.png)

I tried using the client build included in the repository and it does work, but not with a new build

**Comment by LucasAntoniassi** [comment]
I have faced the same issue when attempting to load jpeg via the http(s) image loader. If you try to load the `simpleJpeg.json` example which contains a few jpegs it's going to fail. I investigated it a bit and I think it's because the `/client/compatibility/cornerstoneWebImageLoader.js` is old.

To fix that I've added the `cornerstone-web-image-loader` as a npm dependency to `ohif-cornerstone` package and loaded it in the `main.js` like the following:

`cornerstoneWebImageLoader.external.cornerstone = cornerstone`

I don't know if it is the best solution but I works for me. I hope it works for you too :)

**Comment by swederik** [comment]
Thanks @LucasAntoniassi!

**Comment by Zaid-Safadi** [comment]
This is fixed in PR #188, thank you @LucasAntoniassi for the information.

@yehudahkay, I see you submitted a PR  #185 to fix this (Thanks!) but seems you have a different approach and the diff is significant. Will you please describe more on the PR what changes you had to do?

**Comment by yehudahkay** [comment]
Hi, I had simply updated cornerstonewebimageloader.js to the latest version in the project. I don't know this project very well but your approach seems better.

**Comment by swederik** [comment]
Looks like this was fixed in #188. Thanks for the report!
