### ISSUE TITLE
Implement Error boundaries to catch uncaught JS errors in react components.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#1729]
Right now if a component throws an error the whole screen goes black.
We can use the follow React functionalty to give more useful errors:

https://reactjs.org/docs/error-boundaries.html

We should probably catch the error and display it in a notification, with the option to go back to the study list (or back on history step?)

@fedorov @pieper

**Comment by fedorov** [comment]
@JamesAPetts I don't know if this deserves a separate issue, but here's what I am facing:

When loading this study: https://idc-sandbox-000.firebaseapp.com/projects/idc-tcia/locations/us/datasets/issues/dicomStores/issue-2-kits/study/1.3.6.1.4.1.14519.5.2.1.6919.4624.239280682742083783797899101579

I get empty series list (not black screen), and the following in the console:

![image](https://user-images.githubusercontent.com/313942/82914050-0db4de00-9f3d-11ea-9af8-bf61f654b7c9.png)

Then when I click the Segmentations tab, I get black screen, and this error:

![image](https://user-images.githubusercontent.com/313942/82914115-1c9b9080-9f3d-11ea-923d-14dc46667d00.png)

Also, do you know if #1130 will work in this situation? I am able to load the study and seg into Slicer just fine, but I don't know if what I load from Storage bucket is the same that OHIF sees in the DICOM store. It would be good if download study function would work in this situation so I can try to debug the issue, if the issue is with the data.

**Comment by fedorov** [comment]
Just has this thought that when error happens, maybe as part of the error message there could be a link to download the study that was in the viewer at the time error took place?

**Comment by JamesAPetts** [comment]
cc @igoroctaviano : To @fedorov 's point we should have an error service that launches a custom component. The vanilla one can just display the message, then we can make a slightly different one for IDC that includes the download study function bound to a button?
