### ISSUE TITLE
Brush tool measurements

### ISSUE THREAD

**Issue by akhmrenata** [OHIF/Viewers#1749]
Hi! Recently we've added a FreehandRoi instrument and it was a trivial task since we needed only to define it in few places. Now we faced up with the need of the Brush tool. Fortunately it's already persist in cornerstone-tool. So we've done all the manipulations we did for FreehandRoi. So we can see the tool and even draw but it is. We cannot modify or delete it, but the main thing we don't have is the measurements data. Is there any possibility to get measurements (pixels positions) as for FreehandRoi or RectangularRoi tools for instance? Thanks in advance!

**Comment by j6u** [comment]
I am also curious if this is being worked on. If not I am happy to create a PR for this. I am not very familiar with how measurements work and what format it needs to be in for DICOM. Any clarification or help is appreciated here.

**Comment by sedghi** [comment]
I think the newest version of tool supports the data

Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
