### ISSUE TITLE
OpenResty-Orthanc-Keycloack failed to build

### ISSUE THREAD

**Issue by sinanmb** [OHIF/Viewers#1757]
Hi,

I'm following the steps to implement [User Account Control](https://docs.ohif.org/deployment/recipes/user-account-control.html) and want to use the docker image for OpenResty-Orthanc-Keycloack.

I have an error related to the location of the dockerfile, which I fixed in docker-compose.yml by replacing `./docker/OpenResty-Orthanc-Keycloak/dockerfile ` by `./.recipes/OpenResty-Orthanc-Keycloak/dockerfile`

Now I have an other error that I don't know how to solve. 
`Step 7/24 : COPY yarn.lock /usr/src/app/yarn.lock
ERROR: Service 'ohif_viewer' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder969429843/yarn.lock: no such file or directory`

Can someone please point me in the right direction?

**Comment by dannyrb** [comment]
:wave: many of these files have moved since that guide was originally written. An unfortunate side-effect of documentation that isn't living documentation (generated from code).

If you encounter issues and manage to resolve them, it would be a huge help to others if you created pull requests to update the docs.

If you can link to your dockerfile or docker-compose in a gist, it would be easier to determine where things are hung up.

**Comment by sinanmb** [comment]
Hi @dannyrb sorry for the delay, please find the gist [here](https://gist.github.com/sinanmb/6936c87f10a41094341c5c20f3d9c4aa).

Absolutely I'm willing to update the documentation as I manage to solve this. I also have a [pull request](https://github.com/OHIF/Viewers/pull/1774) currently waiting to be merged to update another part of the documentation.

**Comment by sinanmb** [comment]
Hi @dannyrb, please let me know if you have any pointers for this issue. Thanks.

**Comment by sedghi** [comment]
We have fixed this recipe https://docs.ohif.org/deployment/user-account-control

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
