### ISSUE TITLE
STOW SR Error while saving the measurements.

### ISSUE THREAD

**Issue by pecons** [OHIF/Viewers#1763]
I'm trying to store annotations locally but when i click on save it throws an error. when i see the console appears a cors error but i have nginx installed

![image](https://user-images.githubusercontent.com/42283812/83566078-09606600-a4e5-11ea-8464-d8c5e38e1f4d.png)

here's my viewer conf 
![image](https://user-images.githubusercontent.com/42283812/83566180-33b22380-a4e5-11ea-938f-d93ef0ebb0f9.png)

when i change to wadors  throws the Error 400 seen on this issue https://github.com/OHIF/Viewers/issues/220

![image](https://user-images.githubusercontent.com/42283812/83566291-64925880-a4e5-11ea-8b3e-5c85510bd594.png)

ty btw.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
