### ISSUE TITLE
2D MPR not working with multiframe NM series

### ISSUE THREAD

**Issue by wkochFPV** [OHIF/Viewers#1765]
Multiplanar reconstruction seems not to be available in OHIF viewer when a multiframe nuclear medicine study is viewed.

Series contains transverse slices of a SPECT reconstruction.
Series is stored in a single DICOM file (on a DCM4CHEE-ARC server)
Viewer correctly displays the series.
(OHIF in PWA mode deployed on an apache2 server)

--> MPR button is not visible
(--> if forced to display the button (_isstudyreconstructable forced to be true), only a blank screen is displayed when clicking the 2D MPR button.)

Is there any way to fix this?

Best regards,
  Walter

**Comment by wkochFPV** [comment]
Here is a simple example of a basal ganglia phantom scan to reproduce the issue.
[DC3BDB9D.zip](https://github.com/OHIF/Viewers/files/4763463/DC3BDB9D.zip)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
