### ISSUE TITLE
inverted instance number

### ISSUE THREAD

**Issue by web2ls** [OHIF/Viewers#1766]
i have get latest version from master branch

In the ViewportOverlay i get fully inverted instance_number value of current slice

For example:
if i placed on the first slice of 112 that i get instance number equals to 112
if it is second slice that i get instance number equals 111
and so on

if i try get image info on the first slice in series via cornerstone.metaData.get('generalImageModule', imageId) that i get wrong instance_number inside

![report](https://user-images.githubusercontent.com/17110375/83739297-13f23b00-a65e-11ea-9582-6e73a5bb4cec.gif)

**Comment by web2ls** [comment]
i found separate function for revert instance_number value in array
Does anyone know why?

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

Please try and re-open if the issue persists
