### ISSUE TITLE
how can i update a specific image after loading all the images in a series

### ISSUE THREAD

**Issue by web2ls** [OHIF/Viewers#1780]
my goal is to redraw a particular image after I went into the viewer and all the images are already loaded

my attempt step by step:

- get imageId i want to redraw

- clear current images cache via cornerstone.imageCache.purgeCache()

- load and cache my image again via cornerstone.loadAndCacheImage(imageId)

- after that promise has been resolved i get enabledElement and try redraw my image via cornerstone.drawImage

but the resulting image has not changed

please tell me what I'm doing wrong

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
