### ISSUE TITLE
PDFViewport "Next" button in pager toolbar is not working.

### ISSUE THREAD

**Issue by wtlatli** [OHIF/Viewers#1788]
The problem exists in version 4.2.3

Steps to reproduce:

1. Have a study in which the is an encapsulated PDF document with two pages.
2. Select the document from the series list.
3. Once the document is displayed try to navigate to next page

The navigation will not occur.

**Comment by JamesAPetts** [comment]
The next button in the toolbar is generic and cycles through series. If you only have one series (the PDF report), the button will not do anything.

You would need to make custom functionality for the behavior you describe.

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

Please try and re-open if the issue persists
