### ISSUE TITLE
how can I get measurmentData from the annotation box?

### ISSUE THREAD

**Issue by panzhengo1** [OHIF/Viewers#1804]
fresh man here,
![image](https://user-images.githubusercontent.com/41532053/85377824-37791900-b56c-11ea-82cd-c8c98499b015.png)
how can I get data of the annotation box, such as max, min, mean std Dev or sth else.
ohif/core managing a study measurments, but how can i read it

**Comment by yash0906** [comment]
for the length, some information is being displayed on console, not sure about the other annotations. i also need some help regarding this.

**Comment by MarlonLiu1991** [comment]
@panzhengo1 @yash0906 All the annotations's measurements can be got in the component "MeasurementTalbe", in the component you can use " this.props.measurementCollection.measurements" to get all the annotations

**Comment by panzhengo1** [comment]
> @panzhengo1 @yash0906 All the annotations's measurements can be got in the component "MeasurementTalbe", in the component you can use " this.props.measurementCollection.measurements" to get all the annotations

Thank you for your answer, I got what i want

**Comment by yash0906** [comment]
@panzhengo1 
you can also get the measurements from cornerstone tools.
_cornerstoneTools.globalImageIdSpecificToolStateManager.toolState;_
this will return all the data about each and every measurement

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
