### ISSUE TITLE
Export study failed with LesionTracker

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#182]
At study list, I can export study successfully with OHIFViewer.
However, I got export failed with LesionTracker.

I got console error:
GET http://34.224.187.57:4000/__wado_proxy?........ 401 (Unauthorized)

I already logged in and then export. 
Does anyone give me why?

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

For future issues, if you include a minimal reproduction, it is easier for us to jump in and help. Unfortunately, there is very little to go off of in your original issue description. I hope you were eventually able to work things out! ^_^
