### ISSUE TITLE
Value exceeds max length

### ISSUE THREAD

**Issue by akosijoy** [OHIF/Viewers#184]
Hello, 

I was hoping to ask for some help on how to debug this problem as tracing the cause of an error with ohif is proving difficult for me. The error is:

 `
/Viewers-master/OHIFViewer/.meteor/local/build/programs/server/packages/dimseservice.js:4321 throw 'Value exceeds max length';
^
Value exceeds max length
Exited with code: 1
Your application is crashing. Waiting for the file change
`

I'm running OHIF on centos 7 as a systemctl service. Whenever this error appears, it is resolved by simply stopping and starting the service again. But since this is a recurring issue, this is very inconvenient. And so I'm opting to ask for help on how to solve this problem. 

Thank you

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

I hope you were eventually able to resolve your issue. I know things like this can be particularly frustrating.
