### ISSUE TITLE
Problem trying to load several studies

### ISSUE THREAD

**Issue by sgala** [OHIF/Viewers#1936]
> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

### Describe the Bug

When I try to load something like https://viewer.ohif.org/viewer/1.2.826.0.13854362241694438965858641723883466450351448;1.3.6.1.4.1.25403.345050719074.3824.20170126085406.1 (i.e. several StudyInstanceUIDs together, in late 4.2.X versions it gives me an exception and shows only one of them.

### What steps can we follow to reproduce the bug?

1. First step

Build a master viewer

2. Second step

Load two studies separated by semicolon

```js
Please use code blocks to show formatted errors or code snippets
```

Expected behavior: series of both studies load in their viewports

Seen: an exception in console and on screen.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
