### ISSUE TITLE
OHIF tools not visible for microscopy

### ISSUE THREAD

**Issue by ambawaleankita** [OHIF/Viewers#1938]
Hi Guys,

Currently, I'm able to load study in ohif viewer locally but not able to see any other tools like Annotate, Length, Pan for 'SM' modality. Is there any settings needed to enable those tools?
Please check the screenshot for your reference.

![image](https://user-images.githubusercontent.com/21143159/88913146-0338fc80-d27e-11ea-8348-e60184db880a.png)

**Comment by pieper** [comment]
Hi - 

The microscopy plugin uses a different underlying library (openlayers instead of cornerstone) so we can't enable the same tools directly.

But there is a proof of concept annotation example to generate structure reports that correspond the the ones generated for radiology images.  You can try it out here: https://microscopy.dcmjs.org/structured_report/index.html

Eventually we plan to further develop and push this functionality into OHIF proper.

**Comment by ambawaleankita** [comment]
Thanks for the quick response.
It would be great to know by when would this be added

**Comment by pieper** [comment]
It's hard to say, but I'm pretty sure there's nobody actively working on this at the moment so maybe a year or two at least.  In the next year or so we'll be working more on the microscopy display features before annotations.  Even the dicom standards for representing annotations on microscopy images are still being developed.  Not trying to be discouraging, just want to you know the state of things.  I'll close this but feel free to ask more questions as needed.  If you can help with implementation that would be most welcome.

**Comment by Mohtashim890** [comment]
Hello. I am facing the same problem. Any updates on development of OHIF tools for microscopy extension? Any better solution for displaying dicom-microscopy images?

**Comment by pieper** [comment]
We have been using Slim: https://github.com/MGHComputationalPathology/slim

It has some annotation tools and more are in active development.
