### ISSUE TITLE
Missing "since" argument error

### ISSUE THREAD

**Issue by joweste** [OHIF/Viewers#1944]
Hi, I juist installed ORTHANC  with default install.
I am using OHIF embedded viewer in a html page.
I am getting the next error.
What can I fix it?

```
W0801 11:30:54.957844 main.cpp:1109] DICOM server listening with AET ORTHANC on port: 4242
W0801 11:30:54.957844 HttpServer.cpp:1298] HTTP compression is enabled
W0801 11:30:54.957844 main.cpp:1011] Remote LUA script execution is disabled
W0801 11:30:54.957844 HttpServer.cpp:1205] HTTP server listening on port: 8042 (HTTPS encryption is disabled, remote access is not allowed)
W0801 11:30:54.957844 main.cpp:814] Orthanc has started
E0801 11:37:43.686146 OrthancException.h:76] Bad request: Missing "since" argument for GET request against: /studies/

```
```
window.OHIFViewer.installViewer(
      {
        routerBasename: "/",
        extensions: [],
        showStudyList: true,
        filterQueryParam: false,
        servers: {
          dicomWeb: [
            {
              name: "ORTHANC",
              wadoUriRoot: "http://localhost:8042/wado",
              qidoRoot: "http://localhost:8042/dicom-web",
              wadoRoot: "http://localhost:8042/dicom-web",
              qidoSupportsIncludeField: false,
              imageRendering: "wadors",
              thumbnailRendering: "wadors",
            },
          ],
        },
      },
      containerId,
      componentRenderedOrUpdatedCallback
    );
  },
```

**Comment by gsaielli** [comment]
I have the same exact issue. Any news?

**Comment by gsaielli** [comment]
In the Chrome debugger the error I see is:
GET http://my.orthancsrv.com/Orthanc/studies?limit=25&offset=0&includefield=all&StudyDate=19531101-20220413 400 (Bad Request)

While according to Orthanc docs (https://api.orthanc-server.com/index.html#tag/Studies/paths/~1studies/get) the parameter should have been named "since" and not "offset",

**Comment by alhaag** [comment]
facing the same problem Bad request: Missing "since" argument for GET request against: /studies/

Using the latest versions of Orthanc and OHIF.

Has anyone managed to get around it somehow?

**Comment by swederik** [comment]
I think you are looking at the Orthanc API. OHIF does not use the Orthanc API, it uses the API provided by the Orthanc dicomweb plugin. The endpoints have similar names, but you are probably missing a prefix to the dicomweb endpoint.

If someone wants to write an OHIF data source to use the Orthanc API that may also be an option, but it's not a priority on our end.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by alhaag** [comment]
Perfect, I ended up forgetting to come back here and give feedback. @swederik was precise in his comment, it wasn't a bug, it was hitting the Orthanc API instead of dicomweb which has some similar endpoints, hence the confusion. Thanks
