### ISSUE TITLE
Unable to compile/build ohif viewer 4.4.0

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#1998]
Im unable to compile/build ohif viewer 4.4.0. My yarn and node version are up to date. The errorI get is in the screenshot below.

![Annotation 2020-08-19 175222](https://user-images.githubusercontent.com/5023419/90638697-1587d400-e247-11ea-9682-5e21c123d8d4.png)

**Comment by swederik** [comment]
I just pushed a fix for this but apparently the CI did not cut a release properly. I'll try to fix that. You can clone from master and it should work fine.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
