### ISSUE TITLE
OHIF Viewer touch support

### ISSUE THREAD

**Issue by Richard-WITS** [OHIF/Viewers#20]
Hi,

First, fantastic project.  The viewer currently _almost_ support touch but requires a double-click to open studies from the worklist which breaks support on most mobile devices.  The upstream Cornerstone demo supports touch.  Is there any way to get this working?  It is incredibly powerful to show the viewer on a tablet.

**Comment by swederik** [comment]
Thanks Richard!

Touch support is something we've been meaning to work on but isn't a top priority. Everyone is busy at the HackFest this week but I can try to sort that issue out next week for you.

Cheers,

Erik

**Comment by Richard-WITS** [comment]
Hi Erik,

I hope the HackFest went well.  Let me know if there is any way we can help with this.

Richard

**Comment by swederik** [comment]
I've added HammerJS to allow double tapping on the study list and long-pressing to open the context menu. There is obviously more work to be done to get the viewer to work perfectly on all devices, but this is a start.

Note that you may need to change the wadoUriRoot to the local IP of your computer when testing on mobile devices.

So instead of 

````
"wadoUriRoot" : "http://localhost:8043/wado",
````

You need something like:

````
"wadoUriRoot" : "http://192.168.0.3:8043/wado",
````

**Comment by Richard-WITS** [comment]
We have tested this change on both Android and IOS devices.  So far it looks great!  Thank you!
