### ISSUE TITLE
[IDC] Support reporting of problematic studies - Part 2 - Post report to IDC Discourse.

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#2006]
Follow up to #1939

Post report of problematic studies to IDC Discourse.

- Be able to automatically post a user defined issues/message to the IDC Discourse.
- Autogenerate screenshots of the application.

**Comment by fedorov** [comment]
So what would be the workflow for posting to discourse? At what point the user would need to log in? Did you think the process to be fully automatic, or OHIF would pre-populate the post for the user and let them click "submit"?

A simpler approach would be to pre-generate an email text, or send email to support@canceridc.dev. Emails sent to that address will show up on discourse, but in a private category, so we can triage it. Another benefit is that even users who are not registered with discourse can post to that address.

**Comment by JamesAPetts** [comment]
For the MVP we will just have a mailto button:
- This should copy in the debug table to the body if possible.

**Comment by fedorov** [comment]
Looks like the following two might fulfill many of the Discourse integration needs!
* https://meta.discourse.org/t/compose-a-new-pre-filled-personal-message-via-url/35984
* https://meta.discourse.org/t/compose-a-new-pre-filled-topic-via-url/28074

Maybe just adding a pre-populated Discourse link side by side with the mailto might be sufficient?

**Comment by JamesAPetts** [comment]
Sure thing, we'll need to do this in the IDC fork though, as its rather use case specific. Once we have closed the other major open tickets we can update the fork and work on it in there.

**Comment by JamesAPetts** [comment]
The last discourse bit has been pushed to post MVP on the fork.

**Comment by igoroctaviano** [comment]
@fedorov regarding this issue...
- Using widgets like https://widgetbot.io/ we can create a very limited **_message-only_** panel like:
![image](https://user-images.githubusercontent.com/13886933/110715755-99ee7400-81e4-11eb-970e-a2f4314d2a86.png)
- To use advanced features like attachments, we'll need to Implement a server-side bot (using https://discord.js.org/#/) or a proxy since Discord doesn't allow connecting to the API as a bot from a browser. We may do it using Bearer tokens but it will require us to implement its oauth2 flow which I think may not worth the trouble since mailto would cover the requirements + user wouldnt need to authenticate.

**Comment by pieper** [comment]
Does this support Discourse or only Discord?

**Comment by igoroctaviano** [comment]
> Does this support Discourse or only Discord?

Ops... I thought I had read Discord haha 🌝 , I'll revisit the issue and update the findings here.

**Comment by fedorov** [comment]
Unless development for this issue is well underway, I suggest de-prioritizing it under idc:candidate for the sake of focusing efforts on other priority tickets.

**Comment by pieper** [comment]
good idea, done

**Comment by sedghi** [comment]
@igoroctaviano @fedorov is this valid?

**Comment by fedorov** [comment]
This is IDC-specific and should not be in the OHIF tracker. I think it is here because early on we did not know how to separate such issues.
