### ISSUE TITLE
Measurement error (pixel resolution) for XA (ImagerPixelSpacing (0018,1164))

### ISSUE THREAD

**Issue by rossetantoine** [OHIF/Viewers#201]
The measurements produced by OHIF are wrong, if pixel resolution is stored in ImagerPixelSpacing fields).

See attached image and DICOM file: the diameter should be 3 mm, instead of 15 mm.

The DICOM file is also attached.

[XA-DICOM.dcm.zip](https://github.com/OHIF/Viewers/files/2086809/XA-DICOM.dcm.zip)

<img width="823" alt="ohif" src="https://user-images.githubusercontent.com/1857100/41190027-89efe3c0-6bd7-11e8-94e7-2e336f586777.png">

**Comment by dannyrb** [comment]
I believe this has been resolved. If you're still seeing this issue in `master`, please don't hesitate to comment and I will be more than happy to re-open and investigate further.

**Comment by Zaid-Safadi** [comment]
This is not resolved, the value is only displayed in pixels rather than "mm" (which is better) but we should be able to display a valid measurement "3 mm" as other viewers 

Latest OHIF Master:
![image](https://user-images.githubusercontent.com/10813109/69481794-6070da00-0de2-11ea-815e-9dd0e8f21cd5.png)

MicroDicom
![image](https://user-images.githubusercontent.com/10813109/69481817-9e6dfe00-0de2-11ea-9296-968abb8d731f.png)

**Comment by dannyrb** [comment]
Read @chafey's comments here: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/261#issuecomment-499951878

We can't use `imagerPixelSpacing` as a fallback, or at least we shouldn't in these libraries. It introduces a hazard that should be a deliberate decision for anyone creating a viewer implementation.

That, at least, has been the guidance for all `cornerstone` libraries to date. Stick to the standard and try not to make allowances for vendors that don't adhere to them.

---

@swederik is the product owner. If you can convince him otherwise, we could introduce it as a fallback in OHIF libraries. We also have the ability to show a warning, highlight the hazard, or make this an opt-in behavior. The issue then becomes, if we persist these annotations, that warning likely wouldn't be recorded with what would be perceived as 100% accurate measurements.

**Comment by Zaid-Safadi** [comment]
I would recommend we keep this open for reference as this is something that OHIF as a viewer/display application needs to address. 

Whether reading the imagerPixelSpacing value in cornerstone library or directly in OHIF is agnostic from the fact that there are cases where the user wants to display the measurements in "mm" if imagerPixelSpacing is the only attribute available which is the current behavior in the original post and the viewers I have seen so far.

**Comment by swederik** [comment]
This was fixed (finally) by https://github.com/OHIF/Viewers/pull/1555

<img width="712" alt="Screenshot 2020-03-25 at 23 58 34" src="https://user-images.githubusercontent.com/607793/77593490-92ab5900-6ef4-11ea-859b-f190650354d1.png">
