### ISSUE TITLE
SEG source series should also be parsed from SourceImageSequence

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2017]
## Request

`SourceImageSequence` should be parsed to determine the image series that is associated with segmentation.

**Why should we prioritize this feature?**

As observed from debugging https://github.com/ImagingDataCommons/IDC-WebApp/issues/238, segmentations from TCIA ISPY collection are using [`SourceImageSequence`](https://dicom.innolitics.com/ciods/segmentation/general-reference/00082112), not [`ReferencedImageSequence`](https://dicom.innolitics.com/ciods/segmentation/general-reference/00081140) to refer to the image series segmented.

In the retrospect, I wonder if the approach used in I-SPY is the correct one. We use ReferencedImageSequence in dcmqi, and @dclunie never called out for using SourceImageSequence, so maybe what we do in dcmqi is still the right way to do it. Need to check with David.

**Comment by JamesAPetts** [comment]
Good catch, think I originally used the dcmqi SEGs as examples! ^_^.

It actually appears `SourceImageSequence` is the correct one: 

`SourceImageSequence`:
- "The set of Image SOP Class/Instance pairs of the Images that were used to derive this Image."
- I.e. the imaging stack?

`ReferencedImageSequence`:
-Other images significantly related to this image (e.g., post-localizer CT image or Mammographic biopsy or partial view images).
- I.e. localizers etc (related images).

**Comment by fedorov** [comment]
@JamesAPetts yes, when I read it, I had the same thought, but it is the case that what we have in dcmqi was checked and double checked by David Clunie via our joint work on many datasets we shared created by dcmqi, so I am puzzled ... I will ask David when I get a chance.

**Comment by dclunie** [comment]
Hi James

A few things to consider:

- how do the segmentation pixels correspond to image pixels when no frame of reference is defined (e.g., for 3D projection images (like chest x-rays), for which FoR UID is omitted):

"each pixel of the segmentation shall correspond to a pixel in a referenced image, using the Derivation Image Functional Group"

- when an FoR UID is present, from what images was the segmentation "derived":

"The Derivation Image Functional Group may also be present, to specify on which images the segmentation was actually performed (since there may be others in the same Frame of Reference that are spatially co-located, but were not used to perform the segmentation)"

- what images should a viewer allow a user to select from, to display the segments superimposed upon, to which the general answer is (a) whatever has the same FoR UID, if present, otherwise (b) only what is referenced from the Derivation Image Functional Group (which contains Source Image Sequence)

- what images should a viewer default to selecting to display the segments superimposed upon, to which the general answer is what is referenced from the Derivation Image Functional Group (which contains Source Image Sequence) either if FoR UID is not present because there is no other choice, if FoR is present because it is as good a choice as any other; if Derivation Image Functional Group is absent there is no information to help with this decision

It is very important to look first at the mechanisms that are specific to to Segmentation IOD and the enhanced multi-frame family of objects that it is based on, rather than make generic assumptions based on experience with single frame derived images (to which the General Reference Module applies).

In particular, the Source Image Sequence in the Derivation Image Functional Group may be per-frame rather than shared, and is distinct from the Source Image Sequence in the top level data set (General Reference Module), which may be absent.
 
See:

  http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.51.5.html#sect_A.51.5.1

The text in the earlier section:

  http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.51.html

is a little confusing and could be improved, since it mentions "referenced images" rather than "source images".

You might well ask why the General Reference Module is included in the Segmentation IOD at all, since it just confuses things.

As for the QIICR SEG objects, AFAIK they use Source Image Sequence in the Derivation Image Sequence in the Per-Frame Functional Group Sequence items (i.e., on a per-frame basis) as they should, and Source Image Sequence is not present in the top-level data set, and Referenced Image Sequence is not used.

David

**Comment by fedorov** [comment]
> As for the QIICR SEG objects, AFAIK they use Source Image Sequence in the Derivation Image Sequence in the Per-Frame Functional Group Sequence items (i.e., on a per-frame basis) as they should, and Source Image Sequence is not present in the top-level data set, and Referenced Image Sequence is not used.

David, SEG objects, as produced by dcmqi, will contain the following:
* Referenced Image Sequence > Referenced Instance Sequence at the top-level, listing all instances which were matched from the source DICOM series passed by the user of the conversion tool, and which were determined to match slices of the segmentation based on a dcmqi heuristic
* Source Image Sequence in Derivation Image Sequence per-frame (based on the same heuristic as above, and listing the same instances per-frame as in the top-level Referenced Image Sequence).

Now that you mentioned the "little confusing" text in http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.51.html, maybe that text is the reason for using Referenced Image Sequence in the top level. I don't know.

But the bottom line is that all of the objects produced by dcmqi so far follow those conventions above, and we set the precedent.

Going forward, do you think we should change to Source Image Sequence at the top level? At this point, we do have the "install base" though.

**Comment by dclunie** [comment]
Are you sure about dcmqi including Referenced Image Sequence in the top level data set (TLDS)?

I looked at the Iowa HN (and LIDC) SEG objects, and they include Referenced Series Sequence (+/- Studies Containing Other Referenced Instances Sequence) (Common Instance Reference Module) in the TLDS, which includes Referenced Instance Sequence within it, to provide the "hierarchical relationships of any SOP Instances referenced from other Modules" ([http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.12.2.html](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.12.2.html)).

But I did not see Referenced Image Sequence in the TLDS.

A viewer should be looking in the Derivation Image Functional Group, and only using the TLDS Referenced Series Sequence or Studies Containing Other Referenced Instances Sequence to obtain hierarchical parent information for a hirarchical retrieval of the referenced objects, if necessary.

**Comment by fedorov** [comment]
@dclunie you are correct, I mis-read the dump - it is [Referenced Series Sequence](https://dicom.innolitics.com/ciods/segmentation/common-instance-reference/00081115) indeed, NOT Referenced Image Sequence. I think I got confused because Referenced Image Sequence is a sibling of Source Image Sequence.

**Comment by JamesAPetts** [comment]
Going to close this for now, I've made the required upgrades to read all the data I can see on IDC. I tested 20-30 studies looking for edge cases but all seem good now. If you find an edge case/if there is any fundemental issue you encounter please open another ticket.

Thanks.
