### ISSUE TITLE
[Bug] There is wrong for image of patient 

### ISSUE THREAD

**Issue by thanhtd1012** [OHIF/Viewers#2021]
## Bug Report
When running the latest version. I detected an error when view image of patient:
![image](https://user-images.githubusercontent.com/70577879/91846957-8508b500-ec84-11ea-8683-9ac708b7cec7.png)

When  running the old version, then view image below:
![image](https://user-images.githubusercontent.com/70577879/91847064-8b972c80-ec84-11ea-8a00-f763b522f729.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
