### ISSUE TITLE
Area Measurment Feature

### ISSUE THREAD

**Issue by laithdj** [OHIF/Viewers#2031]
Hi there ,

is there  a chance to add a feature for 'Area' measurement to the viewer . Or if it exists somewhere can i please know where i can
find it and add it to the viewer?

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

Please try and re-open if the issue persists
