### ISSUE TITLE
"Send Bug Report" does not work

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2051]
### Describe the Bug

Clicking "Send Bug Report" in "Debug info" extension does not have any effect.

![2020-09-20_22-26-27](https://user-images.githubusercontent.com/313942/93729117-1f2b9100-fb91-11ea-8636-397eea23317f.gif)

### What steps can we follow to reproduce the bug?

This is reproducible in the viewer under idc-testing and in the sandbox.

Maybe something is missing in the configuration?

**Comment by JamesAPetts** [comment]
Which browser was this on?

This works for me on the IDC sandbox on Firefox, Safari and Chrome.

Maybe a particular study hit some strange edgecase in this is a red herring, do you have a link to the exact study?

**Comment by fedorov** [comment]
That was on Chrome, here's the sandbox URL (I keep using the one for series selection): https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_mvp_wave0/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.6279.6001.131383203689189807643685075952/?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.6279.6001.214252223927572015414741039150,1.2.276.0.7230010.3.1.3.0.3098.1553287530.406853

**Comment by JamesAPetts** [comment]
Strange, I can't reproduce, works for me on chrome with the above link. Perhaps your browser is set to block mailto links?

Upon clicking my mail opens with the following content:

<img width="1394" alt="Screenshot 2020-09-22 at 11 06 57" src="https://user-images.githubusercontent.com/25818497/93869719-18516b00-fcc4-11ea-89e9-4eb9e86ecb4e.png">

**Comment by fedorov** [comment]
I tried with Firefox and Safari, and when I click there, it switches focus to the Chrome window. Then I tried a random page with "mailto", and the behavior is the same actually! Maybe it has to do with Gmail configured as my "mailto" client? I thought it is not system-wide, but maybe it is.

Would it be possible to add a "copy to clipboard" button? If it's complicated, maybe just add a note to copy paste the content of the debug window, and specify the support email where it should be sent?

**Comment by JamesAPetts** [comment]
> Would it be possible to add a "copy to clipboard" button? If it's complicated, maybe just add a note to copy paste the content of the debug window, and specify the support email where it should be sent?

Lets do this on the fork 👍 . I'll edit this issue.

**Comment by fedorov** [comment]
The email button works for me in Chrome with Gmail configured as email client on mac. @gundluru can you provide details about your configuration?

**Comment by pgundluru** [comment]
I have tested this issue in 2 workstations and am seeing inconsistent results. I believe having Gmail configured as email client is going to be necessary for the bug report to work otherwise it appears to be non functional (even though bug report button is currently functional)

Please see steps below that i used to reproduce this issue:

I selected ACRIN collections and opened up studies level to view the bug reports 

Windows 10 Workstation: 
Chrome with no blocks on Gmail and correct hander settings (see image below) - unsuccessful with 404 error 
Edge - Unsuccessful 

Mac Workstation:
Chrome with Gmail configured as email client - bug report is successful with correct details
Edge with Gmail configured as email client - successful with correct details 
Safari with Gmail mailto extension not configured - Not successful (due to not having Gmail client configured)

![image](https://user-images.githubusercontent.com/85526819/132026062-42420181-fa3a-41fe-a0ad-af6c9dcc9ca9.png)
![image](https://user-images.githubusercontent.com/85526819/132026152-a5f1cc98-12e4-4984-a368-7844a7dc47c1.png)

**Comment by pieper** [comment]
Thanks for checking this.  Looking around it seems that the `mailto` tag is not considered reliable and there's no good way for the web app to know if it will work or not.  I don't mind leaving it, since people will presumably realize if it doesn't work for them and they will fallback to the copy method.  But if we think it's confusing then I would be fine with removing the mail link and just saying the info needs to be pasted into an email message.

**Comment by fedorov** [comment]
I am fine keeping it as is.
