### ISSUE TITLE
my local ohif gone

### ISSUE THREAD

**Issue by atiya1-hub** [OHIF/Viewers#2055]
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

**Description**

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by atiya1-hub** [comment]
I made a restart to my computer with an updated operating system, then try to access localhost:3000 not working, however, before the restart, it was working fine, how I can fix this problem

Thanks

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
