### ISSUE TITLE
Length measurements not getting saved

### ISSUE THREAD

**Issue by rongaza** [OHIF/Viewers#2066]
### Describe the Bug

Length measurements are not getting saved.

I get a successful "Stow SR Measurements Saved Successfully" after saving a measurement.

When I log out and back in I do not see my saved measurement.

We are using the google healthcare api to store our datasets. 

### What steps can we follow to reproduce the bug?

1- Access the application
2- Navigate to Study Viewer page
3- Add 2 length annotations
4- Expand the Measurements panel and add a new Label and Description to both annotations
5- Click on "Save measurements" button
6- Log Out

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
