### ISSUE TITLE
Image rendering is only half done

### ISSUE THREAD

**Issue by josephgogh** [OHIF/Viewers#2067]
### Describe the Bug

Use the Viewer to view an dicom image,but dicom image rendering is only half done.
like this
![image](https://user-images.githubusercontent.com/30017948/94355459-cee39000-00b6-11eb-82ae-a0326241d2b0.png)
but correct dicom image would look like this
![Uploading image.png…]()
.so i don't know why it's rendered this way

**Comment by josephgogh** [comment]
the file in question
[1.3.12.2.1107.5.1.4.87023.30000020092002215518200001643.zip](https://github.com/OHIF/Viewers/files/5287705/1.3.12.2.1107.5.1.4.87023.30000020092002215518200001643.zip)

**Comment by krushnavadan** [comment]
i am facing same issue , does any one has solution

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
