### ISSUE TITLE
SR Reports are not displayed when navigating from one to the next

### ISSUE THREAD

**Issue by sgala** [OHIF/Viewers#2072]
> **Before Creating an issue**
>
> - Are you running the latest version?

This happens both in viewer.ohif.org, see for instance https://viewer.ohif.org/viewer/1.3.6.1.4.1.14519.5.2.1.6279.6001.265704884949271879044145982159
 and building master

> - Are you reporting to the correct repository?

I think so
> - Did you search existing issues?

I think so

### Describe the Bug

When one tries to navigate from one series to the previous or next, by pressing pgup or down (this only in master, does not work in viewer.ohif.org) or with the mouse, the selected series is shown. Except when the currenly selected series is a SR and we select another SR. Then the new series is not displayed.

### What steps can we follow to reproduce the bug?

Go to https://viewer.ohif.org/viewer/1.3.6.1.4.1.14519.5.2.1.6279.6001.265704884949271879044145982159 click on the first series, then the first SR and check the ContentTime. Select the second SR and the ContentTime does not change. Now click the first series and then the second SR; the second ContentTime will be shown. Clicking in the first one will not update the display.

**Comment by kswedberg** [comment]
I'm seeing this, too. Possibly related: when I run the viewer in dev mode locally, I'm seeing an error when I select an SR…

```Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>.```

**Comment by sedghi** [comment]
Try here https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463

Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
