### ISSUE TITLE
measurement not save in ohif viewer

### ISSUE THREAD

**Issue by atiya1-hub** [OHIF/Viewers#2078]
> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

### Describe the Bug

_A clear and concise description of what the bug is._

### What steps can we follow to reproduce the bug?

1. First step
2. Second step
3. ...

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by atiya1-hub** [comment]
once save measurement or clicked save measurement display green alert save measurement successfully, however, if you do refresh for a page or got out of the application (ohif viewer) it's gone measurement or not display any manipulate on Dicom image

**Comment by lanesky** [comment]
**Describe the Bug**
Same issue here.  
If you save SR multiple times, only the annotation or length saved in the first time would be displayed.
Seems like all SRs were saved into DCM4chee server successfully, but only the first-time version can be displayed by OHIF Viewer.

**OHIF Viewer Version**
4.12.7

**What steps can we follow to reproduce the bug?**

1. Add an annotation or length
2. Click "Save measurements" button, it displays a green alert saying save measurement successfully
3. Refresh page
4. Add another annotation or length
5. Click "Save measurements" button, it displays a green alert saying save measurement successfully
6. Refresh page again, then you will find the second annotation or length won't display at all.

**Comment by michaelkain** [comment]
Hi,
I hope you are all doing fine.
I am facing the same issue. I am now able to stow-rs the structured report in our internal pacs. When I check in the pacs the structured report is well stored and aligned with the patient and the referencing SeriesInstanceUID matches with the original one. The viewer displays when re-opening the serie an icon SR (below Research Derived series, S: 99), but does not overlay (as during the creation) the measurement done on the original serie. I would be happy for any help here. It would be really great, when not an error on my side, if the viewer would restore the measurements as the users will be confused not finding back their annotations. Thank you and with kind regards, Michael

**Comment by michaelkain** [comment]
Hi, sorry for having you bothered! I solved it, the issue was on my side. One of my backend responses was not yet implemented, that delivered the content of the DICOM SR: /dicomweb/studies/XXX/series/YYY/instances/ZZZ, now it works nicely. Keep going with your nice viewer, greetings from the black cat developers: https://shanoir.org!

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
