### ISSUE TITLE
 prefix setting to allow the standalone viewer to run from http://server/path rather than http://server

### ISSUE THREAD

**Issue by SachidanandAlle** [OHIF/Viewers#2099]
Reference: https://groups.google.com/g/cornerstone-platform/c/OWB0LTkBIUs/m/Iru_mf3zAgAJ

https://github.com/OHIF/Viewers/issues/115

What is the solution for this issue in latest version of OHIF?

**Comment by swederik** [comment]
You probably need to set routerBasename in the app config: https://docs.ohif.org/configuring/

There are two paths you can set for OHIF:
1. Where should the application look to find the rest of its assets (set PUBLIC_URL env variable before building the app)
2. What the 'base' path for the application (i.e. where is index.html hosted)? (routerBasename relative path in the app-config.js file). Since the application uses client-side page routing, this is required for it to know which page it should be showing.

PUBLIC_URL should be a full path to the place where the actual viewer files are being hosted from (e.g. the S3 bucket). The user may never even see this URL, depending on your setup.

routerBasename is only the fragment from the root URL where the viewer is reached by the end user. E.g. if the user hits the viewer at amazing-webapp.com/ohif, then routerBasename should be "/ohif". That way, the client-side routing logic can figure out if it sees /ohif/viewer in the location bar, which "page" it should show. If the routerBasename is wrong, the application doesn't know which page to show, and you get the "Sorry that page doesn't exist" messages.

Hope that helps. We should add this to the docs since we get this question a lot.

**Comment by SachidanandAlle** [comment]
Thanks this works 👍
