### ISSUE TITLE
Internet dependency

### ISSUE THREAD

**Issue by matthiasg** [OHIF/Viewers#2109]
Even though most users would have access to the internet and the google domain is pretty safe from a security standpoint. When trying to version the code for compliance, I would rather have the option to integrate the external reference. This would also allow for intranet deployments without internet access (which many radiologist use)

https://github.com/OHIF/Viewers/blob/352407c71ae93946e9ebad41446d6086cfbc237b/platform/viewer/public/init-service-worker.js#L6

**Comment by swederik** [comment]
I completely agree that there should be no internet dependency. We also
need to remove polyfill.io usage.

**Comment by matthiasg** [comment]
The 'stale' bot is quite quick :) I added a pull request to address it now if anybody is interested. 

I am still trying to deepen my understanding of the project and as such and as always would welcome any feedback.

**Comment by salimkanoun** [comment]
Hi, just in case, this commit has a side effect for users who will serve OHIF through Apache as the distribution now contains .mjs file that are emited with text/plain MIME Type (instead of javascript). 
This has been fixed recently in apache 2.5.1 (https://github.com/apache/httpd/blob/trunk/CHANGES) (jun 2022) but many linux distro are not updated yet

**Comment by sedghi** [comment]
@matthiasg @salimkanoun Do you know if this still is a problem?

**Comment by sedghi** [comment]
@matthiasg @salimkanoun bump
