### ISSUE TITLE
How to save a report to the DICOM images as done by the measurement extension?

### ISSUE THREAD

**Issue by randikabanura** [OHIF/Viewers#2112]
I want to save a report (user typed) to the dicom images as done by saving the information from the measurement extension. So user should be able to see the saved report in a later date. Is there any way to achieve this?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
