### ISSUE TITLE
RTSTRUCT tab is shown when not applicable, does not load when opened

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2117]
If I open this study, it shows the dose image, and somehow RTSTRUCT tab button is populated. When I click that button, I get a spinner and nothing loads.

Study: 1.3.6.1.4.1.14519.5.2.1.1706.4009.149676576527243140820654927789
Series: 1.3.6.1.4.1.14519.5.2.1.1706.4009.104748144873675756696310742946

![image](https://user-images.githubusercontent.com/313942/96172386-5bce7c00-0ef4-11eb-8dc9-e5492b9f8aa3.png)

**Comment by fedorov** [comment]
Seems to be reproducible with any RTDOSE? 

![image](https://user-images.githubusercontent.com/313942/98252284-ba14da80-1f47-11eb-8b7c-cc9efd86260e.png)

**Comment by igoroctaviano** [comment]
@fedorov I have opened the PR to dynamically disable the RT panel if there are no rtstructs. 

About this study uid you gave: 1.3.6.1.4.1.14519.5.2.1.1706.4009.149676576527243140820654927789 
Its not showing because the only series which have RTs its modality is CT and not RTStruct so now at least the button will be disabled for those. The other series is RTDOSE but they dont have any RTs.

The same happens here: http://localhost:3000/projects/chc-tcia/locations/us-central1/datasets/hnscc-3dct-rt/dicomStores/hnscc-3dct-rt/study/1.3.6.1.4.1.14519.5.2.1.2193.7172.113038498776356011546245623307
- This one again, CT modality with RTStructs and other series with modality RTDOSE and empty RTs.

**Comment by fedorov** [comment]
That's very weird, I need to look into that... I will assign this to myself to hopefully not forget about it...

**Comment by fedorov** [comment]
> Its not showing because the only series which have RTs its modality is CT and not RTStruct so now at least the button will be disabled for those. 

@igoroctaviano I looked, and I do not understand your point.

In that study referenced above, RTSTRUCT series is definitely RTSTRUCT. Can you explain your point?

**Comment by igoroctaviano** [comment]
> > Its not showing because the only series which have RTs its modality is CT and not RTStruct so now at least the button will be disabled for those.
> 
> @igoroctaviano I looked, and I do not understand your point.
> 
> In that study referenced above, RTSTRUCT series is definitely RTSTRUCT. Can you explain your point?

Hey @fedorov sorry for my poor attempt to explain it, actually i got confused understanding the issue, you can forget what i have said previously. The problem was caused by a reactivity bug with the panel and the active viewport, the loading should only appear for rtstructs and be empty otherwise. I have updated the PR so now the panel will behave correctly.

**Comment by fedorov** [comment]
I get this error now when I open the study: 
![Uploading image.png…]()

**Comment by igoroctaviano** [comment]
> I get this error now when I open the study:
> ![image](https://user-images.githubusercontent.com/313942/101645754-b8d24400-3a04-11eb-83cb-318bfca0b42c.png)

@fedorov this is caused

**Comment by igoroctaviano** [comment]
@Punzo https://github.com/OHIF/Viewers/pull/2207 should fix the issue reported above, also it should fix reactivity issues with RTPanel.

**Comment by Punzo** [comment]
perfect I'll test https://github.com/OHIF/Viewers/pull/2207 now
