### ISSUE TITLE
typing a space (" ") in patient name form (study list view) causes the entire page to go black/crash

### ISSUE THREAD

**Issue by shivasuri** [OHIF/Viewers#2134]
> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

### Describe the Bug
In title.

_A clear and concise description of what the bug is._

### What steps can we follow to reproduce the bug?

Run locally. To reproduce, run locally with `yarn install`/`yarn start`. Then, type a single space in "Patient Name"

```js
Please use code blocks to show formatted errors or code snippets
```
Log trace on console:

![image](https://user-images.githubusercontent.com/22109813/97093075-0d109880-15fe-11eb-947d-6a6972b09c55.png)

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
