### ISSUE TITLE
Timezone Issue in datetime picker

### ISSUE THREAD

**Issue by SachidanandAlle** [OHIF/Viewers#2136]
The end date for filters (studies) is based on local time.  This is causing some of the studies not matched (which are recently loaded on server sitting in different timezone.

Example:
DICOM Server: UTC
Client/Browser: PDT (not ok; some studies missed due to 8 hrs difference)
Client/Browser: UTC (ok)

Tried to manually select next day as end day... but before query is fired to dicom server next-day becomes today

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
