### ISSUE TITLE
Where is the Context Menu in v2.0.0?

### ISSUE THREAD

**Issue by dmumedical** [OHIF/Viewers#2144]
In the Meteor version there was a context menu, accessible via right click on studies:

![Context Menu](https://i.imgur.com/VSHkHjB.png)

The menu had a distinct export feature I need to use:
![Export Modal](https://i.imgur.com/Mjoor6T.png)

I can't find it in v2.0.0 - was it moved? Or disabled?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
