### ISSUE TITLE
Basic auth  in get frame requests does not work

### ISSUE THREAD

**Issue by dyens** [OHIF/Viewers#2181]
Hi!

I try to use BasicAuth in OHIF with my local dicomweb server. I have:

```js
  servers: {
    dicomWeb: [
      {
        name: 'My local dev',
        qidoRoot: 'https://127.0.0.1:8080',
        wadoRoot: 'https://127.0.0.1:8080',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
        requestOptions: {
          auth: 'username:password',
	},
      },
    ],
  },

```
QIDO requests like get studies, get series works fine. Request for get metadata works fine too.

But in the get frame requests like:

https://127.0.0.1:8080/studies/1.2.826.0.1.3680043.8.1055.1.20111102150758591.92402465.76095170/series/1.2.826.0.1.3680043.8.1055.1.20111102150758591.96842950.07877442/instances/1.2.826.0.1.3680043.8.1055.1.20111102150831466.74318282.34203447/frames/1

there is no Authorization headers.

Is there any way to add `Authorization headers` for all requests?

**Comment by yvedant** [comment]
I'm facing exactly the same issue. In wado request while fetching the instances somewhere we need to include the authorization header i.e. `headers: DICOMWeb.getAuthorizationHeader(server)` but can't figure out exactly where.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
