### ISSUE TITLE
504 timeout error when loading large MRI studies

### ISSUE THREAD

**Issue by kavijoshi92** [OHIF/Viewers#2183]
I am experience 504 timeout error when loading MRI studies from orthanc with approx. 20 series and 1000 images. The issue is even with smaller size of 500-600 images. 
The viewer starts loading for sometime and then goes blank. The error in devtools show 504 gateway timeout.
Attached screenshot of the error, can anyone advise how to resolve this issue?
I am using OHIF with Orthanc on reverse proxy in nginx.
![504error](https://user-images.githubusercontent.com/66158160/100080769-3a09d280-2e6c-11eb-8b25-edf10ae5e6cc.JPG)

**Comment by gh94uk** [comment]
Hey, how did you manage to fix this issue? I'm getting the same error. Thanks in advance.

**Comment by igoroctaviano** [comment]
I worked with studies that had 1-2k images in them and they could be loaded. This type of problem could have many different causes like VM unavailable because it's scaling in the middle of the request or something.

Not sure if it's your case but after merging, exponential backoff could potentially help these kinds of scenario: https://github.com/OHIF/Viewers/pull/2408

**Comment by gh94uk** [comment]
Thanks for the info and quick reply! In our case, we're on a pretty old version but it seems to work by removing Nginx from the equation (probably a timeout setting or something).
