### ISSUE TITLE
Blank black page while OHIF/study is loading

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#2202]
When a study is opened a blank black page shows while OHIF viewer is being loaded whereas on the 1.x Meteor version a "loading" screen was shown which was a lot more user friendly as it gave the user an indication that the loading process is under way.

**Comment by ranasrule** [comment]
OHIF viewer takes a while to load when it opened after clearing the browser cache and all that is displayed while its loading is a blank black page. Would it be possible to add some kind of loading progress indicator as this would make things a bit more user-friendly?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
