### ISSUE TITLE
Can't change the main viewport between different structure report by clicking the thumbnail in the left panel.

### ISSUE THREAD

**Issue by thylakoids** [OHIF/Viewers#2217]
## Bug Report
Thank you for creating this amazing project.

### Cann't switch between different SR(structure report)

_When open a study with multiple SR series, can't change the main viewport between different structure report by clicking the thumbnail in the left panel._

### What steps can we follow to reproduce the bug?

1. Open a study with multiple SR series.
2. Click one of the SR thumbnail on the left panel, now the active viewport will show the corresponding SR.
3. Click a different SR thumbnail, the active viewport stays the same. While, it is expected to show the new SR.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
