### ISSUE TITLE
DICOM SR in OHIF build in not presented

### ISSUE THREAD

**Issue by ruska03** [OHIF/Viewers#2224]
When I run **yarn othanc:dev** SR is presented within the series correctly but when I build the package (**yarn build:package**) and import it in another React app and use it with OHIFViewer.installViewer it is not presented and the error in the console is presented. 

![image](https://user-images.githubusercontent.com/72269025/103534990-310b1880-4e90-11eb-97cb-bfed14fd012e.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
