### ISSUE TITLE
dicom-tag-browser extension not working

### ISSUE THREAD

**Issue by charleschen** [OHIF/Viewers#2230]
## Bug Report

dicom-tag-browser extension now working.  

### Describe the Bug

when extension is included in configuration, "Tag Browser" button shows on study view, but when clicked an error is thrown on console:

```
index.umd.js:185590 Uncaught TypeError: Cannot read property 'getDisplaySets' of undefined
    at openDICOMTagViewer (index.umd.js:2)
    at CommandsManager.runCommand (index.umd.js:135320)
    at ToolbarRow._handleToolbarButtonClick (index.umd.js:116188)
    at handleClick (index.umd.js:16426)
    at Object.ka (index.umd.js:185588)
    at qa (index.umd.js:185588)
    at ra (index.umd.js:185589)
    at wa (index.umd.js:185589)
    at Aa (index.umd.js:185590)
    at ya (index.umd.js:185590)
```

### What steps can we follow to reproduce the bug?

https://codesandbox.io/s/intelligent-khorana-enll5?file=/index.html

**Comment by charleschen** [comment]
looked into the stack trace and found that in `openDICOMTagViewer`, `studyMetadataManager.all()` returns an empty list.  So for some reason no metadata is retrieved by the manager?  I'm pretty new to this so not sure how to debug further.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
