### ISSUE TITLE
Double click to maximise viewport/ revert to previous layout

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#2266]
Is there any way possible to toggle between full size viewport and toogle it back to previous layout by double clicking.  I saw a post but that does not seem to be valid as may files either are merged or have been deleted.

Thank you!

**Comment by PoyangLiu** [comment]
There is a [DoubleTapFitToWindowTool in cornerstoneTools](https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/DoubleTapFitToWindowTool.js).  You just have to add it to the [Viewers cornerstone package init.js](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone/src/init.js#L57)

**Comment by richsmith123** [comment]
Dear PoyangLiu,

Truly appreciate your help in guiding me, thank you!!

Best regards,

**Comment by richsmith123** [comment]
Dear PoyangLiu,

I tried your suggestion however, it did not gave me the outcome I was expected.  I came across more recent [post](https://github.com/OHIF/Viewers/pull/1860) but this seems to be not merged with the main branch as the functionality is not there. 

Hence, I posted new community [request ](https://github.com/OHIF/Viewers/issues/2269) which was already echoed by David.

Thanks!

**Comment by sedghi** [comment]
Done in master 
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
