### ISSUE TITLE
UI/UX - Double click viewport to toggle between full size and grid layout

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#2269]
Hello, 

In most commercial PACS viewers you can double click an image (a single viewport) to toggle between the grid layout (eg. 4x4) and full size (single viewport) on that image.  This is useful if measurement is needed to make a single viewport full size.

This question has been asked earlier [post](https://github.com/OHIF/Viewers/issues/1686) by David Connaughton however, no helpful response was given.  Wondering if anyone could shed some light.

Thanks!

**Comment by praispranav** [comment]
Please give an update or any solution for this

**Comment by jensen0914** [comment]
> Can this be implemented in OHIF V2 ?

Hello, I have implemented this in a branch of my fork of OHIF v2 (https://github.com/jensen0914/Viewers/tree/saincepacs-ohif-viewer). The code is dependent upon other changes, such as reference lines and syncing slices but allows users to double-click on regular and 2D MPR viewports to switch back and forth from full-screen and also adds a toolbar button/command for this.

Todd Jensen, PhD
Jensen Informatics LLC

**Comment by YogeshTDev** [comment]
Hello, Thank you for your help... It would be helpful if you point me to the commits or the files that needs to be changed in order to add the feature to my current viewer, Yogesh Jadhav,Web Dev Sent from Mail for Windows From: Todd JensenSent: 02 June 2023 17:28To: OHIF/ViewersCc: Yogesh Jadhav; CommentSubject: Re: [OHIF/Viewers] UI/UX - Double click viewport to toggle between full size and grid layout (#2269) Can this be implemented in OHIF V2 ?Hello, I have implemented this in a branch of my fork of OHIF v2 (https://github.com/jensen0914/Viewers/tree/saincepacs-ohif-viewer). The code is dependent upon other changes, such as reference lines and syncing slices but allows users to double-click on regular and 2D MPR viewports to switch back and forth from full-screen and also adds a toolbar button/command for this.Todd Jensen, PhDJensen Informatics LLC—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by jensen0914** [comment]
I highlighted a commit you can start with in the screenshot in my last comment: commit fecf77. Also look at 686de7, 849c5b.

**Comment by YogeshTDev** [comment]
Hi, Thank you for the Help.Implemented the feature in V2.   Yogesh Jadhav,Web Dev From: Todd JensenSent: 02 June 2023 18:08To: OHIF/ViewersCc: Yogesh Jadhav; CommentSubject: Re: [OHIF/Viewers] UI/UX - Double click viewport to toggle between full size and grid layout (#2269) I highlighted a commit you can start with in the screenshot in my last comment: commit fecf77. Also look at 686de7, 849c5b.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by sedghi** [comment]
This is implemented already in master branch

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
