### ISSUE TITLE
Error: GetStudyMetadata

### ISSUE THREAD

**Issue by NMCHos** [OHIF/Viewers#2273]
hello all,
i was used ohif with orthanc pacs server, all thing works fine, and i was able to view the studies is correct way. recently i connect CT device to orthanc but unfortunately when viewing studies of the CT is faces the following error:
 
Error: GetStudyMetadata: No study data returned from server: 1.3.12.2.1107.5.1.4.36624.30000021020812251232800000080 

what to do to solve this issue?

**Comment by olivert1969** [comment]
Hi @NMCHos 
Are you able to view the study using Orthanc's native viewer? How are you storing the studies? in the database or in a filesystem?

**Comment by NMCHos** [comment]
> 
> 
> Hi @NMCHos
> Are you able to view the study using Orthanc's native viewer? How are you storing the studies? in the database or in a filesystem?

yes i able to view studies using native orthanc viewe and other viewers like RadAnt

**Comment by olivert1969** [comment]
Hi @NMCHos - sometimes when Orthanc viewer works, but OHIF viewer has this particular error message, we've found that clearing the browser cache and/or rebooting the client computer resolves the issue.

**Comment by NMCHos** [comment]
> 
> 
> Hi @NMCHos - sometimes when Orthanc viewer works, but OHIF viewer has this particular error message, we've found that clearing the browser cache and/or rebooting the client computer resolves the issue.

i try form different browsers form different computers, also clear cache and restart == all these steps does not make any difference.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
