### ISSUE TITLE
Stack Scroll not in order

### ISSUE THREAD

**Issue by 1774575836** [OHIF/Viewers#2284]
> **Before Creating an issue**
>
> - Are you running the latest version?
Yes
> - Are you reporting to the correct repository?
Yes
> - Did you search existing issues?
Yes

### Describe the Bug

Build and install latest release, connected with Orthanc server with several studies. One study stack scroll images not in order from 1-xxx. Using Orthanc built-in viewer(Osimis/Stone web viewer) to check, the images can be viewer in correct order. 
the studies in test server temporary located here:
http://47.98.186.14:8080/orthanc/osimis-viewer/app/index.html?series=ea98233a-a8406dbd-ef76afa1-36ed91c6-e448a7b7

### What steps can we follow to reproduce the bug?

1. First step
modify app-config.js to point to our test server:
        wadoUriRoot: 'http://47.98.186.14:8080/orthanc/wado',
        qidoRoot: 'http://47.98.186.14:8080/orthanc/dicom-web',
        wadoRoot: 'http://47.98.186.14:8080/orthanc/dicom-web',

2. Second step
go to study P0000147531, check the serial with 116 images, scroll images, order started from 58,116,57,115,56,114......
3. ...

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by Prashant117** [comment]
hi @1774575836 , did you get to resolve the issue as I am also facing the same.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
