### ISSUE TITLE
How to segregate the left sidebar as a single component?

### ISSUE THREAD

**Issue by proteeti13** [OHIF/Viewers#2286]
For my project, I want to segregate the sidepanel (the photo is attached)  as a single component. I have been exploring the codebase, but I am clueless where and how to start. Please help me where and how can I start [ The folder structures, the dependencies I will need and the components ] 

Also, while exploring the components, I found out that the ImageThumbnail.js component (which I will probably need) requires `import { utils } from '@ohif/core';`. I am confused on how to import while I will generate it as a single component. 

Thanks. Hoping to get some responses.
![git](https://user-images.githubusercontent.com/11318378/109482072-be8d7200-7aa7-11eb-8949-c83c1f698046.png)

**Comment by sedghi** [comment]
What do you mean can you explain more?


Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
