### ISSUE TITLE
Demo site segmentation not shown anymore

### ISSUE THREAD

**Issue by vsaase** [OHIF/Viewers#2287]
Hi,

I am not sure if this site : https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.6279.6001.224985459390356936417021464571?seriesInstanceUID=1.2.276.0.7230010.3.1.3.0.57823.1553343864.578877,1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680 (I got the link from @fedorov in an unrelated issue) is running the current version of OHIF-Viewer, but there seems to be a bug that was introduced in the last few days so that the segmentation is not shown anymore.

**Comment by Punzo** [comment]
Hi @vsaase by checking the console errors, this seems correlated to https://github.com/dcmjs-org/dcmjs/issues/177

**Comment by fedorov** [comment]
@vsaase thank you for reporting this, and sorry we missed it in our testing.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
