### ISSUE TITLE
Show some kind of loading indication

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#2291]
When OHIF viewer is loaded it just shows a black screen while its being loaded in the browser which makes the user think  nothing is happening. In version 1.x a "loading" message was shown. Can this simple but essential feature be added?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
