### ISSUE TITLE
Error while saving the measurements.

### ISSUE THREAD

**Issue by minhneo** [OHIF/Viewers#2294]
> **Before Creating an issue**
>
> - Are you running the latest version?
Yes
> - Are you reporting to the correct repository?
Yes
> - Did you search existing issues?
Yes

I want delete the old measurements. While press Save measurements button, Notify is:
STOW SR
Error while saving the measurements.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
