### ISSUE TITLE
Opening the localhost:3000 page at the first time is very slow

### ISSUE THREAD

**Issue by bianyueyan** [OHIF/Viewers#2296]
I am running the latest version.

I deployed the dcm3chee-arc-light at my local computer, then connected with the OHIF viewer. When I open the localhost:3000 page at the first time, it is very slow. I checked the network information with dev tool, I found the reason is that there is the file "app.js" with the size of 46.8 MB. It is too large. Please give a solution for how to compress this file making faster.

**Comment by dfsRony** [comment]
I face similar problem, but in my case it is not first time load, it takes a few minutes to fully load the page.

**Comment by PoyangLiu** [comment]
OHIF uses webpack to bundle all the libraries together.  If you'd rather have several smaller files to download instead of one large one, you can use the [SplitChunksPlugin](https://webpack.js.org/plugins/split-chunks-plugin/).

There are lots of articles on Google showing you how to do it.  Here is one article that advocate on one chunk per library to take advantage of HTTP/2 multiplexing.
https://medium.com/hackernoon/the-100-correct-way-to-split-your-chunks-with-webpack-f8a9df5b7758

**Comment by bianyueyan** [comment]
> OHIF uses webpack to bundle all the libraries together. If you'd rather have several smaller files to download instead of one large one, you can use the [SplitChunksPlugin](https://webpack.js.org/plugins/split-chunks-plugin/).
> 
> There are lots of articles on Google showing you how to do it. Here is one article that advocate on one chunk per library to take advantage of HTTP/2 multiplexing.
> https://medium.com/hackernoon/the-100-correct-way-to-split-your-chunks-with-webpack-f8a9df5b7758

Thanks for your answer. I found the commented parameter "compress: true" in the file "viewer/.webpack/webpack.pwa.js". I uncomment this parameter, then it works.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
