### ISSUE TITLE
Question about adding custom Cornerstone tool

### ISSUE THREAD

**Issue by henryhe1** [OHIF/Viewers#230]
Related to #38 

I want to add the [freehandROI tool](https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/freehandRoi/index.html) from CornerstoneTools to the OHIFViewer (not lesiontracker), and modify it so that it can also load and save ROIs. The idea is to show segmentations and allow them to be edited and saved. How exactly should I go about doing this? How are the tools called/accessed by OHIFViewer? Where should I put a custom version of this tool in my project?

Many thanks

**Comment by liuchen1393193701** [comment]
already realize?

**Comment by liuchen1393193701** [comment]
can you give me share

**Comment by dannyrb** [comment]
@henryhe1, I believe limited support for this may now exist; however, @swederik would know better than I.

We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

For what it's worth, we're trying to do a better job at tracking feature requests, building scope/requirements for items we would accept PRs for, and show which items we have planned for development in the near future. You can see our very early stage roadmap here: https://github.com/OHIF/Viewers/projects/3
