### ISSUE TITLE
yarn run dev and yan run orthanc up running properly, but still not able to access Viewer

### ISSUE THREAD

**Issue by sambid9988** [OHIF/Viewers#2304]
I am able to run yarn run orthanc:up and yarn run dev:orthanc, two commands are not showing any errors, but still am not able to view anything on port 3000 and 8042..i dont understand what i am missing now.I am running all this  on a aws linux VM.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by DragonnZhang** [comment]
I have the same problem on mac.

**Comment by losefor** [comment]
same problem on mac M2 Pro

**Comment by sedghi** [comment]
Can you add reproducible steps?

**Comment by sedghi** [comment]
can you re-try with latest master branch, or release branch and if this still happening open the issue please
