### ISSUE TITLE
Segmentation metadata corruption

### ISSUE THREAD

**Issue by vsaase** [OHIF/Viewers#2309]
Here https://github.com/OHIF/Viewers/blob/360616be138d1943848671c298dadc15b6ab01ff/extensions/dicom-segmentation/src/getOHIFDicomSegSopClassHandler.js#L96 it is assumed that dcmjs returns the segmentation metadata array, but as can be seen here https://github.com/dcmjs-org/dcmjs/blob/390c0a17ea7bf7539abe64c183aa87e268f9e11b/src/adapters/Cornerstone/Segmentation_4X.js#L1386 is is actually an object containing also the SeriesInstanceUID.
This leads to wrong metadata saved in the labelmap by this call https://github.com/OHIF/Viewers/blob/360616be138d1943848671c298dadc15b6ab01ff/extensions/dicom-segmentation/src/loadSegmentation.js#L19

see also issue https://github.com/dcmjs-org/dcmjs/issues/192

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
