### ISSUE TITLE
Error / STOW SR Error while saving the measurements.

### ISSUE THREAD

**Issue by brikjr** [OHIF/Viewers#2317]
**My app have allot of errors 
- Not saving Measurements
- not export PDF**

**Comment by igoroctaviano** [comment]
@brikjr can you share more details on the issues you are facing? 

- which flow you are executing?
- which measurement you're trying to store? 
- what are the error messages?
- what is the error stack trace?

In order to help, the more specific you go the better. If we can't instantly fix the problem, we may give you directions on how to solve it so you can contribute to the solution.

**Comment by brikjr** [comment]
> @brikjr can you share more details on the issues you are facing?
> 
> * which flow you are executing?
> * which measurement you're trying to store?
> * what are the error messages?
> * what is the error stack trace?
> 
> In order to help, the more specific you go the better. If we can't instantly fix the problem, we may give you directions on how to solve it so you can contribute to the solution.

### **first thanks 4 ur response ,**

## version of 9/3/2021 
it have a ton of issues like

- `: Failed prop type: Invalid prop studies[0].displaySets[0].SeriesNumber of type string supplied to Viewer, expected number` supplied to StudyBrowser
- `Failed prop type: Invalid prop windowWidth of type string supplied to ViewportOverlay, expected number `

**also when use measurment tools like length or annotate  and save measurements don't save** 
![enter image description here](https://i.ibb.co/7VWZ4LG/Screenshot-311.png) 

My NodeJS version: 14lts , yarn 1.22
