### ISSUE TITLE
Problem loading image with last version OHIF (with react-cornerstone-viewport 4.0.5)

### ISSUE THREAD

**Issue by IMP360** [OHIF/Viewers#2319]
Hi,

I tried the new version. I produced my version like this:

yarn config set workspaces-experimental true
yarn install --force
yarn build

I run dist with apache (and rewrite mod) or nginx (same problem)

I kept server.dcmjs.org for test.

This screenshot show problem
![image](https://user-images.githubusercontent.com/5773662/111335782-f33b2500-8674-11eb-8861-92ffa68bbd03.png)

Thanks for help

**Comment by jonasscherer** [comment]
I have similar issues with TCIA data.

**Comment by ngutman** [comment]
I ran into the same issue.

It happens with some CT studies served from the latest version of DCM4CHE, when I tried using a different DCM4CHE server running an older version (5.22.4-secure) the same studies loaded just fine 😕

Will verify tomorrow but maybe something changed in the way DCM4CHE serves CT studies which breaks cornerstone.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
