### ISSUE TITLE
Storing measurements

### ISSUE THREAD

**Issue by MaksFasolka** [OHIF/Viewers#2322]
Hi guys
My question is related to storing measurements.
I use a 'length' measurement tool and then I click the "Save measurements" button.
After that I get a message that my measurements were saved successfully.
<img width="375" alt="Screenshot 2021-03-17 at 18 14 19" src="https://user-images.githubusercontent.com/48988115/111500368-99a62980-874c-11eb-92f3-625c978942f2.png">

But after reloading the page, all my measurements disappear.
Please tell me what to look for and what could be the problem
I would be grateful for any help

**Comment by brikjr** [comment]
After Save measurements go to studylist and press to this Study again , U should find your SR Report with Measurments

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
