### ISSUE TITLE
" setToolMode call for tool not available globally" error

### ISSUE THREAD

**Issue by mozzy11** [OHIF/Viewers#2328]
Am adding anew custom tool to OHIF through an extenstion.
This works fine in dev mode ,
but when i build the extention and embed it in a web page using the script tag , the tool icon appears on the ohif tool bar ,but when i click on the tool ,i get the above error
and then 
`Unable to find tool "save-Tool" for enabledElement`

here is the referenced source of the error from the browser console

```
 var globalTool = _index_js__WEBPACK_IMPORTED_MODULE_5__["default"].state.globalTools[toolName];

  if (!globalTool) {
    logger.warn("setToolMode call for tool not available globally: ".concat(toolName));
    return;
  }
```

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
