### ISSUE TITLE
choppy scrolling in 2D mode

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2334]
## Bug Report

@chafey pointed out that scrolling with slider or StackScroll tool is choppy on [IDC](https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.6279.6001.224985459390356936417021464571?seriesInstanceUID=1.2.276.0.7230010.3.1.3.0.57823.1553343864.578877,1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680).

### Describe the Bug

If you load the same dataset in the MPR view you can see how smooth it should be.

### What steps can we follow to reproduce the bug?

1. Visit the IDC link above
2. Drag the slider.  Lots of "Loading..." hangs but choppy even after loading is complete.  These two may be related

**Comment by swederik** [comment]
Pretty sure it's because of this stuff which should not exist:

https://github.com/OHIF/Viewers/blob/94a9067fe3d291d30e25a1bda5913511388edea2/extensions/cornerstone/src/index.js#L42

I had removed that stuff in a branch here which included another tool as an example, so maybe we can pull those changes back in

https://github.com/OHIF/Viewers/pull/2169
