### ISSUE TITLE
Why New version of OHIF don't have Generate report? 

### ISSUE THREAD

**Issue by briyk** [OHIF/Viewers#2337]
in version 1 of OHIF there was a Save Component which responsible for Generation PDF Reports so why in newer version i don't see it
![Version 1.0.0 Meteor](https://i.ibb.co/j3vb8Jr/LT-Rotate-Right.png)
and where can i download this version ?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
