### ISSUE TITLE
2D MPR button is not displayed if user clicks on Study List and selects the same Patient

### ISSUE THREAD

**Issue by Michael-Andersen** [OHIF/Viewers#2339]
### Describe the Bug

2D MPR button is not displayed when returning to a study you have previously clicked.

### What steps can we follow to reproduce the bug?

1. Click a study from studylist that should have 2D MPR option available.
2. Observe that there is a 2D MPR button in the Toolbar.
3. Go back to studylist.
4. Click on same study
5. See the 2D MPR button is missing

This issue was previously reported here as issue 1: https://github.com/OHIF/Viewers/issues/1326

This PR was supposed to fix the issue: https://github.com/OHIF/Viewers/pull/1360

I have found that removing the 

```
studyMetadataManager.purge();
```
 call entirely from [ViewerRetrieveStudyData.js](https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js#L399
)
fixes the issue but I'm not sure there's a more nuanced logic that should be used to call purge()

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
