### ISSUE TITLE
Serving dicom image database efficiently

### ISSUE THREAD

**Issue by henryhe1** [OHIF/Viewers#234]
I am running the OHIF Viewer meteor app from a remote machine running an Orthanc server. I imported all our exams (54GB) into a persistent database but it makes loading the study list and images very slow (10-15 seconds). Is there a more efficient way to do this? 

Previously we stored only the paths to the exams in a postgresSQL database, should we think about reverting to that instead of Orthanc?

**Comment by swederik** [comment]
Historically, Orthanc has had poor performance when you used the DICOMWeb plugin rather than their own API endpoints. I haven't tested it recently, but I know they were working on that. There may also be issues on our end with the SearchForStudies call, but I don't know of anything in particular.

You can try using [Orthanc with DIMSE](https://github.com/OHIF/Viewers/wiki/Orthanc-with-DIMSE) instead, and only retrieve image data over WADO-URI.

You can also try DICOMCloud (https://dicomcloud.azurewebsites.net/) or dcm4chee (https://github.com/dcm4che/dcm4chee-arc-light/wiki/Running-on-Docker).

I've been doing most of my testing with dcm4chee via Docker lately. It's not lightweight, but it's a solid system.

**Comment by henryhe1** [comment]
I want to clarify that the longest lag (~30s) is actually when loading the study list. From the console, it seems like it's stuck at the `search()` function in studylistResult.js for 30 seconds, until finally displaying `StudyListSearch`. 

1. So I added Orthanc with DIMSE, and it loads much faster! (<2 s). Is there a way to set it to DIMSE as default? Currently the user still has to go to "Server Information" and check the DIMSE option. 

2. From the terminal, when I make the switch to the "DIMSE Server" I get this error: 

```

I20180725-10:19:57.898(-4)? Adding DIMSE peers
I20180725-10:19:57.900(-4)? server error { Error: listen EADDRINUSE 0.0.0.0:11112
I20180725-10:19:57.900(-4)?     at Object._errnoException (util.js:992:11)
I20180725-10:19:57.901(-4)?     at _exceptionWithHostPort (util.js:1014:20)
I20180725-10:19:57.901(-4)?     at Server.setupListenHandle [as _listen2] (net.js:1355:14)
I20180725-10:19:57.901(-4)?     at listenInCluster (net.js:1396:12)
I20180725-10:19:57.901(-4)?     at doListen (net.js:1505:7)
I20180725-10:19:57.902(-4)?     at _combinedTickCallback (internal/process/next_tick.js:141:11)
I20180725-10:19:57.902(-4)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
I20180725-10:19:57.902(-4)?   code: 'EADDRINUSE',
I20180725-10:19:57.903(-4)?   errno: 'EADDRINUSE',
I20180725-10:19:57.903(-4)?   syscall: 'listen',
I20180725-10:19:57.903(-4)?   address: '0.0.0.0',
I20180725-10:19:57.903(-4)?   port: 11112 }

```
Are those peers required? What is a peer?

Thank you

**Comment by davidi1** [comment]
@henryhe1 Are you using the Docker image of OHIF Viewer? I found that to be a lot easier to get setup and its been running great for me and the clinic I work at. It loads fairly fast and the study list used to take forever to load but once the devs made it so the study list only loads today's patients, its MUCH faster. I am using Orthanc as well and our Orthanc database is a decent size.

**Comment by henryhe1** [comment]
Yes I am. Orthanc with DIMSE made the study list load much faster, hopefully Orthanc with DICOMWeb will be fixed in the future
