### ISSUE TITLE
ohif annotation delay

### ISSUE THREAD

**Issue by nithin-samudrala** [OHIF/Viewers#2340]
I am facing a strange issue. When I load a mammography study on viewer.ohif.org and use the annotation tools, it works perfectly. But, when I clone the GitHub repo and build it using yarn, UI lags while marking the annotations( I tried Freehand, length tool, rectangle tool). Is there any solution for this

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
