### ISSUE TITLE
Failure to load segmentation

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2345]
![image](https://user-images.githubusercontent.com/313942/113339455-78227180-92f8-11eb-9b23-10661c1d5c30.png)

```
Enter the description of your problem here: 


============= SESSION INFO =============

== App ==
version	4.9.8

== Extensions Versions ==
generic-viewer-commands	4.9.8
cornerstone	2.10.6
vtk	1.11.4
html	1.3.4
microscopy	0.52.0
pdf	1.0.6
com.ohif.dicom-segmentation	0.6.2
rt	0.6.7
dicom-p10-downloader	0.2.1
dicom-tag-browser	undefined

== Browser Info ==
name	 chrome
os	 Mac OS
type	 browser
version	 89.0.4389

== URL ==
URL	 https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc/dicomStores/v2/study/1.3.6.1.4.1.14519.5.2.1.7311.5101.758555921127856064761732086690

== Viewport Layout ==
Rows	1
Columns	1

== Viewports ==
[0,0]	1.3.6.1.4.1.14519.5.2.1.7311.5101.165636727522505811947315188478

```

Both of the segmentations in question load fine in Slicer:

![image](https://user-images.githubusercontent.com/313942/113339540-9be5b780-92f8-11eb-8188-c643f8f14490.png)

![image](https://user-images.githubusercontent.com/313942/113339569-a7d17980-92f8-11eb-9c66-84a9bb5bb6b9.png)

**Comment by Punzo** [comment]
Hi @fedorov I checked the data.

the segmentation with 4 segments gets laoded with no problem (second segementation in the seg UI combobox).

The segmentation with only 1 segments I would say that it is not completely clean, if you navigate the DICOM in the Tag Browser you can see that:

1. PerFrameFunctionalGroupsSequence is an array of 116 elements instead of 21 (the data have 21 frames and the segmentation has only 1 segment). 
2. Of the 116 elements only 21 have the DerivationImageSequence information (which we use to load the segmentation in the array buffer). 
3. So if I ignore the 95 elements with missing informations (which I guess they should simply not exist, see fix in dcmjs https://github.com/dcmjs-org/dcmjs/pull/198), the segmentation loads wrongly because the Columns and Rows dicom attribute are wrong (320x320 instead of 384x384).

See image: 
![image](https://user-images.githubusercontent.com/7985338/114554835-6aa9a780-9c67-11eb-9cb7-bd2a4692fb5b.png)

**Comment by fedorov** [comment]
Thank you Davide. Let me investigate, and let's hold https://github.com/dcmjs-org/dcmjs/pull/198 for now.

**Comment by Punzo** [comment]
ok perfect, in the case you will confirm the original data are correct, we would have to check at which step the DICOM attributes get corrupted.

**Comment by fedorov** [comment]
This segmentation is very different from any other samples we've had so far, but, I think, is completely fine. It just exposed certain incorrect assumptions in the implementation.

The way this segmentation was created is discussed here: https://wiki.cancerimagingarchive.net/display/DOI/High+Resolution+Prostate+Segmentations+for+the+ProstateX-Challenge.

> The high resolution segmentations were obtained by considering the three scan directions: for each scan direction (axial, sagittal, coronal), the gland was manually delineated by a medical student, followed by a review and corrections of an expert urologist. These three anisotropic segmentations were fused to one isotropic segmentation by means of shape-based interpolation in the following manner: (1) The signed distance transformation of the three segmentations is computed. (2) The anisotropic distance volumes are transformed into an isotropic high-resolution representation with linear interpolation. (3) By averaging the distances, smoothing and thresholding them at zero, we obtained the fused segmentation. 

So the geometry of the segmentation image frames is not the same as the geometry of the referenced instances in `DerivationImageSequence`, and to my knowledge, there is nothing in the standard that requires that.

Segmentation series correctly lists 116 frames, and 320x320 resolution. It does reference individual MR instances for some of the segmentation frames as "Source image for image processing operation". I don't think there is anything wrong with that, since the geometry of each frame is fully defined by the content of Shared/PerFrame FGs.

I think implementation should never rely on the referenced images to get the geometry **unless** that is the only means to get the geometry. In this situation, it is not:

![image](https://user-images.githubusercontent.com/313942/114615885-35578680-9c74-11eb-83dd-db6630512e66.png)

![image](https://user-images.githubusercontent.com/313942/114615949-47d1c000-9c74-11eb-979f-1d3715db33ef.png)

It is a separate question if OHIF can support at all rendering of the segmentation that has geometry different from the geometry of the image it references. If this is not possible due to the limitations of the implementation, it should probably be tagged with a warning sign. Ideally, it would be great if OHIF could overlay any segmentation over any image, as long as their FrameOfReferenceUID is the same. The reason it works in Slicer is because Slicer reconstructs segmentation geometry from the shared/per-frame FG content.

**Comment by pieper** [comment]
This kind of data should be handled fine by the MPR mode (vtkjs-based) but we said we would not go back and retrofit cornerstone to support out-of-plane segmentation so we should just detect it and give the user a warning for now.  Something like "The segmentation is not in the image plane.  Please use MPR mode to visualize it.".

I can confirm that the rendering works in MPR mode, but there's a problem with the crosshair, which we should probably file as another issue.

![image](https://user-images.githubusercontent.com/126077/114626046-27f4c900-9c81-11eb-9631-9401c8af7b48.png)

**Comment by Punzo** [comment]
ah I missed that 95 frames were out of plane respect to the source frame of the datasets (I should have looked at the image patient position attributes and realize it form there...). It is indeed true that in Slicer the segmentation geometry is indipendent from anything else (Slicer actually also optimizes the ram consumption creating array buffer smallest as possible). 

Two main limitations are generated by the current cornerstone approach (segmentation geometry has to fit the one of the source images):
1) we can't have out of plane frames;
2) we can't have segmentation frames with different Columns and Rows attributes respect to the source frames.

I agree, these are limitating and we should think in long term how to update cornerstone to fix (1) and (2) (@dannyrb, @JamesAPetts do you have any feedback? e.g. were there any particular reasons for the design of the current cornerstone/dcmjs segmentation loading/handling?). 

@pieper unfortunately, if a segmetation gets loaded wrongly in cornerstone, it will be loaded wrongly also in vtk MPR mode, since at the moment the infrastructure pass to vtk the array buffer stored in cornerstone. (the segmentation that you are visualizating in the screenshot is the "second" one, which has the same geometry of the source frames and it has no problem in cornerstone too). 

On the short term we could:
A) ignore the out of plane frames (i.e., https://github.com/dcmjs-org/dcmjs/pull/198) and fire a warning in dcmjs;
B) ignore seg frames that have different Columns and Rows attributes respect to the source frames and fire a warning in dcmjs;
C) if the segmentation after these two checks has no "compatible" frames, fire an error in dcmjs and do not load the segmentation.

Please also remind that at the moment the OIHF viewer UI notifications and logger, pop-ups only the errors from third libraries and not the warnings (this should go in another ticket).

@pieper @fedorov I will wait your feedback, before delving deeper into this ticket.

**Comment by pieper** [comment]
Okay, yes, I recall now that the vtk MPR code is getting the volume data from the 2D cornerstone code - this has cropped up before.  Thanks for the reminder @Punzo 👍 

Since OHIF is moving toward unifying 2D and 3D approaches I would not want to invest a lot of work in handling this case for the current viewer code and instead just detect it and say it's not supported for now.  Better to invest our effort into developing and adopting a more unified solution.  This is something we should discuss in the context of briefing everyone on the state of other developments going on in the OHIF community to avoid divergent work.

**Comment by fedorov** [comment]
>  I would not want to invest a lot of work in handling this case for the current viewer code and instead just detect it and say it's not supported for now.

👍

**Comment by Punzo** [comment]
> Okay, yes, I recall now that the vtk MPR code is getting the volume data from the 2D cornerstone code - this has cropped up before. Thanks for the reminder @Punzo 
> 
> Since OHIF is moving toward unifying 2D and 3D approaches I would not want to invest a lot of work in handling this case for the current viewer code and instead just detect it and say it's not supported for now. Better to invest our effort into developing and adopting a more unified solution. This is something we should discuss in the context of briefing everyone on the state of other developments going on in the OHIF community to avoid divergent work.

ok perfect, then I would just detect it in dcmjs when is loading and fire an error.

**Comment by Punzo** [comment]
PR https://github.com/dcmjs-org/dcmjs/pull/198 updated with checks to detect difference of geometries between seg and source data and throw errors not supported for now.

**Comment by fedorov** [comment]
> and throw errors not supported for now

I have not seen what the above actually means, but what do you think about adding the icon as in the other situations identified with series tagging problematic SEGs, and providing details in a tooltip? I think this would be more helpful.

![image](https://user-images.githubusercontent.com/313942/114733322-3ab6de80-9d11-11eb-8563-34180d5d15cc.png)

**Comment by Punzo** [comment]
the problem is that the loading is done in dcmjs. So it is natural to implement the checks there while loading the SEGs (and in case aborting it and avoid memory consumption). We could write informating regarding the SEG loading issues in the dcmjs errors and update the OIHF UI similar to the Logger service. @igoroctaviano do you have any feedback on an eventual implementation?

**Comment by fedorov** [comment]
Thanks Davide. I would like to better understand the flow. When this error occurs, does it mean the affected SEG won't show in the list on the left at all?

**Comment by Punzo** [comment]
with PR https://github.com/dcmjs-org/dcmjs/pull/198, I fire an error in dcmjs, for which OIHF will show a pop-ups notification as
![image](https://user-images.githubusercontent.com/7985338/114734895-f3e2dc00-9d44-11eb-89d7-68f1850d5dd4.png)

but yes the segmentation will still show in the left column:
![image](https://user-images.githubusercontent.com/7985338/114734996-0fe67d80-9d45-11eb-8f7a-39c343a0b376.png)

**Comment by fedorov** [comment]
I am fine with any way that is most expedient, we don't need to dwell on this, but I find this approach to be misleading. I do not like this inconsistency in flagging problematic series in UI, but I also don't know the implementation to appreciate the challenges in implementing more uniform user experience, so it's your call in the end.

**Comment by Punzo** [comment]
> I am fine with any way that is most expedient, we don't need to dwell on this, but I find this approach to be misleading. I do not like this inconsistency in flagging problematic series in UI, but I also don't know the implementation to appreciate the challenges in implementing more uniform user experience, so it's your call in the end.

ok, I will get Igor feedback on the UI. Shall I put https://github.com/dcmjs-org/dcmjs/pull/198 in hold until we have a clear way to notify series issues to the users trough the UI?

**Comment by fedorov** [comment]
Yes, we don't need to rush with this. Let's wait to hear from Igor first.

**Comment by igoroctaviano** [comment]
> Yes, we don't need to rush with this. Let's wait to hear from Igor first.

Just had a chat with @Punzo in Slack, we came to an agreement on the approach. 👍

**Comment by Punzo** [comment]
> > Yes, we don't need to rush with this. Let's wait to hear from Igor first.
> 
> Just had a chat with @Punzo in Slack, we came to an agreement on the approach.

Done in https://github.com/OHIF/Viewers/pull/2364.

**Comment by fedorov** [comment]
Hey guys, could you check this study: 1.3.6.1.4.1.14519.5.2.1.3671.4754.121472087445374646718121301133?

It does not load SEGs with the error below in the sandbox, and I don't think they are orthogonal. Does it work in the version you are developing?

![image](https://user-images.githubusercontent.com/313942/115130706-b8a01180-9fbf-11eb-9e17-b4990342cf66.png)

**Comment by Punzo** [comment]
@fedorov this one was a tollerance issue (dcmjs was using 1.e-5 which was too stringent for this case). I added an option to set the tollerance in dcmjs and set as defualt 1.e-3. See PR: https://github.com/dcmjs-org/dcmjs/pull/200.

**Comment by fedorov** [comment]
IMHO, works as intended.
