### ISSUE TITLE
CINE ultrasound not playing the frames

### ISSUE THREAD

**Issue by ambawaleankita** [OHIF/Viewers#2383]
Hi Guys,

I'm using OHIF viewer and it's working very nicely.  The issue is when I'm trying to load the ultrasound image via JSON file. The viewer is loading a single image. There are 110 frames in the ultrasound image but the frames not playing in cine. 

Attaching the image for your reference,
The first part displays the number of frames (The image is properly displayed with the Cornerstone library. In cornerstone, only one image is loaded but it shows 110 frames in the description. [It has been tested here](https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html
) ) & In the second part as you can see only one image is loaded.

![image](https://user-images.githubusercontent.com/21143159/116061262-4a82db00-a6a0-11eb-9f25-60f62788af91.png)

Note- In JSON format there's only one object in instances array that points to single Dicom file with 110 frames.
**Exected output**:  Viewer should recognize the ultrasound image and run the frames in the loop.
Any help would be greatly appreciated.

**Comment by olivert1969** [comment]
@ambawaleankita - what happens when trying the Cine control toolbar?

**Comment by ambawaleankita** [comment]
@olivert1969 Nothing happens just single frame is shown.

**Comment by ranasrule** [comment]
same issue here

**Comment by Mamta92** [comment]
Any updates on the above issue? Not able to play/scroll multiframe images on OHIF.

**Comment by olivert1969** [comment]
have you tried the original Meteor v1 version?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
