### ISSUE TITLE
DisplaySets are lost in metadata on page navigation to studylist and back

### ISSUE THREAD

**Issue by vsaase** [OHIF/Viewers#2387]
Hi,

I noticed that when I have a study open, the study metadata as provided by the MetadataManager contains the displaySets of that study. On going back to the study list and forward to the study again, this is not the case anymore.

As a hack I added this to ViewerMain.js in ComponentDidUpdate, but maybe someone knows where the correct place is to ensure consistent metadata?

```
this.props.studies.map(study => {
        const studyMetadata = studyMetadataManager.get(study.StudyInstanceUID);
        if (studyMetadata._displaySets.length == 0) {
          study.displaySets.map(displaySet =>
            studyMetadata.addDisplaySet(displaySet)
          );
        }
      });
```

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
