### ISSUE TITLE
When Click "2D MPR", the web view show message error

### ISSUE THREAD

**Issue by thanhtd1012** [OHIF/Viewers#2422]
Hi @ALL !

Describe the bug:
When Click "2D MPR", the web view show message error:
![image](https://user-images.githubusercontent.com/70577879/119803751-ed31b200-bf09-11eb-8da7-846443b8b1b2.png)

My pc env : view version & PC details
![image](https://user-images.githubusercontent.com/70577879/119803947-1c482380-bf0a-11eb-84c8-1aebd7c11b20.png)

I also try doing the issue #2400. It is NOT worked.

Please check and help me!
Thanks guys!

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
