### ISSUE TITLE
Trouble in loading data from local Orthanc server

### ISSUE THREAD

**Issue by ragu1257** [OHIF/Viewers#2425]
I want to get the data from my local Orthanc server but getting a proxy error:

![image](https://user-images.githubusercontent.com/38836613/119958086-fc187300-bfa2-11eb-9320-11f661c9526d.png)

My default.js file looks like this:

![image](https://user-images.githubusercontent.com/38836613/119958320-38e46a00-bfa3-11eb-9029-287603509155.png)

I am using Nginx to proxy-pass the Orthanc-server:

![image](https://user-images.githubusercontent.com/38836613/119958622-806af600-bfa3-11eb-9895-b41536cae44c.png)

When I am going to this url http://localhost/orthanc/dicom-web/studies I am able to see an array object of studies.

While searching for my problem, I saw a solution to make a change in orthanc.json file for DicomWeb, so I also updated my orthanc.json file:

![image](https://user-images.githubusercontent.com/38836613/119959911-b78dd700-bfa4-11eb-98c8-3d8e48e3b17e.png)

I am not sure where am I going wrong. 
When I am running the project with yarn run dev:orthanc, it is working fine.
Can you please suggest me correct way of rendering the data from my local Orthanc server?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
