### ISSUE TITLE
Problem viewer displaying US modality

### ISSUE THREAD

**Issue by sylvainb31** [OHIF/Viewers#2426]
Version : "@ohif/viewer@4.5.28"

Problem : 

I am using the ohif viewer to display images for several hospitals.
There is one hospital in which the ultrasound images (US modality) don't display correctly in the ohif viewer. I have tried changing the transfer syntax of the images but it still doesn't work.

Here is the display of the ultrasound :

![image](https://user-images.githubusercontent.com/37896804/120010298-44548700-bfdd-11eb-8d11-604013698b1d.png)

When trying to display an other ultrasound for an other hospital, it displays correctly :

![image](https://user-images.githubusercontent.com/37896804/120010525-88e02280-bfdd-11eb-8ea3-5cdef33ceaa3.png)

I thought the problem came from the images .dcm, but I tried displaying them on a viewer online and it displays correctly : 

![image](https://user-images.githubusercontent.com/37896804/120010814-e07e8e00-bfdd-11eb-9c3b-3d86abaafc19.png)

I've tried comparing the dataset of .dcm of both exams, but I can't find what's causing this.

Here is the result of the study query of the viewer for the ultrasound not displaying correctly :
studies/1.2.826.0.1.3680043.8.1275.9882141517/series
[metadatastudy.txt](https://github.com/OHIF/Viewers/files/6562064/metadatastudy.txt)

Here is the result of the series query of the viewer for the ultrasound not displaying correctly :
studies/1.2.826.0.1.3680043.8.1275.9882141517/series/1.2.410.200001.1.11801.447477310.2.20210427.1134649616.946.1/metadata
[metadataserie.txt](https://github.com/OHIF/Viewers/files/6562066/metadataserie.txt)

Here is the dataset of one of the image of the ultrasound not displaying correctly :
[Ultrasound dataset not displaying correctly.xlsx](https://github.com/OHIF/Viewers/files/6562008/Ultrasound.dataset.not.displaying.correctly.xlsx)

Here is the result of the study query of the viewer for the ultrasound displaying correctly :
studies/1.2.250.1.59.0.999.20210526.2117302/series
[metadatastudy.txt](https://github.com/OHIF/Viewers/files/6562136/metadatastudy.txt)

Here is the result of the series query of the viewer for the ultrasound not displaying correctly :
studies/1.2.250.1.59.0.999.20210526.2117302/series/1.2.840.113619.2.481.84108090782.1622017378.387/metadata
[metadataserie.txt](https://github.com/OHIF/Viewers/files/6562140/metadataserie.txt)

Here is the dataset of one of the image of the ultrasound displaying correctly :
[Other ultrasound dataset displaying correctly.xlsx](https://github.com/OHIF/Viewers/files/6562043/Other.ultrasound.dataset.displaying.correctly.xlsx)

I am displaying the image using the wadouri mode :

```
window.OHIFViewer.installViewer(
            {
                routerBasename: '/Home/Viewer',
                extensions: [], /* https://github.com/OHIF/Viewers/issues/1722 commentaire pour inclure extensions :  https://github.com/OHIF/Viewers/issues/1003#issuecomment-539190501 */
                showStudyList: true,
                filterQueryParam: false,
                maxConcurrentMetadataRequests: 2,
                servers: {
                    dicomWeb: [
                        {
                            name: 'DCM4CHEE',
                            wadoUriRoot: '/api/WadoUriAPI', /* https://dicomcloud.azurewebsites.net/api https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado /api/WadoUriAPI  /api/WadoUriAPI/getImageDicom */
                            qidoRoot: '/api/WadoQidoAPI', /* https://dicomcloud.azurewebsites.net/api https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs /api/WadoQidoAPI */
                            wadoRoot: '/api/WadoQidoAPI', /* https://dicomcloud.azurewebsites.net/api https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs /api/WadoQidoAPI */
                            qidoSupportsIncludeField: true, /* a vérifier l'utilité de la propriété */
                            imageRendering: '@(Model.WadoRsOuWadoUri)', /* wadors / wadouri voir : https://github.com/OHIF/Viewers/issues/1338 et https://github.com/OHIF/Viewers/issues/482 */
                            thumbnailRendering: '@(Model.WadoRsOuWadoUri)', /* wadors / wadouri */
                            enableStudyLazyLoad: true, /* a vérifier l'utilité de la propriété : https://github.com/OHIF/Viewers/pull/953 */
                        },
                    ],
                }
            },
            containerId,
            componentRenderedOrUpdatedCallback
        );
```

I've been at it for several days now, but I can't seem to find what's causing the problem.
Why is it working on an other viewer but not with the ohif viewer ?
Is there a dicom tag missing for the problematic ultrasound ?

If anyone can help me that would be much appreciated, thanks a lot :)

**Comment by sylvainb31** [comment]
@dannyrb @swederik any ideas guys ?

**Comment by jeffer1312** [comment]
same problem here
![image](https://user-images.githubusercontent.com/44037843/127146628-a3319c9a-f58c-4b85-b4eb-de280fee4e08.png)

**Comment by pilacoepouco** [comment]
Solution to my problem, maybe it's the same as yours @jeffer1312 

https://github.com/OHIF/Viewers/issues/2420#issuecomment-892141342

**Comment by jeffer1312** [comment]
we were able to solve by removing this code
```
cornerstone.metaData.addProvider(
     metadataProvider.get.bind(metadataProvider),
     9999
   ).
```   
   which is located in the file '\extensions\cornerstone\src\init.js'.

for us it worked correctly after removing it, but we don't know exactly what this part did, if anyone can help us understand.

**Comment by PoyangLiu** [comment]
The documentation of `metadataProvider` is in [cornerstone documentation](https://docs.cornerstonejs.org/concepts/metadata-providers.html) and its [api documentation](https://docs.cornerstonejs.org/api.html#addprovider).

Basically, it's a way to register your own (and cornerstone or OHIF) `metadataProvider` that provides a common API for retrieving DICOM tags from an instance.  

Multiple providers can be registered.  The one with higher priority will be tried first.  If the `metadata.get(...)` found a provider that returns something, then it will stop and won't try the lower priority provider.  By removing this line, you are basically forcing the application to skip this provider and continue to the next provider.

For example.  Let's say the application calls `cornerstone.metaData.get('imagePlaneModule', 'ct://1');`.  It will first try providerA.   Let's say it returns the following:
```
{
            columns: 512
}
```
It will then stop.  

If you remove the line in your previous comment, then the next provider will be tried.  Let's say there is a providerB that returns
```
{
   columns: 512,
   rows: 512
}
```
you see how the first provider is missing the property `rows`?

It is possible that the provider you removed is missing a property that you need in order to render the image properly.  But the next provider somehow does provides it.  You'll have to debug to find out what the important missing tag is.

Once you found out what the missing tag is, you can write your own provider, and call `addProvider(yourOwnProvider, priorityHIgherThan9999)`.  This way you'll retain full control of the DICOM tags that returns from `metadaProvider` API.

I hope this helps.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
