### ISSUE TITLE
Keycloak with recent version of ohif-viewer and dcm4che-secured

### ISSUE THREAD

**Issue by hawodi** [OHIF/Viewers#2429]
I have followed the integration tutorials with dcm4chee-arc-secured and had a problem with the login. Is there an updated compose file for the version branch since the ver 1 is no longer actively been work on.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by sedghi** [comment]
We recently added several recipes for implementing authentication with Keycloak in OHIF. You can find them here:

https://docs.ohif.org/deployment/user-account-control
