### ISSUE TITLE
wado?dicom-web?

### ISSUE THREAD

**Issue by leonopteryx130** [OHIF/Viewers#2461]
**Description**

i have two patients' data from different CT machine
![image](https://user-images.githubusercontent.com/69339697/124051207-a118e680-da4e-11eb-8d82-19bff63378f3.png)
the second one can read but the first can't
the two patients' image urls are different
 
![image](https://user-images.githubusercontent.com/69339697/124051371-f7862500-da4e-11eb-8435-7c18142d6ad6.png)
![image](https://user-images.githubusercontent.com/69339697/124051400-08369b00-da4f-11eb-9c29-b155c0ccf252.png)

here is my configuration of dicomWeb:

dicomWeb: [
      {
        name: 'Orthanc',
        wadoUriRoot: 'https://localhost/wado',
        qidoRoot: 'https://localhost/dicom-web',
        wadoRoot: 'https://localhost/dicom-web',
        qidoSupportsIncludeField: false,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        requestionOptions: {
          auth: "orthanc:orthanc",
        },
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],

how to resolve this problem

**Comment by andresmmujica** [comment]
you need to solve the cors issue adding an nginx before reaching the failing machine will do the trick.  see here

https://github.com/OHIF/Viewers/issues/2455#issuecomment-884987404

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
