### ISSUE TITLE
Tag browser shows InvalidDate for all series except the first series of a Study 

### ISSUE THREAD

**Issue by Christian-e-S** [OHIF/Viewers#2475]
### Describe the Bug
In the Tag browser, only the first series shows a valid date. All other series show invalid date.

![image](https://user-images.githubusercontent.com/59229557/126044201-828324be-1ccb-42df-95ca-def857dfd736.png)

_A clear and concise description of what the bug is._

### What steps can we follow to reproduce the bug?

1. use latest master branch
2. enable tag browser
3. start with standard configuration (yarn run dev)
4. select first study
5. open tag browser

## My observations

The metadata for the series is first populated with the results of the following http request:
https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339/series

The result from this request does not include SeriesDate and SeriesTime.

The function makeSOPInstance defined in StudyInstanceHelpers.js would create series including the date and time, but only for series that are not present in the current study object. Since the series are already present (but without the seriesDate and time), the values are not set correctly.

I will propose a pull request, and link it here

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
