### ISSUE TITLE
What is the current stable version?

### ISSUE THREAD

**Issue by guoquan** [OHIF/Viewers#2488]
Hi,

I am looking for the correct version to work with.
Reading the [docs](https://docs.ohif.org/) I understand that it is featuring v2 (react) and v1(meteor) is out of support.

But I find in [release](https://github.com/OHIF/Viewers/releases), [tags](https://github.com/OHIF/Viewers/tags), on [npm](https://www.npmjs.com/package/@ohif/viewer), [docker hub](https://hub.docker.com/r/ohif/viewer/tags), and the latest is v4.9.21!
I even found [v5.0.0-v2](https://github.com/OHIF/Viewers/tree/v5.0.0-v2-sprint-1) in tags which I believe is a draft version.

Also, I never find any hint about v4/v5 in any docs. I also look at some random branches to find updates in the docs and, OOH you say you have V3 on a [v2 tmp branch](https://github.com/OHIF/Viewers/tree/docs/v2-main-tmp/docs/latest)?! Cheering, but where is V3?

Now I got confused about v1/v2 and v3/v4/v5. 
Most of the recent commits and docs are aiming v2 while there are v3/v4/v5. 
I might miss the component described by the version numbers. Maybe v2 for core and v4.9 for viewer app. Please correct me if that is the case.

And, if I clone from the master branch, what is the version I got?

Thanks!

**Comment by PoyangLiu** [comment]
@swederik, thank you for the explanation.  I've been seeing a lot of documentation update on v3 (feat/v2-main) recently.  Are there any about the difference between v2 to v3 and the migration path?

**Comment by swederik** [comment]
Not a ton yet, but it's coming soon and it's one of our top priorities. The v3 stuff is being published to https://ohif-platform-docs.netlify.app/next/ and https://ohif-platform-viewer.netlify.app/ at the moment. It still misses some features that v2 has (notably, MPR and DICOM Seg), but that's because we have other plans for those.

**Comment by guoquan** [comment]
@swederik Thanks for the explanation. Totally understand the difficulty when it comes to versioning.

What about the planned upgrading to v3? Found the gap analysis and there are some features we really missed, especially the 3D things (VTK and MIP/MPR layout). Is it soon, or something promising, but should be expected after a year?
I don't mean urging, 😃 just spying on OHIF's plan and that should help my decision.

**Comment by danihodovic** [comment]
Is https://github.com/OHIF/Viewers/tree/v3/storybook yet another branch / version that's worked on? Is there any timeline for consolidating the different versions?

**Comment by swederik** [comment]
> @swederik Thanks for the explanation. Totally understand the difficulty when it comes to versioning.
> 
> What about the planned upgrading to v3? Found the gap analysis and there are some features we really missed, especially the 3D things (VTK and MIP/MPR layout). Is it soon, or something promising, but should be expected after a year?
> I don't mean urging, 😃 just spying on OHIF's plan and that should help my decision.

Yes there is an upcoming replacement for the current approach to 3D support (via https://github.com/OHIF/react-vtkjs-viewport) that should make everything 3D a lot easier for the future. We plan to integrate it into OHIF v3 soon.

> Is https://github.com/OHIF/Viewers/tree/v3/storybook yet another branch / version that's actively worked on? Is there any timeline for consolidating the different versions?

We are planning to stop embedding UI components inside the new docusaurus site because some of the styles break, and instead to just host a Storybook (https://storybook.js.org/) site for the UI components instead. That branch is just a testbed for that.

**Comment by shivasuri** [comment]
Is there any plan to update the base styling of v3? imo v2 looks a bit more professional/cleaner stylistically (colors and edges) than v3. Although I understand that TailwindCSS provides more customizability on the design to those who extend OHIF.

It also seems like there are a few features v2 has over v3 such as the series information overlays on images as well as multiple tools. Were some of these intentionally left behind, and what is the timeline/plan to supply the toolbar? Is there a public doc or kanban somewhere describing the process of closing all the gaps? Thanks!

**Comment by swederik** [comment]
> series information overlays on images

This information is usually displayed in DICOM viewers but I think it's not strictly necessary. From our discussions with users, it seems that most of the time they are just ignoring this information and it's just visual clutter. Some other imaging applications have also removed / reduced the amount of information in the panels at any given time (https://arterys.com/ as an example), so I don't think this is really an issue. If you want to have it for your application, you can copy the overlay component into a new extension and replace the viewport.

> to supply the toolbar

I'm not sure I understand this question? Which toolbar? (Maybe a screenshot would help)

> update the base styling of v3?

We will be evolving it as we move forward, but we won't be changing it back to look like v2. If you like how v2 looks, you can probably adapt the CSS or set some tailwind variables to make it closer to that style, but that's not on our roadmap. If you have specific issues with it, or think some aspects need polishing / cleanup we'd be happy to hear about them though.

I think we will make a public Github Project soon with a set of issues for achieving feature parity between v3 and v2. We need that so we know when we think it's okay to replace the master branch with v3. We don't want to do that now because some people will lose features they may be using now (e.g. DICOM Seg, RT Struct).

**Comment by danihodovic** [comment]
Could you release feat/v2-main versions to npm? Currently we're building and re-publishing feat/v2-main under our own organization, but in order to stay in sync with the upstream it would be preferable if we could install it from the source project.

**Comment by anujramsoft** [comment]
> > @swederik Thanks for the explanation. Totally understand the difficulty when it comes to versioning.
> > What about the planned upgrading to v3? Found the gap analysis and there are some features we really missed, especially the 3D things (VTK and MIP/MPR layout). Is it soon, or something promising, but should be expected after a year?
> > I don't mean urging, 😃 just spying on OHIF's plan and that should help my decision.
> 
> Yes there is an upcoming replacement for the current approach to 3D support (via https://github.com/OHIF/react-vtkjs-viewport) that should make everything 3D a lot easier for the future. We plan to integrate it into OHIF v3 soon.
> 
> > Is https://github.com/OHIF/Viewers/tree/v3/storybook yet another branch / version that's actively worked on? Is there any timeline for consolidating the different versions?
> 
> We are planning to stop embedding UI components inside the new docusaurus site because some of the styles break, and instead to just host a Storybook (https://storybook.js.org/) site for the UI components instead. That branch is just a testbed for that.

Do we have any timeline for integration of 3D?

**Comment by Georift** [comment]
Hey @swederik thanks for the summary on the current state of the project. Would you accept a PR adding some of these details to the main README?

I'll look to raise a PR soon, has anything changed since your comment? Looks like the `v3` branch is now `v3-stable`?

**Comment by mbilalsh** [comment]
I need v1. or any possible way to connect the legacy pacs system that donot support DicomWeb with latest ohif v3-stable

**Comment by ahlaughland** [comment]
Congratulations on the release of ```master 3.7.0-beta.61```!

I've been developing on the ```v3-stable``` branch since 08/2022 and it looks like the ```master 3.7.0-beta.61``` is not included?

Will the ```v3-stable``` branch be merged in to ```master```? And if so when?

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
