### ISSUE TITLE
Can I use jpeg pictured instead of dicom files?

### ISSUE THREAD

**Issue by ShakhzodbekYuldoshov** [OHIF/Viewers#2495]
I want to use jpeg files instead of Dicom files. The reason for it is I converted Dicom to jpeg and edited using photoshop. Then converted jpeg to Dicom. But Dicom file did not change when I uploaded it to orthanc server again it did not recognized changes. For the reason of that I want to use jpeg reader instead of dicom servers. Is it possible? Please I need help. If you can please help me

**Comment by jensen0914** [comment]
This is not really an OHIF viewer issue or even an Orthanac server issue.

But did you replace the pixel data in the original DICOM file with your edited copy? If so, your server probably saw it as the same image and rejected it due to the same DICOM UIDs in the file. You should create a new DICOM file that has different UIDs so the server sees it as a different image object. There are plenty of JPEG to DICOM on the web that can do this for you.

**Comment by PoyangLiu** [comment]
There is a [`cornerstoneWebImageLoader`](https://github.com/cornerstonejs/cornerstoneWebImageLoader) in the cornerstonejs organization for exact that, loading png/jpg images.  You can read up on its documentation.

As of  how to get it to work in OHIF, you can search the usage of `cornerstoneWADOImageLoader` and probably replicate some of the initialization/configuration.

**Comment by papy-ganjha** [comment]
Hi everyone!
Did you managed to make it working? 
I'm interessed by doing the same thing for the viewer
Thanks for any response :smile:

**Comment by sedghi** [comment]
Cornerstone3D has webImageLoader but OHIF does not support that right now
