### ISSUE TITLE
How to integrate OHIF viewer with existing ZFP Viewer

### ISSUE THREAD

**Issue by rajashree-gh** [OHIF/Viewers#2508]
> :hand: How to integrate OHIF viewer with existing ZFP Viewer

**Description**

We have ZFP Viewer where the image has been displayed, assume Study Instace UID = "1234". Now on click some buttons in ZFP viewer, OHIF viewer will be started with the same study [Study Instace UID = "1234"]. How can I implement this? Please help.

Regards,

**Comment by jwitos** [comment]
I'm not familiar with the ZFP Viewer, but if you have Study Instance UID, you should be able to open it in OHIF viewer simply going to localhost:8080/viewer/<study_instance_uid>. The question is how do you implement a button in the ZFP viewer so that it can open a link to OHIF, but that I believe is something to discuss with ZFP Viewer developers.

**Comment by sedghi** [comment]
Regrettably, the mentioned feature is not supported at present and is not included in our current plans. However, we would be delighted to review your pull request if you would like to contribute.
