### ISSUE TITLE
Images are displayed in black in OHIF viewer 2.0. Unsupported orthanc versions

### ISSUE THREAD

**Issue by JorgeFragozo** [OHIF/Viewers#2513]
I am using the OHIF Viewer 2.0 and Orthanc 1.5.0 versions and the images are displayed correctly in the orthanc viewer, but in the OHIF viewer it is not displayed. The image is not displayed(Black screen) even when patient data and series information has been loaded successfully.

This is how the image is displayed in the orthanc viewer:
![image](https://user-images.githubusercontent.com/71538394/129236297-43684663-123f-417f-9700-53688491d750.png)

When opening the same study with the OHIF viewer it appears like this:
![image](https://user-images.githubusercontent.com/71538394/129237406-fde85b3a-b407-4f4e-96aa-2557993b34ea.png)

I decided to try version 1.5.0 of orthanc because with newer versions the images appears with some black stains. I share with you a very similar case published previously:
[https://github.com/OHIF/Viewers/issues/359](https://github.com/OHIF/Viewers/issues/359)

Using orthanc version 1.9.6 and the OHIF viewer 2.0, the image is displayed with black spots as can be seen below:
![image](https://user-images.githubusercontent.com/71538394/129431627-99fae5e0-eae1-47de-8001-d94bb981d528.png)

I could notice that this does not happen when I project the image in another viewer with the same version 1.9.6 of orthanc:
![osimis1](https://user-images.githubusercontent.com/71538394/129431415-e4e90e61-9da3-4844-9435-ab3f75f08fcc.png)

I am attaching dicom image used earlier in the examples, so that you can replicate the bug and help me find a solution.
[https://drive.google.com/file/d/1iwYRPDkUlZ53mPo5VtxXNu6pZ7RB_N9S/view?usp=sharing](https://drive.google.com/file/d/1iwYRPDkUlZ53mPo5VtxXNu6pZ7RB_N9S/view?usp=sharing)

I have not found correct documentation of the versions of the orthanc compatible with the OHIF viewer 2.0 or of how to solve this error.

**Comment by sedghi** [comment]
This loads fine in latest master

![CleanShot 2023-10-13 at 12 59 23](https://github.com/OHIF/Viewers/assets/7490180/31e3b434-0baf-412c-b3a7-a58d72f993cd)


Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
