### ISSUE TITLE
Problem rendering some US images.

### ISSUE THREAD

**Issue by YeuKo** [OHIF/Viewers#2521]
We have a problem loading images is some US mode studies. We am using the OHIF viewer to display images for several hospitals:
![captura imagen OHIF](https://user-images.githubusercontent.com/6795934/130612398-d097f256-83a0-4a21-b1a6-54f0422fd1dd.png)

After digging into metadata, we have observed some duplicated tags only in these problematic cases, for example, rows and columns fields:
![captura tag](https://user-images.githubusercontent.com/6795934/130612386-433ce8cc-def4-4ee3-a9dd-4a665364fde3.png)

Here is the image metadata:
![captura metadatas](https://user-images.githubusercontent.com/6795934/130612410-f8c8ccf0-90b1-487b-8f71-a7c4ad979ac9.png)

Here are some extra details:

- These images are correctly rendered in some viewers like "Microdicom" (Windows), but not in Horos (Mac) nor OHIF.
- We applied the solution mentioned in this issue, that solved some cases but not these ones: https://github.com/OHIF/Viewers/issues/2420#issuecomment-892141342
- This problem only happens with US that have these duplicated fields
- When we manually modify rows/columns metadata fields, we get to change the way it renders, but not correctly.
- The machine we are getting the images from is a SIENET model

An important detail is that these images are correctly rendered when they are loaded into OHIF viewer with drag/drop functionality, but not when we build the metadata ourselves.

Do you think we are missing any metadata? Maybe a solution could be to apply drag&drop logic to this building? If so, do you know how?

Thank you in advance.
Fran

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing


Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?
