### ISSUE TITLE
Measurement not getting clear

### ISSUE THREAD

**Issue by pmd23** [OHIF/Viewers#2527]
am also facing the same issue. while applying the new measurement tools on image in the standalone viewer. any update on this?

**I am using latest viewer which is available on npm.**  **I am loading json file in the viewer**

![image](https://user-images.githubusercontent.com/2580866/130425007-244573d5-34b9-4b3f-bc84-d56cf6ae079e.png)

return timepoint.studyInstanceUIDs is undefined
![image](https://user-images.githubusercontent.com/2580866/130432713-7e47ca91-b782-45a3-a2be-b18c37da9e6b.png)

@dannyrb @Zaid-Safadi 

https://user-images.githubusercontent.com/2580866/130438619-75a94dad-c663-4501-95ba-d9e608911232.mp4

_Originally posted by @pmd23 in https://github.com/OHIF/Viewers/issues/2264#issuecomment-903602105_

**Comment by pmd23** [comment]
@swederik @dannyrb please any update on this

**Comment by sedghi** [comment]
I cannot reproduce this on https://viewer-dev.ohif.org/viewer/1.3.6.1.4.1.14519.5.2.1.7009.2403.459769504433903221904322299373

Is there a chance this has been fixed?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
