### ISSUE TITLE
How do I fix to load correct DICOM image in v3? 

### ISSUE THREAD

**Issue by ChoiYuChan** [OHIF/Viewers#2542]
Hello all! 
I've just tried to make an application for the ultrasound DICOM file.
and I just have a little knowledge about programming I've been learning.

I'd like to use the latest version of OHIF. and I tried to upload DICOM files on local. but it looks like the below image.

![image](https://user-images.githubusercontent.com/88298993/132832865-38a3b61a-0f0f-4ba7-b9b9-f524191a5088.png)

I could guess it has different metadata so it may be a problem to load the image. 
and I tried to modify a code for metadata and study config files.
but I didn't figure out how to solve it.

if who knows the answer.  I hope you can teach me the solution.

your work will be very helpful for me and thanks for it.

**Comment by sedghi** [comment]
I don't believe this issue happens in latest master branch. Feel free to reopen if it does 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
