### ISSUE TITLE
Showing some validation or warning in Exclamation Triangles when load dicom image.

### ISSUE THREAD

**Issue by rohit64Singh222** [OHIF/Viewers#2565]
Showing some validation or warning in Exclamation Triangles when load dicom image.

@ohif/viewer : 4.9.24

![image](https://user-images.githubusercontent.com/57747188/134903104-ef33bf99-3da7-4a7a-98d5-87d2fd1355c9.png)

![image](https://user-images.githubusercontent.com/57747188/134903174-af6962f2-8b8c-49c3-9ec0-0627a0e06de4.png)

Please suggest what is issue on that.   Please provide solution.

**Comment by rohit64Singh222** [comment]
Hello, 

Any one please suggest or help some thing to fix this issue.

**Comment by rohit64Singh222** [comment]
Hello,

Any one please suggest or help some thing to fix this issue.

**Comment by sedghi** [comment]
The warning is telling that:
- The dataset frames have different orientations
This means that the images don't have consistent orientation. If you have them locally, you can open the dicom and look into the [dicom tag ](https://dicom.innolitics.com/ciods/rt-dose/image-plane/00200037)

- Is not reconstructable
Because of the above inconsistency, the series is not reconstructable in 3D, i.e., you cannot use MPR to view it from other planes (other than the acquisition plane)

**Comment by kamlesh0606** [comment]
@sedghi Thanks for Update.

For Image Orientation (0020,0037)  Dicom Tag, we will update in Machine Side and Check above Query .

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
