### ISSUE TITLE
Not able to load json file into v3

### ISSUE THREAD

**Issue by pmd23** [OHIF/Viewers#2577]
I am trying to load json dicom file in ohif viewer v3, but I am not able to load it showing some error in the console.

![image](https://user-images.githubusercontent.com/2580866/135814212-ff3da271-fe31-4850-b74f-1633d421fd98.png)

any thing else need to configure for this?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
