### ISSUE TITLE
Delete measurement after it has been saved.

### ISSUE THREAD

**Issue by amita125** [OHIF/Viewers#2585]
When we create a measurement in the ohif viewer we can view the measurements in the measurements table. After we click the save button we are able to save the measurement for that specific study. After the refresh page as well the measurements are available but when we click the delete button from the measurement table the measurements get removed but after the refresh page, the measurements are still there. Is there a way to delete a measurement after it has been stored? 

Below image the measurement if present and if select the delete, it deletes from the viewer but when reload measurements still present
![image](https://user-images.githubusercontent.com/49608334/137695930-3d8e3d66-5d1b-4db1-a33f-2dd4554e1a75.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
