### ISSUE TITLE
Dose Record structure report Not Loading in Cornerstonejs library(OHIF VIEWER)

### ISSUE THREAD

**Issue by arunjoshtech** [OHIF/Viewers#2589]
Dear Team,
When I load Dicom dose Record images that not loading in the Ohif viewer.
sample DICOM Dose record images and error code in OHIF Viewer is attached here.
It make application freeze the browser.
[DICOM DOSE REPORT.zip](https://github.com/OHIF/Viewers/files/7389555/DICOM.DOSE.REPORT.zip)
![OHIF ERROR](https://user-images.githubusercontent.com/63642104/138291406-8dc9b5d4-3c66-47ba-af4e-2f85581d996d.jpeg)
![DOSE RECORD](https://user-images.githubusercontent.com/63642104/138291412-aa818b8a-93fc-4b64-9f42-acf878cfd5bb.jpeg)

> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

### Describe the Bug

_A clear and concise description of what the bug is._

### What steps can we follow to reproduce the bug?

1. First step
2. Second step
3. ...

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I think that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
