### ISSUE TITLE
How to enable context menu on annotation right click?

### ISSUE THREAD

**Issue by igor-sysoev** [OHIF/Viewers#2610]
I'm missing this feature.

**Comment by sedghi** [comment]
You can take a look how it is implemented here 
https://github.com/OHIF/Viewers/blob/v3-stable/extensions/cornerstone/src/init.js#L84-L199

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
