### ISSUE TITLE
DICOM-SEGMENTATION LOADING ISSUE - Cannot populate shared groups uniquely without multiple frames

### ISSUE THREAD

**Issue by venkatesh-sp** [OHIF/Viewers#2637]
- Dataset along with segmentation files are able to load into the [viewer](https://deeplobe.s3.amazonaws.com/media_assets/Screenshot_from_2021-12-15_17-24-34.png) using local files.
- Dataset along with segmentation files causes error and not able to load into the [viewer](https://deeplobe.s3.amazonaws.com/media_assets/Screenshot_from_2021-12-15_17-24-13.png) using public url of file

> Using public url we fetch blob data of file and pass collection of blobs as argument to files_to_studies

> Segmentation file generated using [dcmqi](https://github.com/QIICR/dcmqi)

**Comment by sedghi** [comment]
We have updates our segmentation workflow significantly. Can you try again in the master branch?


Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
