### ISSUE TITLE
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word .... openjpegwasm_decode.js

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#2650]
We have been using Standalone version V2 for some time, it works well. 

We downloaded the newer OHIF with all the updates/fixes but now its not showing the images. I know its getting the data as thumbnails shows correct number of sequences and image count in each thumbnail however, there are no images in the thumbnails. 

There is no CORS errors as my previous compile works well on the same server. Also, the error I'm getting in the newer compile is not regarding CORS.

I am following new [json schema](https://github.com/OHIF/Viewers/issues/1500) and URL is given below.

url: "wadouri:https://myIP/orthanc/instances/270373c7-680c7088-8ad05670-2bdc2164-c48e64f2/file",

Thanks!

![error - Copy](https://user-images.githubusercontent.com/23708609/147514855-630c593b-e1f9-46ce-b89f-3c89cec7e485.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
