### ISSUE TITLE
MR - Explicit VR Big Endian 

### ISSUE THREAD

**Issue by brunovolant** [OHIF/Viewers#2673]
Hello dear community, 

I have a weird issue with some MR images.
The images are retrieved from qido/wado and there is no error but when the images are displayed in ohif, they are really bright with some black areas. 

If I test this image on https://viewer.ohif.org/local. it's working.

![Screenshot 2022-01-20 111003](https://user-images.githubusercontent.com/15800333/150308324-4cede847-3e4b-45ff-9213-1a50c30e2636.png)
![Screenshot 2022-01-20 110914](https://user-images.githubusercontent.com/15800333/150308330-c6038d5a-1104-47c2-8b23-06b69298af4d.png)

Here is the DICOM file:

[00001.1.2.840.113619.2.134.1762853927.1683.1564666069.927.dcm.zip](https://github.com/OHIF/Viewers/files/7903791/00001.1.2.840.113619.2.134.1762853927.1683.1564666069.927.dcm.zip)

Thanks in advance 
Regards

**Comment by jensen0914** [comment]
I sent your sample image to a DCM4CHEE archive and viewed it using QIDO/WADO on OHIF Viewer v4.12.10 and it looks fine and matches what I see when loading it from a file via the "local" link.

Todd Jensen, PhD
Jensen Informatics LLC

**Comment by sedghi** [comment]
This loads fine in latest master

![CleanShot 2023-10-13 at 12 35 48](https://github.com/OHIF/Viewers/assets/7490180/a5e58a8d-702b-4de0-b161-3c2f7263a8de)


Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
