### ISSUE TITLE
Dependencies missing from npm

### ISSUE THREAD

**Issue by xtfer** [OHIF/Viewers#2694]
The NPM build of 4.12.13 appears to be missing, at minimum, 610.bundle.min.worker.js and 888.bundle.min.worker.js. These are part of cornerstone.

Am I missing something?

**Comment by swederik** [comment]
Hi Christopher,

Thanks for the report.

Can you explain how you arrived at this issue? It could be related to the
dynamic imports we use for the codecs from WADO Image Loader. Maybe we are
accidentally excluding them while packaging the NPM version. If this is the
case then we need to add an end to end test that checks codecs are loading
properly (which I guess we should have anyway)

Which NPM package are you referring to? @ohif/viewer ?

Thanks!

Erik

**Comment by xtfer** [comment]
Thanks @swederik 

I'm loading the viewer using the embedded method, with https://unpkg.com/browse/@ohif/viewer@4.12.13/dist/.

So...
```
<script src="https://unpkg.com/@ohif/viewer@4.12.13/dist/index.umd.js" crossorigin></script>
```

This is mostly working fine, however on some images, the viewer is failing trying to load some files probably requested by the cornerstoneWADOImageLoader. 

![CleanShot 2022-01-29 at 18 26 09@2x](https://user-images.githubusercontent.com/40190/151651946-97305322-7da1-4add-b509-521c551a81b7.png)

Potentially related issues:
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/401
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/403

**Comment by swederik** [comment]
Ah yeah ok. The script tag version needs to be switched to use the non-dynamic import (single file) version of the Wado image loader. This is definitely my fault, I thought I had tested that...

In the next version we plan to stop supporting the script tag version because it's a pain for stuff like this.

Thanks,

Erik

**Comment by xtfer** [comment]
>  The script tag version needs to be switched to use the non-dynamic import (single file) version of the Wado image loader. 

Is that a I thing I need to do in my code, or something you can fix? :)

**Comment by xtfer** [comment]
@swederik Okay, I'll take a look.

**Comment by swederik** [comment]
>PWA folder is we run the viewer in a subdirectory, and some of the assets try to load from root

Maybe you need to set PUBLIC_URL when building if you plan to serve it from a subdirectory. I couldn't find it in v2 docs, but in v3 docs it's here: https://v3-docs.ohif.org/configuration/index/#environment-variables

**Comment by xtfer** [comment]
@swederik On a related note, neither v2 nor v3 will load in a subdirectory currently. I've opened a new issue at https://github.com/OHIF/Viewers/issues/2695, so there is currently no way to run the viewer below root.

**Comment by sdenardi** [comment]
Apologies in advance for surfacing an old thread.

We tried switching from the bundle build to using the PWA to work around this issue (and enjoy the general benefits the PWA viewer affords). However, we're running into some [Worker CORS](https://stackoverflow.com/questions/58098143/why-are-cross-origin-workers-blocked-and-why-is-the-workaround-ok/) issues.

We serve the viewer in an `iframe` from our app, but load the assets from a CDN. This isn't an issue when loading the viewer via a `<script>` tag, but when all of the assets reside in another domain we get errors creating `Workers` with scripts from another domain. This looks like a known browser limitation, `Workers` fetch scrips using `same-origin`, which is frustrating. 

We're investigating what we see as our two current options:

- A) modifying the webpack config as you specified to make a usable bundle loaded by a `<script>` tag
- B) somehow modify the webpack `worker-loader` to fetch worker scripts before loading or use `importScripts` (as described in the SO link above) so we can use the PWA assets from our CDN

We'd prefer to go with the PWA approach, since it seems that'll be the canonical method going forward. We weren't able to find any other folks having similar issues loading the PWA assets from another domain, I don't think we're doing anything particularly novel.

**Comment by NikGurev** [comment]
@sdenardi do you have any progress with that? Your experience would be much appreciated

**Comment by NikGurev** [comment]
I'm using angular 11 and this approach helped: https://stackoverflow.com/questions/60857214/uncaught-domexception-failed-to-execute-importscripts-on-workerglobalscope

instead of `ace`-related files, corneerstone files were added:

```
"architect": {
        "build": {
            "builder": "@angular-builders/custom-webpack:browser",
                "options": {
         ......
         
                     "scripts": [
                          "node_modules/cornerstone-wado-image-loader/dist/610.bundle.min.worker.js",
                          "node_modules/cornerstone-wado-image-loader/dist/888.bundle.min.worker.js"
                      ]
```
