### ISSUE TITLE
Building OHIF v2 and v3 doesn't work in a subdirectory

### ISSUE THREAD

**Issue by xtfer** [OHIF/Viewers#2695]
### Describe the Bug

Attempting to run OHIF v2 in a directory below the server route fails. 

### What steps can we follow to reproduce the bug?

1. Check out OHIF master
2. `$ export PUBLIC_URL=/foo/' (or any alternative, non-root path)
3. `yarn run build`
4. Serve and load the site on that path

All the assets seem to load fine except `third_party`, which still tries to load from root (e.g. third_party/workbox/workbox-v5.1.4/workbox-sw.js).

### Related issues

- https://github.com/OHIF/Viewers/issues/1125
- https://github.com/OHIF/Viewers/issues/2540

**Comment by xtfer** [comment]
v3 also fails, but without an error, as far as I can tell. Just loads a white screen.

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

Please try and re-open if the issue persists
