### ISSUE TITLE
Opacity settings are not applied to all segments

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2706]
This is a very minor issue, but I thought I note it before I move on.

Source of data: https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.3671.4754.304001015100152820571364796240

![2022-02-09_17-06-18](https://user-images.githubusercontent.com/313942/153298297-c38e678f-6548-454a-bd8d-5960e4d66629.gif)

**Comment by Punzo** [comment]
IDC closing this since the rendering settings are a property of active and inactive LabelMaps in cornerstone2D. When we have overlapping segments, the segments in a same series (i.e. same segmentation) are in different labelmaps and only one can be active. To fix this we would need to change how cornerstone2D segmentation rendering works. This is not IDC high priority at the moment.
