### ISSUE TITLE
retrieveMetadataLoaderAsync uses QIDO-RS service instead of WADO-RS

### ISSUE THREAD

**Issue by PantelisGeorgiadis** [OHIF/Viewers#2711]
### Describe the Bug

The async metadata loader is using the QIDO-RS service https://github.com/OHIF/Viewers/blob/2f443fa2efa223ac0fcdf238eee834c6a4ee3fc1/platform/core/src/studies/services/wado/retrieveMetadataLoaderAsync.js#L76, to obtain the series metadata while the sync version is using WADO-RS https://github.com/OHIF/Viewers/blob/2f443fa2efa223ac0fcdf238eee834c6a4ee3fc1/platform/core/src/studies/services/wado/retrieveMetadataLoaderSync.js#L61. The correct service to use for series metadata retrieval is the WADO-RS and, therefore, the async metadata loader service needs to be changed.

This was probably overlooked because most of the servers (DCM4CHEE, Orthance, etc.) are exposing QIDO-RS and WADO-RS service endpoints under the same root URL.

### What steps can we follow to reproduce the bug?

1. Load a study to trigger a series metadata query. 
2. Observe that the series metadata query uses QIDO-RS service (qidoRoot config param) instead of WADO-RS (wadoRoot config param).

**Comment by parneshraniga** [comment]
This bit me today. I am developing our own PACS which exposes different endpoints for QIDO and WADO. What's more, the down stream code seems to expect the QIDO results (one meta-data entity per series rather than one meta-data entity per instance for all instances in the series). 

This is also highlighted by the URL used ( "GET /wado/studies/1.2.840.113564.9.1.2994789779.78.2.5005161809/series HTTP/1.1" 200 OK), which I don't think conforms to wado spec but does to qido spec.

**Comment by parneshraniga** [comment]
https://github.com/OHIF/Viewers/pull/2712#discussion_r808796912

Makes sense now. My workaround at the moment is to redirect to the QIDO url on my PACS.

**Comment by sedghi** [comment]
might be related topic
https://github.com/OHIF/Viewers/issues/2176

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
