### ISSUE TITLE
Incorrect handling of single-slice segmentations

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2733]
It appears that OHIF is unable to correctly handle single-slice segmentations.

Here's the sample: https://idc-tester-1.web.app/projects/idc-tcia/locations/us-central1/datasets/duke_breast_cancer_mri_seg_dataset/dicomStores/duke_breast_cancer_mri_seg_store/study/1.3.6.1.4.1.14519.5.2.1.126811963435115860548863313780820690347 (both the viewer instance and the DICOM store are non-public, but both @Punzo and @igoroctaviano should have access).

OHIF view:

![image](https://user-images.githubusercontent.com/313942/157490626-9eabb05f-5337-4ecd-97ac-87ee6c168afb.png)

Slicer view of the same study:

![image](https://user-images.githubusercontent.com/313942/157490729-2ef2da38-d35b-4968-b1b1-b52e840765fc.png)

OHIF MRP also appears to be messed up:

![image](https://user-images.githubusercontent.com/313942/157490868-87d71348-075d-47a4-8137-d9073f64a13f.png)

**Comment by Punzo** [comment]
working on it

**Comment by Punzo** [comment]
Hi @fedorov I checked the issue, and the issue is actually in the data:

the segmentation has 6 frames and this are the reference values 

```
multiframe.PerFrameFunctionalGroupsSequence[i].DerivationImageSequence.SourceImageSequence.ReferencedSOPInstanceUID
multiframe.PerFrameFunctionalGroupsSequence[i].PlanePositionSequence.ImagePositionPatient

1) 
ReferencedSOPInstanceUID | 1.3.6.1.4.1.14519.5.2.1.334861096229480140557548845610334044965
ImagePositionPatient | -180.968994\-214.867004\32.6519012
2) 
ReferencedSOPInstanceUID | 1.3.6.1.4.1.14519.5.2.1.334861096229480140557548845610334044965
ImagePositionPatient | -180.968521\-214.866821\-34.8480644
3)
ReferencedSOPInstanceUID | 1.3.6.1.4.1.14519.5.2.1.334861096229480140557548845610334044965
ImagePositionPatient | -180.968994\-214.867004\40.1519012
4)
ReferencedSOPInstanceUID | 1.3.6.1.4.1.14519.5.2.1.334861096229480140557548845610334044965
ImagePositionPatient | -180.968994\-214.867004\32.6519012
5)
ReferencedSOPInstanceUID | 1.3.6.1.4.1.14519.5.2.1.334861096229480140557548845610334044965
ImagePositionPatient | -180.968521\-214.866821\-27.3480625
6)
ReferencedSOPInstanceUID | 1.3.6.1.4.1.14519.5.2.1.334861096229480140557548845610334044965
ImagePositionPatient | -180.968521\-214.866821\71.6519394
```

As you see the ImagePositionPatient are right, but the ReferencedSOPInstanceUID is wrong. Probably 3DSlicer ignores ReferencedSOPInstanceUID and just uses ImagePositionPatient. For dcmjs we use ImagePositionPatient only if the ReferencedSOPInstanceUID is missing (i.e. if ReferencedSOPInstanceUID is missing, we do this https://github.com/Punzo/dcmjs/blob/master/src/adapters/Cornerstone/Segmentation_4X.js#L625-L665).  See https://github.com/Punzo/dcmjs/blob/master/src/adapters/Cornerstone/Segmentation_4X.js#L626-L630 why we prefer  ReferencedSOPInstanceUID over ImagePositionPatient (3DSlicer does not care of that, because it loads all the data in the ram in VTK objects in full 3D).

**Comment by Punzo** [comment]
meet with @fedorov , we decide to put this in hold, since if we can't rely on the ReferencedSOPInstanceUID, we would need to use ImagePositionPatient to find the referenced slice. However we would need additionally info in the segmentation dicom (e.g. referencedSeriesUID) to determine univocally the reference between segmentation frame slide and source data frame slide.

**Comment by fedorov** [comment]
I fixed the converter, and the issue is resolved (data is in the same DICOM store). If you take a look at the updated segmentations, they have `ReferencedSeriesSequence > SeriesInstanceUID` - as we discussed, I think it would be more robust if those references were used to establish the matching series, but not to initialize the geometry of the segmentation.

**Comment by Punzo** [comment]
> I fixed the converter, and the issue is resolved (data is in the same DICOM store). If you take a look at the updated segmentations, they have `ReferencedSeriesSequence > SeriesInstanceUID` - as we discussed, I think it would be more robust if those references were used to establish the matching series, but not to initialize the geometry of the segmentation.

Done in https://github.com/dcmjs-org/dcmjs/pull/253
