### ISSUE TITLE
When click on Measurements it throughs error

### ISSUE THREAD

**Issue by mbshingala28** [OHIF/Viewers#2747]
When click on Measurements it throughs error
![image](https://user-images.githubusercontent.com/58248433/158615251-ce4493a9-3cc9-489b-b321-5ca0e5301127.png)

![image](https://user-images.githubusercontent.com/58248433/158615417-a726b701-d756-4cd1-af4f-0737da0d657a.png)

![image](https://user-images.githubusercontent.com/58248433/158615549-d1cf932a-9207-41dd-b3bd-8675000d319a.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
