### ISSUE TITLE
It requires two clicks to open a series from the study list

### ISSUE THREAD

**Issue by j6u** [OHIF/Viewers#2757]
### Repro
Open a study and try navigate to a different series by clicking on another series
It doesn't open on one click

### Expected
We should be able to open a different series by click one time

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
