### ISSUE TITLE
Reference Line

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#2764]
Greetings OHIF users,

I have been using [Reference Lines](https://github.com/OHIF/Viewers/pull/1482) in OHIF build since Dec 2020. It has been working fine. 

Downloaded latest version of OHIF (Mar 2022), applied changes as for Reference Lines as mentioned [here ](https://github.com/OHIF/Viewers/pull/1482) but its not working normally, e.g, sometime RL does not appear at all, other times for some series it won't show the lines whereas the older build would show the lines. In other words, there seems to be inconsistency between same piece of RL code running in the newer OHIF version.

Any update to Reference Line code considering recent changes to OHIF? Or any assistance what could be the issue?

Best regards,
Ric

**Comment by jensen0914** [comment]
I've added this code in a fork based on 4.12.26 and see the following warning in the console:

**Could not render reference lines, image plane modules not defined.** @ enableReferenceLines.js:58

I haven't tracked down why it cannot get the metadata required for the MR series I tried it with.

**Comment by jensen0914** [comment]
The missing metadata is also leading to other issues (like cannot use MPR, get warning not a valid 3D series).

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
