### ISSUE TITLE
BUG/Error dcmjs On Empy Views

### ISSUE THREAD

**Issue by ArturRod** [OHIF/Viewers#2771]
Versión OHIF: 4.12.24
Versión DCMJS: 0.19.9

When opening a view without data, that is, putting several images with some empty, it fails since it finds that it is not a corresponding dicom file. Pass in method: setContentFromByteArray(byteArray) - DicomHtmlViewport.js

Example: I have 4 series, but if I put the view in 6 series it fails:
![fallo](https://user-images.githubusercontent.com/86238895/161956516-f7f6fbcb-b321-4861-b6f0-be7f6b4688bc.PNG)

I solved it with a try catch, but yours would be to fix it from dcmjs, the error ocurred in readFile():
![solution](https://user-images.githubusercontent.com/86238895/161956688-16b5b722-0c13-420a-8616-fc597c4d5025.PNG)
Result:
![result](https://user-images.githubusercontent.com/86238895/161956849-81887619-27f8-4451-9972-d93515319220.PNG)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
