### ISSUE TITLE
Secondary capture colour image does not render on v3-demo

### ISSUE THREAD

**Issue by anthonyjang** [OHIF/Viewers#2788]
I am running v3-demo on https://v3-demo.ohif.org/local and load attached sample file and having following display.
![OHIFViewer](https://user-images.githubusercontent.com/48885675/165551562-3eb003a2-9785-4f46-806e-e6f01dd87a70.jpg)

Please refer to the attached sample dicom file "colortest1-1.dcm", unzip from colortest1-1.zip.
[colortest1-1.zip](https://github.com/OHIF/Viewers/files/8573299/colortest1-1.zip)

**Comment by s2ramana** [comment]
It is easy to reproduce by dragging the sample DICOM object attached by Anthony into v3-demo URL. By looking at the way it is rendering, it is as if the image is not being recognized as a color image even though samples per pixel is 3 and photometric interpretation is set to YBR_RCT.

**Comment by s2ramana** [comment]
@swederik will the integration of Cornerstone 3D into OHIF fix issues like this or will the rendering of 2D images be unchanged? I looked at the Cornerstone 3D examples and if there was an example where you could drag and drop a local image, it would be useful to see what the behavior is.

**Comment by swederik** [comment]
My guess is that it's a metadata issue in OHIF or maybe in the WADO image loader. So I don't think the change to cs3d will fix it by itself, but we will make a note to look into it.

**Comment by s2ramana** [comment]
@swederik I agree that it is likely a metadata issue. It looks similar to the issue reported in #2790 from its appearance. What is the easiest way to debug Cornerstone from OHIF? Do I need to rebuild Cornerstone to be not minified? My guess is that this is likely a simple issue to fix so I wanted to investigate it further.

**Comment by RoshniPal** [comment]
@s2ramana Turns out the JSON structure mentioned [here](https://github.com/OHIF/Viewers/issues/2420#issuecomment-1119588320) render's the image correctly. However, issue of viewing all the frames of dicom images still persists.
Additionally, I also observed issue rendering the image when the photometric interpretation tag's value is YBR_FULL_422 and  it works with YBR_FULL or RGB.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
