### ISSUE TITLE
Problem viewing US modality/multiframe images. Wrongly stacked frames.

### ISSUE THREAD

**Issue by RoshniPal** [OHIF/Viewers#2790]
Hi team,

Version: @ohif/viewer - "4.12.18"
I am trying to view US modality/multiframe images in OHIF using the JSON supplied via the '?url=' query parameter but weird colors / wrongly stacked frames are visible as below.
![Weird Colors in US image](https://user-images.githubusercontent.com/37709570/166914794-70f6adbd-7cab-4474-8b9a-c325af1b29e6.png)

However, viewing the same in dicom web viewer (another open source dicom viewer : https://ivmartel.github.io/dwv/) displays it correctly as below.
![Dicom Web Viewer US image](https://user-images.githubusercontent.com/37709570/166914861-8f9f21a6-10c5-4e51-8b21-5abbb3094281.png)

I have gone through the similar issue but the fix doesn't seem to be working for me.  
https://github.com/OHIF/Viewers/issues/2420
https://github.com/OHIF/Viewers/issues/2262
Any help on the same would be appreciated.

**Comment by beavermml** [comment]
fix the JSON response file to include property PlanarConfiguration.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
