### ISSUE TITLE
DICOM images not loading in v2 or v3 viewer

### ISSUE THREAD

**Issue by OLI9292** [OHIF/Viewers#2794]
My company uses OHIF along with Orthanc to assess medical images. It works great, except that all DICOMs from one of our client hospitals fail to load in the OHIF viewer.

I’ve attached the error that is thrown in the console and a link to an example DICOM that is failing.

Any support would be greatly appreciated.

[https://shareable.s3.amazonaws.com/80f943cc-0889-422a-ae01-1632eea04387.dcm](https://shareable.s3.amazonaws.com/80f943cc-0889-422a-ae01-1632eea04387.dcm)

<img width="663" alt="Screen Shot 2022-05-06 at 10 08 45 AM" src="https://user-images.githubusercontent.com/13812317/167161881-c97b0968-f595-4051-8f8d-4e282f22a144.png">

**Comment by s2ramana** [comment]
It look like a crash with the Jpeg 2000 decoder (OpenJPEG). The sample image itself looks to be fine.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
