### ISSUE TITLE
how to integrate the standalone viewer with orthanic

### ISSUE THREAD

**Issue by cultulhul** [OHIF/Viewers#281]
i have set up the stand alone viewer to be served by a nodejs server running hapijs
when i visit the url i can view the sample dicoms. Now i want to integrate it with orthanc that when a user clicks a link it will open a new tab with the viewer.

i assume that for the viewer to display dicoms it needs to be given a json with a format similer to the sampleDicom.json is the assumption correct or is their another way.

 is their an easy way get a json file of the series that follows the sampleDicom.json format from orthanc rest api.

or is it possible to construct it manually from orthanc rest api
using something like https://www.npmjs.com/package/orthanc-client  

i hope what i wrote makes sense english is not my first launguage

**Comment by johannamussolini** [comment]
were you able to solve this issue? do you know how to open new files in the Stand Alone Viewer? I'm particularily have my DICOM files in their original folder which is hosted in AWS S3.
Any comment from your side would be really appreciated
Thanks

**Comment by cultulhul** [comment]
Yes i was able to, for it to work you have to construct a JSON object similar to the sampleDICOM.json
and pass the url of the JSON object to the url query parameter of the standalone viewer.

you can construct the json object by querying the orthanc  server api

**Comment by johannamussolini** [comment]
thanks! yes I figure it out. The problem is that I cannot generate the JSON file correctly... not sure if the  StandaloneViewer supports every DICOM file... or just some of them .... For some reason the standalone viewer is displaying to me the following error: 
Error: loadImageFromImageLoader: no image loader for imageId
    at loadImageFromImageLoader (ohif_cornerstone.js?hash=b2d4f3d201840adb2975e3fbc1f00e4786b64831:6133)
    at Module.loadAndCacheImage (ohif_cornerstone.js?hash=b2d4f3d201840adb2975e3fbc1f00e4786b64831:6199)

and this is my JSON file:
{
  "transactionId": "study",
  "studies": [
    {
      "studyInstanceUid": "1.2.826.0.1.3680043.2.1208.154494870514920191158835635",
      "studyDate": "20180817",
      "studyTime": "080835.000000",
      "patientName": "SANCHEZ MARIA DELIA",
      "patientBirthDate": "20050226",
      "patientId": "NO ID",
      "patientSex": "F",
      "seriesList": [
        {
          "seriesInstanceUid": "1.2.826.0.1.3680043.2.1208.254494870514920191158835642",
          "seriesBodyPart": "SPINE LUMBAR",
          "seriesNumber": "0001",
          "seriesDate": "20180817",
          "seriesTime": "080835.000000",
          "seriesModality": "OT",
          "instances": [
            {
              "columns": 3610,
              "rows": 4400,
              "instanceNumber": "0001",
              "photometricInterpretation": "MONOCHROME2",
              "bitAllocated": 16,
              "bitsStored": 12,
              "pixelRepresentation": 0,
              "samplesPerPixel": 1,
              "highBit": 11,
              "rescaleSlope": "1.00",
              "rescaleIntercept": "0.00",
              "imageType": "ORIGINAL\\PRIMARY\\OTHER",
              "sopInstanceUid": "1.2.826.0.1.3680043.2.1208.354494870514920191158835644",
              "url": "file://Users/johannamussolini/code/Viewers/StandaloneViewer/StandaloneViewer/private/testData/examples/1.2.826.0.1.3680043.2.1208.154494870514920191158835635/1.2.826.0.1.3680043.2.1208.254494870514920191158835642/1.2.826.0.1.3680043.2.1208.354494870514920191158835644.dcm"
            }
          ]
        }
      ]
    }
  ]
}

Not sure what is wrong...

**Comment by cultulhul** [comment]
i read some where that it only supports dicom p10 files but not sure where,
can you try putting the url of your dicom file in the sampleDICOM.json url field and see it it displays

**Comment by johannamussolini** [comment]
yes, that was the problem, I cannot read the files locally (reference for the solution: https://github.com/OHIF/Viewers/issues/177#issuecomment-465627101). Thanks so much for replying back!

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

For what it's worth, the easiest way to get Version 2 of the OHIF Viewer to work with Orthanc is to use it's DicomWeb plugin. Then, you can either:

_recommended for production:_

- Host the OHIF Viewer separately (at a different domain)
    - Setup orthanc behind a reverse proxy
    - Set appropriate CORS headers
    - Configure the OHIF Viewer to connect to Orthanc

_okay for development/local:_

- Build the app and use Orthanc's ServerFolder plugin to host the app
    - Configure the OHIF Viewer to connect to Orthanc

See here for more info: https://book.orthanc-server.com/faq/same-origin.html

Most of our example recipes use Orthanc, so they are also worth checking out:

- https://docs.ohif.org/essentials/data-source.html#set-up-a-local-dicom-server
- https://docs.ohif.org/deployment/recipes/nginx--image-archive.html
- https://docs.ohif.org/deployment/recipes/user-account-control.html
