### ISSUE TITLE
Update code to use dicom-microscopy-viewer extension

### ISSUE THREAD

**Issue by wx115** [OHIF/Viewers#2829]
> :hand: Many people requests features. Tell us why yours is important to the
> community. How does it add value? Why _this feature_?
>
> Is your request very specific to your needs? Consider
> [contributing it](https://docs.ohif.org/contributing.html) yourself! Or reach
> out to a community member that offers
> [consulting services](https://docs.ohif.org/help.html#paid--commercial).

## Request

**What feature or change would you like to see made?**
The current extension using dicom-microscopy-viewer needs to be updated. The current code in DocomMicroscopyViewport.js is compatible with dicom-microscopy-viewer 0.1.0 (https://www.npmjs.com/package/dicom-microscopy-viewer/v/0.1.0) but its current version is 0.39.0 (https://www.npmjs.com/package/dicom-microscopy-viewer/v/0.39.0). The rendering method (retrieving meta data) has changed.
...

**Why should we prioritize this feature?**
The current version of OHIF viewer does not render dicom images that are transcoded from WSI using the Orthanc dicomizer plug-in, and the error points to the rendering of dicom images using dicom-microscopy-viewer in OHIF viewer extension. 
...

**Comment by jamesdigid** [comment]
I've been tasked to start work on this but am slightly confused as I am able to see this working when i use the embedded version of OHIF but does not work for the react version. I assume this is still an issue as its not closed?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
