### ISSUE TITLE
Include 3D MPR with Axial, Coronal, and Sagittal options

### ISSUE THREAD

**Issue by lindadesmond** [OHIF/Viewers#2835]
> :hand: Many people requests features. Tell us why yours is important to the
> community. How does it add value? Why _this feature_?
>
> Is your request very specific to your needs? Consider
> [contributing it](https://docs.ohif.org/contributing.html) yourself! Or reach
> out to a community member that offers
> [consulting services](https://docs.ohif.org/help.html#paid--commercial).

## Request

**What feature or change would you like to see made?**

Please include 3D MPR with Axial, Coronal, and Sagittal options. 3D MPR enables us to measure organs in reformatted CT formats like coronal and sagittal views.
Most organs like the liver and kidneys are measured in the coronal planes.

**Why should we prioritize this feature?**

Using the cursor/pointer for CT/HU numbers is faster and a more precise way of differentiating air, fluid, muscle and bone

**Comment by ranasrule** [comment]
MPR is available in OHIF Viewer V2

**Comment by lindadesmond** [comment]
What we have in Viewer V2 is 2D MPR which takes measurements in one plane. What I am requesting is 3D MPR.  3D MPR is required for the OHIF viewer to be useful to a radiologist. Without it, they cannot be able to measure the liver, kidney, and any other organs in the right places.

**Comment by tiagopedrosoftmakersbr** [comment]
Hi! This feature is added to project?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

![CleanShot 2023-10-13 at 09 54 48](https://github.com/OHIF/Viewers/assets/7490180/3272a887-6efb-4dbf-9cce-bb352bb90329)
