### ISSUE TITLE
TypeError: n.Value is undefined

### ISSUE THREAD

**Issue by floringhimie** [OHIF/Viewers#2839]
## Bug Report
search for studies vendors~app.bundle.c05fa7770938a2991657.js:2:1823903
TypeError: n.Value is undefined
    getModalities http://192.168.0.0:3000/app.bundle.315e6e30fbc4268b0557.js:1
    p http://192.168.0.0:3000/app.bundle.315e6e30fbc4268b0557.js:1
    p http://192.168.0.0:3000/app.bundle.315e6e30fbc4268b0557.js:1
StudyListRouting.bundle.a8093f277e170a176e09.js:1:39553

### Describe the Bug

Hi,
I'm using OHIF docker image, Version Number | 4.12.30
With dcm4chee-arc Version 5.25.2,58cc8cb,2022-02-14
I'm not able to view Study List, it's a black page, if I'm opening one study with direct link it's loading the image.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
