### ISSUE TITLE
Hello, could you tell me the reason why OHIF displays the garbled Chinese names?

### ISSUE THREAD

**Issue by huangji123** [OHIF/Viewers#2841]
![image](https://user-images.githubusercontent.com/100657287/179383233-6ed43637-ea59-4eb6-a979-c632d2a55d59.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
