### ISSUE TITLE
W/L is displayed incorrectly when using json metadata.

### ISSUE THREAD

**Issue by chaoao** [OHIF/Viewers#2842]
### W/L is displayed incorrectly when using json metadata.

- I'm using json metadata like this: "http://localhost:3000/viewer?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json", and W/L shows incorrectly
- I'm using master version downloaded from github. (V2)
- I didn't change any code.

My OHIF Viewer shows W/L is 1600/-600:  
![Snipaste_2022-07-18_18-40-19](https://user-images.githubusercontent.com/985311/179648526-3bc43ca6-fb5a-4e83-93ed-13299184f928.png)
![Snipaste_2022-07-18_18-40-55](https://user-images.githubusercontent.com/985311/179648561-30154df9-1deb-43a8-b900-953a2d19ce03.png)

The correct W/L should be 300/40:  
![Snipaste_2022-07-19_10-12-15](https://user-images.githubusercontent.com/985311/179649240-c12259db-e3c6-4a35-8eeb-cf00c5f39177.png)

Is this a bug or I've done something wrong? 
Help please.

**Comment by abasb75** [comment]
i have this problem!

**Comment by beavermml** [comment]
this is because the viewer will be using the values from JSON files instead of grabbing the data from the DICOM metadata itself. You can see that in the JSON response it shows 1600/600

**Comment by abasb75** [comment]
You need add 'RescaleIntercept' tag to image's metadata in json:

`"RescaleIntercept" = $dicom->value(0x0028, 0x1052)`

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
