### ISSUE TITLE
Import modal provider to studylist

### ISSUE THREAD

**Issue by MurilosSampaio** [OHIF/Viewers#2862]
## Question

I'm adding a new column in the studylist, in this new column we have a dropdrown, I'm trying to add a modal provider in the studylist component, so the functions in the dropdown can open the modal. One example of the functions are to display the dicom information of that study, export the image or download the exam.

What is the correct way of implementing this provider?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
