### ISSUE TITLE
getDateEntryFromRange  has no return

### ISSUE THREAD

**Issue by joweste** [OHIF/Viewers#2885]
> **Before Creating an issue**
>
> - Are you running the latest version?
Yes
> - Are you reporting to the correct repository?
Yes
> - Did you search existing issues?
Yes

## Bug Report
In this function in  ...Viewers\platform\ui\src\components\studyList\TableSearchFilter.js
"today.subtract(numOfDays, 'days') has no return"

[const getDateEntryFromRange = (today, numOfDays, edge = 'start') => {
  if (typeof numOfDays !== 'number') {
    return;
  }

  if (edge === 'end') {
    return today;
  } else {
    today.subtract(numOfDays, 'days');  -- no return
  }
};
](url)
### Describe the Bug

_A clear and concise description of what the bug is._
function without return

### What steps can we follow to reproduce the bug?

1. First step
2. Second step
3. ...

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Can you please add more details if you can?
Please re-open the issue if it still happens in the latest master branch

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
