### ISSUE TITLE
Dicom RT and Seg Extensions export equal names

### ISSUE THREAD

**Issue by joweste** [OHIF/Viewers#2893]
> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

### Describe the Bug
Dicom segmentation and diocom RT extensions has the same export name: OHIFExtDicomSeg

Another problem is that dicom-rt is not working when added in extensions at runtime, using umd package output

### What steps can we follow to reproduce the bug?
Just open the umds generated and look at line 'exports'

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
