### ISSUE TITLE
Rectangle and Angle Annotation can not be deleted in v3.2

### ISSUE THREAD

**Issue by JennyLeePMH** [OHIF/Viewers#2901]
### Rectangle and Angle Annotation can not be deleted
Created rectangle and angle can not be deleted.

### Step to reproduce

1. Go to v3-demo.ohif.org
2. Open any series
3. draw a rectangle 
4. right click on the rectangle, select "Delete measurement"
5. Can not delete rectangle

### Step to reproduce
1. Go to v3-demo.ohif.org
2. Open any series
3. draw an angle
4. right click on the angle, select "Delete measurement"
5. Can not delete angle

**Comment by JennyLeePMH** [comment]
In general, the rectangle and angle tool behaves differently than ruler, bidirectional, annotation and ellipse tool.  Any created rectangle and angle cannot be deleted, labeled nor tracked.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
