### ISSUE TITLE
Rendering issues with some ultrasound studies

### ISSUE THREAD

**Issue by racacere** [OHIF/Viewers#2928]
### Describe the Bug
One of our users reported us visualization issues with some DICOMS generated by the same ultrasound machine. We've compared the Dicoms tags of the problematic studies with the tags of normal ultrasounds, but we can't find relevant differences. This issue only happens with Ohif Viewer, in Horos and Weasis all of this images are rendered without problems.

The problem is that images are rendered inverted on his vertical axis and the only workaround is to zoom-in it, after that the image is correctly rendered.

An anonymized example a problematic study can be downloaded here: https://drive.google.com/file/d/1Z97rYEpoXPcq0k6GyLO08UnejxoSbFpc/view?usp=sharing

### What steps can we follow to reproduce the bug?

1. Download the study
2. Open it with Ohif viewer
3. The image is rendered vertically inverted
4. Zoom-in it solves the problem

Anyone have some idea of what is the root of the problem?

**Comment by sedghi** [comment]
This is certainly a weird one. 
I tried on cornerstone3D itself (https://www.cornerstonejs.org/live-examples/local.html) and works fine, so i'm wondering if 
it is a metadata provider issue, like OHIF is giving some metadata that shouldn't

**Comment by rmasad** [comment]
Does anyone have any idea which field is causing problems? I have the same problem in some studies and I can try to solve it (or modify the metadata of that study).

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
