### ISSUE TITLE
Loading Mask in V3 stable not working in Cornerstone3D

### ISSUE THREAD

**Issue by krishnav05** [OHIF/Viewers#2929]
Hi.
I have been trying to load mask/rtstruct in the v3 OHIF by following this example.
https://examples.dcmjs.org/displaysegmentation/

This last part was setting the mask on the study. 

              const { setters, state } = cornerstoneTools.getModule(
                 "segmentation"
              );
            console.log(labelmapBufferArray[0]);

            setters.labelmap3DByFirstImageId(
                imageIds[0],
                labelmapBufferArray[0],
                0,
                segMetadata,
                imageIds.length,
                segmentsOnFrame
            );
            
But now v3 Viewer is using scalarData to show the segmentation.
My main issue is how to generate a scalarData from the mask/rtstruct so i can show over the viewer?
I tried using dcmjs to convert it into the arraybuffer as shown in the example , but don't have any further idea as how to generate the scalardata for the mask.
In the below image i have modified the scalardata's some values to 1 to test if it renders. Now i only have to update the values to correct location according to the mask.
![image](https://user-images.githubusercontent.com/48890831/190152272-301ab7dd-f3c3-4026-80d1-75c4cb2d2153.png)

Any help with this will be highly appreciated.

Thanks : )

**Comment by sedghi** [comment]
More complete SEG api is getting merge soon, but basically the idea is similar to view-source:https://dcmjs.netlify.app/vtkdisplay/

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
