### ISSUE TITLE
Install dependencies related to antd ERROR

### ISSUE THREAD

**Issue by AstridTrj** [OHIF/Viewers#2930]
When I installed antd using ‘yarn add’ under Viewer/platform, the following error occurred when running the project. I want to know how to solve the problem. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/40670592/190157777-05a69b00-418e-4d93-81ab-7afc2b3c077b.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
