### ISSUE TITLE
v3 SR Annotate item wrong handle coordinates after saving SR

### ISSUE THREAD

**Issue by ladeirarodolfo** [OHIF/Viewers#2937]
> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

## Bug Report
<img width="1060" alt="Screen Shot 2022-09-16 at 17 41 55" src="https://user-images.githubusercontent.com/39910206/190745187-d024b006-2777-4afa-b0b9-267eaeff7b4b.png">

### Describe the Bug
Hydrated annotate items has wrong handles positioning

_A clear and concise description of what the bug is._

### What steps can we follow to reproduce the bug?
- Go to viewer
- Select Annotate Tool
- Drawn an annotation (any size, any direction, orientation) (add label...)
- Select to Track annotation
- Save SR

Expected
- Final drawing should be equivalent as user's drawing

Results
- Final drawing does not match user's drawing

Bug further info
- Final drawing has always the same orientation, size (see attachment)

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by 03shek** [comment]
@sedghi On our v3.3 release, we have a few SRs (very small fraction of all SRs) that were created on axial images by our users, but upon re-loading in the viewer, all the annotations in those SRs exhibit this issue (horizontal shift only, however). I haven't had any luck reproducing the bug, even within the same datasets. Any insight into what this issue stems from? I'm hoping we can reproduce it somehow.

**Comment by sedghi** [comment]
Can you try latest version 3.7 on release branch and 3.8 beta on master?

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
