### ISSUE TITLE
Ohif viewer not displaying images for dot net core 3.1

### ISSUE THREAD

**Issue by Nikhil2870** [OHIF/Viewers#2954]
> **Before Creating an issue**
>
> - Are you running the latest version?
yes

> - Are you reporting to the correct repository?
yes

> - Did you search existing issues?
yes

### Describe the Bug

I have created wadouri api in dot net core 3.1.  when calling api
https://localhost:44383/api/wado/wadouri?requestType=WADO&studyUID=1.2.826.0.1.5968184.2.2.1.1654683428751.75944&seriesUID=1.2.392.200036.9125.3.160140253206683.6510265661.5604903&objectUID=1.2.392.200036.9125.9.0.3206731710.1778420896.3472687940&contentType=application/dicom&transferSyntax=*

This gives following error,

"Invalid JPEG-LS stream, first JPEG marker is not a Start Of Image (SOI) marker"

***This api works in dot net 4.6.2 version

**Comment by ranasrule** [comment]
I don't think this has anything to do with OHIF viewer but rather your API

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
