### ISSUE TITLE
No loading indication shown when study is opened and loading...just blank viewer

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#2956]
Im using the latest version of OHIF v2 and as you can see in the video below when a study is opened  it displays an empty viewer(the larger the study the longer it is displayed as it seems to be loading the study metadata) with no indication that anything is happening which makes the end user think that its not working correctly and they reload the page again and again.

https://youtu.be/7i0hb_pNcmo

**Comment by ranasrule** [comment]
Anyone?

**Comment by ranasrule** [comment]
???

**Comment by ranasrule** [comment]
Can anyone be of help ?

**Comment by ranasrule** [comment]
@sedghi can you please provide some input into this?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
