### ISSUE TITLE
Error code: SBOX_FATAL_MEMORY_EXCEEDED when loading segmentations

### ISSUE THREAD

**Issue by mlaves** [OHIF/Viewers#2977]
### Describe the Bug

I created multi-segment segmentations using highdicom of size 167x512x512. When viewing these segmentations with the latest OHIF viewer from docker hub, my browser (Chrome) goes out of memory with `Error code: SBOX_FATAL_MEMORY_EXCEEDED`.

The segmentations were created with

```python
seg_dataset = hd.seg.Segmentation(
        source_images=image_datasets,
        pixel_array=mask,
        segmentation_type=hd.seg.SegmentationTypeValues.BINARY,
        segment_descriptions=segment_descriptions,
        series_instance_uid=hd.UID(),
        series_number=20,
        sop_instance_uid=hd.UID(),
        instance_number=1,
        manufacturer='XYZ',
        manufacturer_model_name='XYZ',
        software_versions='v1',
        device_serial_number='XYZ',
        omit_empty_frames=False
    )
```

When I only write out the first segment, the segmentation is rendered just fine, but Chrome consumes several GB of memory.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
