### ISSUE TITLE
how can i open local files in ohif viewer？

### ISSUE THREAD

**Issue by SeigiShin** [OHIF/Viewers#2985]

**Comment by simonalo** [comment]
When you add "/local" at the end of the url of OHIF (for example http://localhost:3000/local if you run OHIF locally) you can drag and drop your files.

**Comment by SeigiShin** [comment]
my ohif viewer was installed in docker on unraid, can i open files stored in unraid?

**Comment by sedghi** [comment]
You can use /local or /localbasic on any of the demos 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
