### ISSUE TITLE
i18 Translation error

### ISSUE THREAD

**Issue by Awxm** [OHIF/Viewers#2992]
## Bug Report
In the v3 - satble branch

### Describe the Bug

The translation of i18 doesn't add up , In StudyListFilter.tsx t('Study list') -> t('Studylist'),
There are many such formatting errors

### What steps can we follow to reproduce the bug?

```js
 {t('Clear filters')}
![1666771763617](https://user-images.githubusercontent.com/35212116/197970874-7f432abb-70ca-4e7a-8c09-410730ea67cd.jpg)

```

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
