### ISSUE TITLE
delete measurements error

### ISSUE THREAD

**Issue by Moyoung-Li** [OHIF/Viewers#2993]
![image](https://user-images.githubusercontent.com/37606111/198015348-dc88eca5-c264-4368-ae33-4f99cccb2bee.png)
![Uploading image.png…]()

**Comment by cheyvaert-medexprim** [comment]
Hello, I have another problematic. I cant delete the last measurement I did (I can replace previous dicom SR by new one but when i tried to remove all annotation I got an error because there is technically nothing to save).

Which version of the ohif do you use ?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
