### ISSUE TITLE
Impossible to delete the last annotation

### ISSUE THREAD

**Issue by cheyvaert-medexprim** [OHIF/Viewers#3005]
> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

## Bug Report

found with version 4.12.42 and 4.12.44

### Description

I cannot delete from server the last annotation from the ohif viewer.

### How to reproduce:

1. When I want to delete a measurement, I go the the "measurement panel",
2.  click on "delete" button of the annotation I want to delete. The annotation disappear from the viewer.
3. Then I click on "save measurement".

Results: I have a message: "Stow SR Error while saving measurement". 
The debug console show a message "[DICOMSR] Error while saving the measurements: No measurements provided." (which is logical on a certain way) and no DELETE or POST request is send to the server.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
