### ISSUE TITLE
OHIF 4.12.44 'CR' Error

### ISSUE THREAD

**Issue by AlbertoRequena** [OHIF/Viewers#3024]
Hi, the viewer works fine, I just can't display 'CR' studies.
[1.2.840.114257.42903.2015122103590801842.1.1.1.zip](https://github.com/OHIF/Viewers/files/10040300/1.2.840.114257.42903.2015122103590801842.1.1.1.zip)

**Comment by sedghi** [comment]
This is related to the fetchPalleteColor here, it reaches t[he last line which throws error](https://github.com/OHIF/Viewers/blob/v3-stable/platform/core/src/utils/metadataProvider/fetchPaletteColorLookupTableData.js#L71). @wayfarer3130 Should we throw at the end or just return null? If I remove throw it works fine

![image](https://user-images.githubusercontent.com/7490180/204958472-66e92f59-0e7d-43c9-9e2f-062a7ef318c4.png)

**Comment by wayfarer3130** [comment]
Lets change the error response to a console.error - it is technically wrong
there, but practically it is better to display as grayscale than to fail to
display - the colour mapping might not be right but one sees something.
The correct behaviour is of course to fix the bulkdata retrieve so that
there is a retriever to get the binary data.  I will create myself an issue
to fix bulkdata retrieve.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
