### ISSUE TITLE
OHIF V3 MPR reference lines

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#3030]
In OHIF V2 there are reference lines when MPR mode is activated by they seem to be missing in OHIF V3. Can they be added back?

**Comment by arunjoshtech** [comment]
You have to click the Crosshairs icon for it and two dots in its vertical line for a different purpose

**Comment by sedghi** [comment]
Reference lines are back in OHIF v3.3, they were never in v2 (don't know what you are talking about). 

Here is [the recent newsletter](https://ohif.org/newsletters/2022-11-21-ohif-viewer-3.3-dicom-segmentation-support), you can subscribe to get up to date news  https://ohif.org/news/

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
