### ISSUE TITLE
ViewerMain: Cannot read properties of undefined (reading 'isDerived')

### ISSUE THREAD

**Issue by anarnoli** [OHIF/Viewers#3035]
I am using OHIF Viewer as Embedded in Angular application. I am using `/local` approach to load local Dicom file. Sometimes it worked perfectly and sometimes throws below Error. Looking forward for help on this.

<img width="949" alt="Screenshot 2022-11-23 at 12 41 23 PM" src="https://user-images.githubusercontent.com/54370515/203489849-79295a94-c2de-4d0a-a823-6c6a5154449b.png">

**Comment by Georift** [comment]
Are you able to share the file you used to trigger this error?

**Comment by anarnoli** [comment]
[Archive.zip](https://github.com/OHIF/Viewers/files/10081633/Archive.zip)
Here is the sample files. Sometime it works and sometime it throws error.

**Comment by myousefipour** [comment]
This problem occurs when the output of this function (findDisplaySet in ViewerMain.js) is undefined,
For my case, the displaySetInstanceUid value for the last series was changed at runtime and display was blocked.

![image](https://user-images.githubusercontent.com/17563850/215605590-20f4d6c4-b2d4-4fc2-b7b8-cf4779a7a38e.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
