### ISSUE TITLE
OHIF: User Preferences (Empty shortcuts list)

### ISSUE THREAD

**Issue by luikaaa27** [OHIF/Viewers#3037]
how can i activate or add new shortcut to activate for example presets for Window/Level? 
![image](https://user-images.githubusercontent.com/42840919/203685595-798988cb-dcbf-41fb-b499-a2b0b065908b.png)
It doesn't seem like i can change something. Unfortunately, this window hasn't an edit mode.

**Comment by Georift** [comment]
Can you share how you've found this page? If you checkout the [demo application](https://viewer.ohif.org/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170125113417.1) there appears to be hotkeys available:

![image](https://user-images.githubusercontent.com/859430/203707812-bb5df337-b85e-4c11-ac30-74068fc5f022.png)

**Comment by luikaaa27** [comment]
> Can you share how you've found this page? If you checkout the [demo application](https://viewer.ohif.org/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170125113417.1) there appears to be hotkeys available:
> 
> ![image](https://user-images.githubusercontent.com/859430/203707812-bb5df337-b85e-4c11-ac30-74068fc5f022.png)

Sorry, I can't share the link, due it is used in commercial. 
But I understand, that this problem is related unconfigured keyboard shortcuts/hotkeys. Have you some guide or smth similar how to activate hotkeys? how it should be written

**Comment by Georift** [comment]
No worries, please check the config file you're providing. Here is an example: https://github.com/OHIF/Viewers/blob/master/platform/viewer/public/config/default.js

How are you providing the config to your version?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
