### ISSUE TITLE
Meaning of error messages is unclear

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#3047]
I do not understand what the error messages below communicate. 

Dataset to reproduce: https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.32722.99.99.108388375584764933411258715618206379998

<img width="257" alt="image" src="https://user-images.githubusercontent.com/313942/204412919-0d1f77da-0008-4c7a-b6b1-cab404c1918e.png">

<img width="346" alt="image" src="https://user-images.githubusercontent.com/313942/204412971-116e4cce-0de7-4cae-ad19-e0cbb1cf48b0.png">

**Comment by GitanjaliChhetri** [comment]
This is due to a reference error at https://github.com/dcmjs-org/dcmjs/blob/ab099e7e53cbc88693a14099ce54de13e744f661/src/adapters/Cornerstone/Segmentation_4X.js#L755, the variable 'i' is not defined.
@fedorov , As you pointed out earlier in the email, the main issue here is a missing slice in the CT series. I don't think we should load the seg dataset in such cases. 
Suggested fix is to throw new Error ('Failed to find the reference image in the source data. Cannot load this segmentation') instead of just logging a warning to console.

**Comment by fedorov** [comment]
I think it still makes sense to show segmentation the way it is shown currently for the slices that are present when one slice is missing. We can discuss at the next coordination meeting.
