### ISSUE TITLE
DICOM-SEG loading is not working

### ISSUE THREAD

**Issue by rodrigobasilio2022** [OHIF/Viewers#3055]
## Bug Report

OHIF V3-stable didn't load dicom-seg segmentations correctly

### Describe the Bug

I have an dicom-seg file with 95 segmentations. When I load it, despite the progress bar indicates OHIF is loading 95 segmentations, it only shows 91.

### What steps can we follow to reproduce the bug?

Just load a study with a dicom-seg with 95 segmentations

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
