### ISSUE TITLE
OHIF v3 did not show individual segmentations if unhide all is activated

### ISSUE THREAD

**Issue by rodrigobasilio2022** [OHIF/Viewers#3056]
## Bug Report

OHIF v3 did not show individual segmentations if unhide all is activated

### Describe the Bug

I want to visualize a single segmentation from a file with 95 segmentations. So I click on hide all segmentation and try to activate a single one, but OHIF didnt allow that.

### What steps can we follow to reproduce the bug?

Load a study with a dicom seg serie, open it, unhide all segmentations and try to show a single segmentation.

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
