### ISSUE TITLE
TMTV mode is selecting the NAC PET image by default

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3057]
As far as I can tell the AC PET is being selected solely on the basis of if it has "corrected" or "uncorrected" in the series description.

As such it's just luck that the PET AC gets picked correctly much of the time (probably a lower series number?)

The user can use drag and drop to fix it but you get the wrong one by default which isn't great and looks awful since it picks SUV units on an image in counts.

Repository URL

https://github.com/OHIF/Viewers/tree/v3-stable

Version number

3.3.0

Build number

0

UHN Version

2.0.0 (11/27/2022, 3:03:57 PM)

Browser

Chrome 107.0.0

OS

Windows 10
Default selection
![image](https://user-images.githubusercontent.com/112980389/205403436-21c24efc-178e-4812-9ce2-7530695c42f3.png)
 
actual PET AC
![image](https://user-images.githubusercontent.com/112980389/205403674-eed20082-0202-4327-b5d1-3aef6acf0e32.png)

log file
[qpmdcv-ldvweb01.uhn.ca-1670021916087.log](https://github.com/OHIF/Viewers/files/10144905/qpmdcv-ldvweb01.uhn.ca-1670021916087.log)

sample image set from TCIA that has this behaviour.
https://fileshare.uhn.ca/download/dc762f06-e347-4c6b-a96c-28bc7ab68c48 password "nations"
Please note that this file upload will expire in 30 days.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
