### ISSUE TITLE
MPR not working in v3 with dicomjson

### ISSUE THREAD

**Issue by Amepa** [OHIF/Viewers#3059]
Good evening team,

I was using MPR on OHIF v2 with dicomjson.
I noticed it is not working on v3.
You can check it using the demo link in the documentation :
https://v3-demo.ohif.org/viewer/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json

Once the demo open, click on the MPR button.
The window will divide in three, but the views will not be loaded.

The below error appear in console : 
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.split("/studies/")[1].split')

![image](https://user-images.githubusercontent.com/12066029/205524079-23d03aea-80eb-4932-8369-86ab47f1b208.png)

Below how it load : 

![image](https://user-images.githubusercontent.com/12066029/205524138-39b9dac2-f5c8-4dfa-abf8-163d772daa6e.png)

Any suggestion or comment would be Welcome.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
