### ISSUE TITLE
Add tools of measurements and annotations in 2D MPR. 

### ISSUE THREAD

**Issue by luikaaa27** [OHIF/Viewers#3074]
> :hand: Many people requests features. Tell us why yours is important to the
> community. How does it add value? Why _this feature_?
> Is your request very specific to your needs? Consider
> [contributing it](https://docs.ohif.org/contributing.html) yourself! Or reach
> out to a community member that offers
> [consulting services](https://docs.ohif.org/help.html#paid--commercial).

## Request

**What feature or change would you like to see made?**

Option to take measurements in 2D MPR view and add annotations.

**Why should we prioritize this feature?**

I've shown OHIF to several radiologists, dentists and they think the missing feature of OHIF is the ability to take measurements when they open the 2D MPR viewer. We have the ability to take measurements as usual.

**Comment by sedghi** [comment]
This is already implemented in the viewer. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
