### ISSUE TITLE
Ohif v3 is not working on chrome (ubuntu)

### ISSUE THREAD

**Issue by narbek-abd** [OHIF/Viewers#3076]
Hi, thanks for awesome project.
I opened demo https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095258.1
and got this error:
![image](https://user-images.githubusercontent.com/59279794/207789843-4a6ec257-8eb9-41a3-b6e0-026414ba950a.png)

Chrome version Version 108.0.5359.98 
Ubuntu version 22

Works on windows. v2 also works

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
