### ISSUE TITLE
OHIF V3 SR data issue

### ISSUE THREAD

**Issue by GeethaPriyaBalaraman** [OHIF/Viewers#3148]
We are using OHIF V3 Stable version with Orthanc data source. When we use measurements and do create report, SR data is saved as separate patient in Orthanc server. Due to this study list shows two entries of same patient and reload of dataset fails.

![image](https://user-images.githubusercontent.com/66363697/217019773-760ecf8f-3c42-4e0e-ae72-866b3232156a.png)

We get below errors:

"More than one SOPClassUID in the same series is not yet supported."
"Multiple Study found for WADO-RS"

Root cause is that the saved SR does not contain information of Patient Quadruple (i.e, Patient Name, Age, ID, Sex is empty). If these attributes are set manually in server, OHIF shows study list correctly.

Also, in OHIF Viewer 4.12.45, even though SR is shown as separate patient in Orthanc, OHIF shows studylist correctly and reload of SR data also has no issues.

How do we get the V3 stable version under Releases in Github. We could not find V3 release version.

**Comment by olivert1969** [comment]
use Orthanc to merge the SR with the original study
or upgrade to Orthanc 1.11.3 (just released) which apparently addresses this
to get v3-stable switch to v3-stable branch in Github

**Comment by GeethaPriyaBalaraman** [comment]
I have tried with Orthanc 1.11.3, but issue is still present.  We are interested in using Modes/Extensions feature of V3. Do you have tentative timeline when this feature would be merged to master branch?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
