### ISSUE TITLE
yarn build:package-all failed in v3-stable

### ISSUE THREAD

**Issue by anarnoli** [OHIF/Viewers#3172]
### yarn build:package-all failed in v3-stable

_When I ran `yarn build:package-all` it failed `error Command failed with exit code 2.`_

### Steps to Reproduce:

1. run `yarn install`
2. run `yarn build:package-all`

### The current behavior

_Command failed_

```
lerna ERR! yarn run build:package exited 2 in '@ohif/extension-dicom-pdf'
lerna WARN complete Waiting for 14 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

![image](https://user-images.githubusercontent.com/54370515/218496125-585602dd-4d72-42db-b9d3-9c2e512b4a2b.png)

### The expected behavior

_It should generate build files_

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
