### ISSUE TITLE
Source data not present when open RTSTRUCT

### ISSUE THREAD

**Issue by zhengdechang1** [OHIF/Viewers#3175]
Why open RTSTRUCT to show that source data does not present 

![image](https://user-images.githubusercontent.com/118711209/218964058-48c5d819-8646-443b-bfa0-4f41ca61d5e3.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
