### ISSUE TITLE
Incorrect default preset for lung window level

### ISSUE THREAD

**Issue by akluiber** [OHIF/Viewers#3177]
### Describe the Bug

The current default preset for the lung window level is 150/-600, resulting in an unusable ultra high contrast rendering. I suspect someone simply forgot a '0' in the default preferences.js, as this should really be 1500/-600. Since this is a per-user/browser setting, it is a hassle to instruct every new user to properly set their lung window preset in the preferences.

### Steps to Reproduce:

1. Load lung CT.
2. Press '2' for lung window preset.

### The current behavior

Current default preset values of 150/-600 results in such a high contrast image render that it is unusable.

<img width="534" alt="150x-600" src="https://user-images.githubusercontent.com/17030450/219115201-868b906a-0a88-4240-808f-486502dfc028.png">

### The expected behavior

Preset value of 1500/-600 would result in proper and interpretable rendering of lung tissue.

<img width="535" alt="1500x-600" src="https://user-images.githubusercontent.com/17030450/219115230-5aa64176-ae23-4cf7-ba50-90b8130ecc60.png">

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
