### ISSUE TITLE
Error: Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by cheyvaert-medexprim** [OHIF/Viewers#3182]
Hello, 
I noticed this in the console (chrome debug tools) when I launch the ohif v3 in a brower (note: I build the app as a npm package and files are served by django)

```
An SSL certificate error occurred when fetching the script.
workbox-window.prod.mjs:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://XXXXXXX/viewer-ohif/') with script ('https://XXXXXXX/viewer-ohif/sw.js'): An SSL certificate error occurred when fetching the script.
```

### Steps to Reproduce:

1. open ohif viewer
2. Look at the webbrowser console.

### The current behavior
It does not seem to impact anything from now but I guess it could impact reactivity later on some computations

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

Please try and re-open if the issue persists
