### ISSUE TITLE
I can't solve MPR by internet OHIF v3-stable 

### ISSUE THREAD

**Issue by AlbertoRequena** [OHIF/Viewers#3184]
Working with Windows 10, Orthanc, OHIF v3-stable the last version, from localhost it works very well, however when I access it over the internet, the mpr button doesn't work well. I have read about the error:"Your page is NOT cross-origin isolated", I modified my php code that calls OHIF by adding statements in the header and it has not been resolved either. Can someone guide me how to solve it, since from https://v3-demo.ohif.org/local I upload the study and it works perfectly.
Thank you very much for your time.

**Comment by hwanython** [comment]
Hi, sir.

I also work on OHIF-v3stable with Orthanc in Window10. 

I success turn on  OHIF-v3stable web view and loading the database in local Orthanc.

But this web page also can not use MRP function..

Do you progress something to do ?

**Comment by sedghi** [comment]
Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

Please try and re-open if the issue persists
