### ISSUE TITLE
Bug: Stack Viewport incorrect initial VOI

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#3190]
Seems like our stack viewport has a wrong initial voi set. 

For instance for this study https://www.dropbox.com/sh/j6mxoutxb4x3moh/AAB69hV6SfvxYj06YsuHlaoza?dl=0

Drag and drop one instance into the https://www.cornerstonejs.org/live-examples/local.html

it works correctly 
![image](https://user-images.githubusercontent.com/7490180/220710656-9b933818-a0bd-466f-b4b6-e79a7ce81c93.png)

But dragging and dropping it into the v3-demo.ohif.org/local (or local server)

![image](https://user-images.githubusercontent.com/7490180/220710790-1160a432-a2ce-4cca-bdf4-083eb32c7fd8.png)

Since it works in cs3d, and not in OHIF, I expect the metadata provider of [OHIF metadata](https://github.com/OHIF/Viewers/blob/v3-stable/platform/core/src/classes/MetadataProvider.js#LL248) for windowlevel and width is different than what cs3d has

**Comment by sedghi** [comment]
It is the same issue in the v2 as well, so definitely the metadata provider of OHIF getting those metadata from instance somehow wrong

![image](https://user-images.githubusercontent.com/7490180/220712677-a27f38d8-d548-43aa-9eff-f48980a388b4.png)

**Comment by sedghi** [comment]
Seems like in the cs3d demos we are adding metadata to the wado rs metadata manager via 

https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/utils/demo/helpers/createImageIdsAndCacheMetaData.js#L61-L64

But OHIF doesn't do that since we use the naturalized instance via dcmjs to store metadata. So we need to see what is happening there

**Comment by heyflynn** [comment]
Hi @sedghi 

I have been testing my own viewer with cornerstone3d using both the old wado image loader 3.3.2 and the new one 4.8.x +

I encountered several instances of this problem when the window level / center values for CT images were an array of different values. metadata was ok but createImage in image loader may be responsible. I never debug the problem beyond a user interface.

I only encountered this with 3.3.2, every version > 4 worked

**Comment by sedghi** [comment]
Thanks @heyflynn , we will look into this, can you be more specific which version worked? You are saying every version of wado loader > 4 works? I'm confused

**Comment by heyflynn** [comment]
yes. every version > 4 this was OK. I created a simple app that loaded old cornerstonejs, new cornerstone3d and the small dicom.ts renderer.

"cornerstone-wado-image-loader": "^3.0.0",
![wado-3](https://user-images.githubusercontent.com/553465/220806580-1a93c609-83a9-4fde-b7ee-3f9c1213a675.png)

"cornerstone-wado-image-loader": "^4.10.0",
![wado-4](https://user-images.githubusercontent.com/553465/220806683-165021c6-cda2-4be2-88f1-8888657f824b.png)

**Comment by Ouwen** [comment]
@sedghi, some dicom metadata stores the initial WW/WL in a different tag (sharedFunctionalGroupsSequence), is the correct initial ww/wl values stored here for the image?

```js
    let center, width;

    try {
      const sharedFunctionalGroupsSequence = dataSet.elements.x52009229;
      const frameVOILUTSequence = sharedFunctionalGroupsSequence.items[0];
      const frameDataset = frameVOILUTSequence.dataSet.elements.x00289132;
      const windowDataset = frameDataset.items[0].dataSet;

      center = getNumberValues(windowDataset, 'x00281050', 1);
      width = getNumberValues(windowDataset, 'x00281051', 1);
    } catch {
      center = getNumberValues(dataSet, 'x00281050', 1);
      width = getNumberValues(dataSet, 'x00281051', 1);
    }
 ```

**Comment by Ouwen** [comment]
@sedghi, some dicom metadata stores the initial WW/WL in a different tag (sharedFunctionalGroupsSequence), is the correct initial ww/wl values stored here for the image?

```js
    let center, width;

    try {
      const sharedFunctionalGroupsSequence = dataSet.elements.x52009229;
      const frameVOILUTSequence = sharedFunctionalGroupsSequence.items[0];
      const frameDataset = frameVOILUTSequence.dataSet.elements.x00289132;
      const windowDataset = frameDataset.items[0].dataSet;

      center = getNumberValues(windowDataset, 'x00281050', 1);
      width = getNumberValues(windowDataset, 'x00281051', 1);
    } catch {
      center = getNumberValues(dataSet, 'x00281050', 1);
      width = getNumberValues(dataSet, 'x00281051', 1);
    }
 ```

**Comment by sedghi** [comment]
`sharedFunctionalGroupsSequence` is for multiframe data, but this is happening even for the regular dicom files. 
@heyflynn I guess you don't have OHIF right? since it works fine inside cs3d, but NOT in OHIF. I expect the problem is the fact that in the cs3d demo we use wadors metadataManager but OHIF uses its own metadata provider which has priority and OHIF metadataProvider is based on naturalized instance of dcmjs

**Comment by heyflynn** [comment]
I don't have OHIF. I downloaded your files and tested them ok on both 3 and 4 of CWIL so I assume they are unrelated issues.

**Comment by IbrahimCSAE** [comment]
@sedghi 

I gave this a look. I'm not sure if it's a bug, but maybe because cornerstone3D is using the WW/WL of the first image in the stack? I also verified dcmjs values and they look correct, so it's not dcmjs.

MR.1.3.12.2.1107.5.2.32.35162.1999123112191238865917962

It has really weird WW/WL and I believe it is at the start of stack, it's WL/WW is 35/99, which matches OHIF

If you drop it into https://www.cornerstonejs.org/live-examples/local.html, you will see the same VOI from OHIF too.

![Screenshot_3](https://user-images.githubusercontent.com/93064150/221353558-28db7679-e52e-48cc-b6f2-216e20a31563.png)

I think this in cornerstone3D is causing the problem since it doesn't update the WL/WW from the metadata for each image, it's always using the first image? (should it be different for each image? [RadiAnt](https://www.radiantviewer.com) does it that way)

https://github.com/cornerstonejs/cornerstone3D-beta/blob/5287ac179ced972f073cf8c2f962e18a63d0875f/packages/core/src/RenderingEngine/StackViewport.ts#L1807

this method called ```this._setPropertiesFromCache();``` sets the WL/WW to the first image always, isn't this supposed to be updated for each imageId? 

I removed it and added this part copied from after the if condition in the original code above ^
```javascript
            const {
              imagePixelModule,
            } = this._getImageDataMetadata(image);

            const { windowCenter, windowWidth, voiLUTFunction } = imagePixelModule;
            let voiRange =
            typeof windowCenter === 'number' && typeof windowWidth === 'number'
              ? windowLevelUtil.toLowHighRange(windowWidth, windowCenter)
              : undefined;

          const isPreScaled =
            this.csImage.isPreScaled || this.csImage.preScale?.scaled;

          if (imagePixelModule.modality === 'PT' && isPreScaled) {
            voiRange = { lower: 0, upper: 5 };
          }

          this.initialVOIRange = voiRange;

          if (this.voiApplied && typeof voiRange === 'undefined') {
            voiRange = this.voiRange;
          }

          if (Object.values(VOILUTFunctionType).indexOf(voiLUTFunction) === -1) {
            this.VOILUTFunction = VOILUTFunctionType.LINEAR;
          } else {
            this.VOILUTFunction = voiLUTFunction;
          }
          this.setProperties({ voiRange });
            return;
```

now OHIF looks like this

![demogif4](https://user-images.githubusercontent.com/93064150/221352092-ddb2f81c-ae04-4573-baa7-27379a39ad20.gif)

which behaves like RadiAnt viewer that I used as a reference. you will notice the WW/WL value change in the viewer overlay.

![GIF 5](https://user-images.githubusercontent.com/93064150/221353582-2ce686be-9926-4cc2-b87b-2ba80c00e664.gif)

this problem is also in the other cornerstone that isn't 3D, so I'm not sure if this really a problem, looks like it's done this way intentionally in cornerstone/cornerstone3D?

If the value is supposed to match the first imageId always then there's nothing wrong with cornerstone3D/cornerstone or OHIF, it's just the first image in the stack looks weird.

**Comment by sedghi** [comment]
@IbrahimCSAE great debugging, I came across the same conclusion yesterday as well. Interesting that you confirmed it now!
We decided to apply a per-slice ww/wl on each image for the stack viewport. and as soon as the user modifies it it becomes global for the stack and later when reset happens we go back to per slice.

**Comment by IbrahimCSAE** [comment]
Great! Happy to help.
