### ISSUE TITLE
Actions taken via hotkey bindings do not update the state of the toolbar

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3200]
### Describe the Bug

Using a hotkey to change the (tool) state of OHIF changes the state, but the toolbar buttons are not updated to reflect that state.

Some examples include zoom tool and cine.

### Steps to Reproduce:

The steps here are for the zoom tool, however similar behaviour can be seen for other tools.
1. Launch OHIF.
2. Press the keyboard shortcut for zoom ('z' is the default).

### The current behavior

Zoom mode is entered however the zoom tool is NOT depicted as selected/active.

https://user-images.githubusercontent.com/109477394/221270034-91136532-36f7-41a1-bd77-a5b32dd51ec5.mp4

### The expected behavior

Zoom mode is entered and the zoom tool displays as selected/active.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by subhasishdash** [comment]
I got the same issue of UI state not getting updated, it has been few months, did you get any workaround or solution for the above problem ?

**Comment by pwespi** [comment]
I have the same issue in version 3.7.0. I would consider this a bug and not a feature request, because it can be very confusing if the active tool button and active tool on the mouse are not the same.

I suspect it has something to do with the `TOOL_BAR_STATE_MODIFIED` that is being triggered when you click on a toolbar button, but it's not triggered when using the hotkeys. Unfortunately I don't know the code well enough to provide a fix.

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
