### ISSUE TITLE
Custom measurements are not rendered

### ISSUE THREAD

**Issue by janaoravcova** [OHIF/Viewers#3221]
### Custom measurements are not rendered

Hi,
I tried to integrate the @ohif/viewer@4.10.0 into React application using the exported function installViewer. Now I would like to add custom measurements to for the study. I tried to use the MeasurementService and call the addOrUpdate method. The window object seemed to register that and the measurement is present in the MeasurementService's measurements list. But **the measurement is not drawn on the frame and it is not in the measurement panel either.** 
Is there any additional initialization needed to achieve the synchronization? 
No error in the console are present, only warning about missing mapping for stack and stackPrefetch definitions:
_Failed to map 'CornerstoneTools@4' measurement for definition stackPrefetch: Cannot read properties of undefined (reading 'toMeasurementSchema')_ 
when I switch between the series in the UI - not sure if this could be an issue. Also, why is the cornerstonetoolsmeasurementadded event published every time I switch the series?

I used this page as a reference for creating the mapper: https://v3-docs.ohif.org/platform/services/data/measurementservice/

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
