### ISSUE TITLE
ERR_NETWORK_CHANGED errors in browser console when loading study over https

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#3231]
I keep getting ERR_NETWORK_CHANGED errors in browser console when loading study over https. It takes even a study of 400-450 instances around 30 minutes to load despite its size being around 150mb and me having a 100mbps connection.

![Screenshot 2023-03-10 180828](https://user-images.githubusercontent.com/5023419/224324994-d3185434-04fd-4c83-9ee9-0344f1268624.png)

And MPR generation looks like this....tons of missing frames
![Screenshot 2023-03-10 180828](https://user-images.githubusercontent.com/5023419/224327379-e09c495d-6f21-4cc5-94f7-6929bcc3acb5.png)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
