### ISSUE TITLE
can not create a report

### ISSUE THREAD

**Issue by JeffreyWW** [OHIF/Viewers#3239]
The branch is v3-stable
I was created a report, after I clicked the "Save" button,  an error is reported, as bellow:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/15065208/224807861-5d6066c9-8a45-4a7b-9759-ee7e7a9966ab.png">

I also can not find the function "getFrameOfReferenceAnnotations"

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
