### ISSUE TITLE
Contrast and Brightness Controls not working at all

### ISSUE THREAD

**Issue by phpKahuna** [OHIF/Viewers#324]
I installed OHIF Viewer from the Master repository and it was updated to Meteor 1.8.0.1. Everything is working as expected, except W/L (Contrast and Brightness) controls. Any suggestions?

**Comment by dannyrb** [comment]
@phpKahuna, are you still experiencing this issue on the latest version? What about in our React branch?

Is it for all DICOMs? Do you have steps you can provide to reproduce the issue? More than happy to reopen this after receiving a verifiable reproduction. This issue is a bit older, so I'll close it until then.
