### ISSUE TITLE
setLayout has a bug, I haven't findOrCreateViewport parameter, setLayout not work.

### ISSUE THREAD

**Issue by webxzy** [OHIF/Viewers#3271]
### Describe the Bug

In modes longitudinal src index.js, I subscribe SERIES_ADDED and setLayout, but not work.

### Steps to Reproduce:

1. First step
2. Second step
3. ...

```js
      const studySub = DicomMetadataStore.subscribe(
        DicomMetadataStore.EVENTS.SERIES_ADDED,
        (data) => {
          const study = DicomMetadataStore.getStudy(data.StudyInstanceUID);
          const layoutSub = HangingProtocolService.subscribe(
            HangingProtocolService.EVENTS.NEW_LAYOUT,
            () => {
              if (['CT', 'MR'].includes(study.ModalitiesInStudy[0])) {
                // 实现有bug
                viewportGridService.setLayout({ numCols: 2, numRows: 2, findOrCreateViewport: () => {} });
              }
              layoutSub.unsubscribe();
            }
          );
          studySub.unsubscribe();
        }
      );
```

### The current behavior

_A clear and concise description of what happens instead of the expected
behavior._

### The expected behavior

_A clear and concise description of what you expected to happen._

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
