### ISSUE TITLE
Bug: NPM install returns "unable to resolve dependency tree"

### ISSUE THREAD

**Issue by Antonio-Riccelli** [OHIF/Viewers#3274]
Hi. I'm trying to add [Ohif-viewer](https://www.npmjs.com/package/@ohif/viewer) to my existing React project. When I try to install it via NPM I get the following error: 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/39813213/226972068-52c0e1f4-1390-40a0-8b9a-f9f407f8bddf.png">

React version is 18.2.0.
NPM version 9.2.0

Is anybody experiencing this or aware of a workaround? 

I'm aware I could use the ```--force``` or ```--legacy-peer-deps``` flags to try and bypass this, but they both generate a very high number of red and yellow warnings. 

Thanks.

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by SaiChandra2896** [comment]
I am getting the same error now any solutions ??

**Comment by Antonio-Riccelli** [comment]
> I am getting the same error now any solutions ??

@SaiChandra2896  I couldn't find any, unfortunately.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
