### ISSUE TITLE
The length annotation behaves wierdly

### ISSUE THREAD

**Issue by may-jhao** [OHIF/Viewers#3284]
### Describe the Bug

_A clear and concise description of what the bug is._
when i add a length annotation:
it has only one length number as below: 57.14
![image](https://user-images.githubusercontent.com/94670917/228209311-1ea2ed4c-4b36-49ad-8ff1-6aaea5920352.png)
but after refresh the page, there are two lines overlapped as below: 57.1 and 57.14

![image](https://user-images.githubusercontent.com/94670917/228209549-3957f862-e547-443d-8e72-e2d30513f940.png)

i use azure health data service to retrieve the data 
### Steps to Reproduce:

1. add length annotation
2. refresh the page

```js
Please use code blocks to show formatted errors or code snippets
```

### The current behavior

show as picture:
![image](https://user-images.githubusercontent.com/94670917/228209549-3957f862-e547-443d-8e72-e2d30513f940.png)
### The expected behavior

show as picture:
![image](https://user-images.githubusercontent.com/94670917/228209311-1ea2ed4c-4b36-49ad-8ff1-6aaea5920352.png)

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
