### ISSUE TITLE
Error loading Image 

### ISSUE THREAD

**Issue by kunjesh1** [OHIF/Viewers#3288]
### Steps to Reproduce:

1. Go to the below links 
2. http://viewer.ohif.org/local or https://v3-demo.ohif.org/local
3. Upload the attached anonymised scan 

Old version of cornerstone WADO Image loader
```js
error: "offset is out of bounds"
```
New version of cornerstone WADO image loader
```js
a2659d938e7b5e69ece3.wasm:0x1e3f Uncaught (in promise) RuntimeError: null function or function signature mismatch
    at a2659d938e7b5e69ece3.wasm:0x1e3f
    at a2659d938e7b5e69ece3.wasm:0x231a
    at a2659d938e7b5e69ece3.wasm:0x8499
    at a2659d938e7b5e69ece3.wasm:0xa468
    at a2659d938e7b5e69ece3.wasm:0xa246
    at a2659d938e7b5e69ece3.wasm:0x10466
    at a2659d938e7b5e69ece3.wasm:0x1727
    at a2659d938e7b5e69ece3.wasm:0x132c
    at a2659d938e7b5e69ece3.wasm:0x1272
    at a2659d938e7b5e69ece3.wasm:0x2e255
```

### The expected behavior

It should correctly decode the image and render it in the viewer
[Anonymised.zip](https://github.com/OHIF/Viewers/files/11100798/Anonymised.zip)

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by ahan** [comment]
@sedghi Hi, Sedghi, it's happen again, with error message "Uncaught (in promise) Error: Failed to transform frame: RuntimeError: null function or function signature mismatch"

link: https://viewer-dev.ohif.org/microscopy?StudyInstanceUIDs=2.25.103659964951665749659160840573802789777

![image](https://github.com/OHIF/Viewers/assets/654880/aab2ee6a-9d23-4d7b-87dd-4af20c62b5bc)

**Comment by sedghi** [comment]
@ahan You issue is separate I guess, can you open another issue to track?

**Comment by ahan** [comment]
Sure, #3865
