### ISSUE TITLE
Studylist: pagination doesn't work in DIMSE case

### ISSUE THREAD

**Issue by lam0620** [OHIF/Viewers#330]
Selected rowperpage is 25 but always display all records (> 25 records)
Checking the latest code, it seem the pagination is just fixed for QIDO(dicomWeb) case only!

Please reported!

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

@lam0620, this is something that I would gladly accept a small high quality PR for if it's made within the next few months; however, I don't believe the core team will have the time necessary to address this issue. DIMSE is not currently supported in v2 of the OHIF Viewer.
