### ISSUE TITLE
MPR keep showing gray in viewports until all images are loaded

### ISSUE THREAD

**Issue by tuvm** [OHIF/Viewers#3301]
### Describe the Bug

MPR keep showing gray in viewports until all images are loaded

### Steps to Reproduce:

1. Try to open a series with large number of slices (about 1000).
2. Then open the MPR immediately before all instances of series are loaded.

The 3 viewport display gray image until all image are loaded.
This might be different with cornerstone3D example (crossHairs example) https://www.cornerstonejs.org/live-examples/crosshairs
Because it render the images at the time they are loaded.
I am not sure it's behavior of the image loading strategy or a bug of rendering.

### The current behavior

The all 3 viewport display gray image until all image are loaded

### The expected behavior

![image](https://user-images.githubusercontent.com/19379659/229459874-541ed332-83cb-428d-b6f1-7ca310430d39.png)

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Can you check the latest build and see if this still happens?



Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
