### ISSUE TITLE
Why Display dicom file so slowly?

### ISSUE THREAD

**Issue by wangning08115** [OHIF/Viewers#3317]
1. I use wadiourl Mode load dcm file with JPEG2000Lossy Transfer Syntax.
2. The JPEG2000Lossy dicom file is small,  Fast transmission speed.
3. But i and when dicom file load to Web browser client.  
Dicom file transfer from server to web browser client is fast, but Display dicom image to HTML ui element is so slowly.

Dicom file transfer from server to web browser client need 0.2 second, but  Display dicom image to HTML need 3 seconds.
How to Display dicom image to HTML faster?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. I am confident that this issue has been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
