### ISSUE TITLE
Array buffer allocation failed when updateImage

### ISSUE THREAD

**Issue by wangning08115** [OHIF/Viewers#3321]
### Describe the Bug

Viewers throw below error:
Uncaught (in promise) Error: updateImage: image has not been loaded yet at object.t.default [as updatermage' (app.bundle.js:2:693929)
16:17:17.481 task decodeTask failed - Array buffer allocation failed at blob:https://dicomcloud-dev.migucare.com/28cc8174-eb5f-456b-8325-dc587e67716b:2

### Steps to Reproduce:
1. In wadiouri Mode. 
2. Views load an dcm format is 【JPEG2000Lossy "1.2.840.10008.1.2.4.91"】
3. Open then viewer on mobile app inside WebView. 
4. Some mobile throw the error

```js
Please use code blocks to show formatted errors or code snippets
```

### The expected behavior

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
