### ISSUE TITLE
[Feature Request] Mechanism to communicate to the users inconsistencies within a single series

### ISSUE THREAD

**Issue by igoroctaviano** [OHIF/Viewers#3360]
### Request
Alert icon (lower right corner under the thumbnail in v2) indicating series that have geometry issues, and explanation of what those are, is missing; e.g., see series 2 for this study

### Example series that motivate some discussion what should be done:
*  https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.8162.4009.498881901170332065029863238265 - first instance is a localizer
* https://idc-sandbox-000.firebaseapp.com/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.8162.4009.498881901170332065029863238265?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.8162.4009.329297441360267384643622758743-  one series has 2 subvolumes with different slice and pixel spacing

At the moment, OHIF Viewer does not have any indication about those inconsistencies, and presents the slices as if they belong to a single continuous volume.

![image](https://user-images.githubusercontent.com/313942/106286951-39970a80-6214-11eb-893a-d83ccc7272d5.png)

### Example in v2
![image](https://user-images.githubusercontent.com/313942/113185008-e6e1cb00-9223-11eb-9c4f-89cd360af456.png)
![image](https://user-images.githubusercontent.com/313942/113185067-fc56f500-9223-11eb-8c3d-c028b3557612.png)

**Comment by fedorov** [comment]
Per discussion today, @jlulloaa will investigate what, if any, are the geometry checks implemented in v3, where in the code they are located, how can they be extended, etc ...

Related to this, here is an interesting edge case from IDC where frames within the same series do not have consistent origin: https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.7009.9004.229337801792248347333415175865?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.7009.9004.172787163177205374234578117444

From the IDC perspective, it would also be highly desirable to be able to see image series that have geometry issues in 2D. If this is not possible, we will be in a situation where (potentially) many images from IDC that were viewable in v2 will no longer be viewable in v3!

**Comment by jlulloaa** [comment]
> Per discussion today, @jlulloaa will investigate what, if any, are the geometry checks implemented in v3, where in the code they are located, how can they be extended, etc ...
> 
> Related to this, here is an interesting edge case from IDC where frames within the same series do not have consistent origin: https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.7009.9004.229337801792248347333415175865?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.7009.9004.172787163177205374234578117444
> 
> From the IDC perspective, it would also be highly desirable to be able to see image series that have geometry issues in 2D. If this is not possible, we will be in a situation where (potentially) many images from IDC that were viewable in v2 will no longer be viewable in v3!

From a review to this particular dataset, it is loaded ok in v3 (see images below). Although there is no alert about the spacing issue, it is calculated in the same way as in v2 ([platform/core/src/utils/isDisplaySetReconstructable.js](https://github.com/OHIF/Viewers/blob/v3-stable/platform/core/src/utils/isDisplaySetReconstructable.js)) and therefore also interprets the shift as missing frames. This information could be transferred as an alert displayed in the thumbnail (next steps)

v2 - display ok and warning about spacing issue (interpreted as missing frames because the distance shift respect to the average spacing in the series)
<img width="960" alt="v2-display-ok-warning-display" src="https://github.com/OHIF/Viewers/assets/84105116/4132d1c4-b877-4545-a338-06ed536557a9">

v3 - display ok, but no warning about spacing issue
<img width="960" alt="v3-display-ok-no-warning-display" src="https://github.com/OHIF/Viewers/assets/84105116/211296a9-ff61-4470-aa25-88a3b59603de">

**Comment by jlulloaa** [comment]
Based on [the sample data](https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.7009.9004.229337801792248347333415175865?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.7009.9004.172787163177205374234578117444), translated v2 alert's logic into v3. From the preliminary results (see image below) it will be possible to notify spacing issues.

As seen in this particular dataset, the root of the issue is not missing frames, but shifting in image position halfway through the series. However, the way the code works out the spacing issue, is equivalent to missing frames. To reflect that, I suggest indicating it in the warning message.

![v3-warning-proposal](https://github.com/OHIF/Viewers/assets/84105116/05cd5525-36df-4acb-a3e0-6c55b6361d37)

**Comment by fedorov** [comment]
Few other criteria that one might consider while reporting inconsistent geometry of the series:

* do not contain LOCALIZER in ImageType
* all instances have identical values for ImageOrientationPatient (converted to string for the purposes of comparison)
* have number of instances in the series equal to the number of distinct values of ImagePositionPatient attribute (converted to string for the purposes of comparison)
* all instances have identical values of PixelSpacing (converted to string for the purposes of comparison)
* with sliceIntervalDifference defined as the difference between the values of the 3rd component of ImagePositionPatient, after sorting all instances by that third component, having the difference between the largest and smallest values of sliceIntervalDifference less than 0.01
* have consistent origin

**Comment by fedorov** [comment]
Once #3361 is done, we should check the actual behavior for some of the situations above, and then decide how to proceed.

**Comment by igoroctaviano** [comment]
> Once #3361 is done, we should check the actual behavior for some of the situations above, and then decide how to proceed.

Feel free to use https://ohif-v3.web.app/ which has support for gcp URLs while its not merged to v3 master.

**Comment by jlulloaa** [comment]
> Few other criteria that one might consider while reporting inconsistent geometry of the series:
> 
> * do not contain LOCALIZER in ImageType
> * all instances have identical values for ImageOrientationPatient (converted to string for the purposes of comparison)
> * have number of instances in the series equal to the number of distinct values of ImagePositionPatient attribute (converted to string for the purposes of comparison)
> * all instances have identical values of PixelSpacing (converted to string for the purposes of comparison)
> * with sliceIntervalDifference defined as the difference between the values of the 3rd component of ImagePositionPatient, after sorting all instances by that third component, having the difference between the largest and smallest values of sliceIntervalDifference less than 0.01
> * have consistent origin

Below there are some example data that may be relevant for the geometry checks: 

The lack of LOCALIZER in the ImageType doesn’t seem to be a problem to load and display the data (see for example: https://ohif-v3.web.app/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.4334.1501.250426352468384929420253109030)

However, if a localiser scan is embedded as an additional frame within a series (in fact, any frame with a different ImageOrientationPatient value within a series), will render the series as no-reconstructable as an MPR volume e.g. https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.99.1071.16051849653578423672035750287473?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.99.1071.28979067023783953913791585130339). 

In v2 there is an alert in the thumbnail when loading the data, and the MPR tab is not available. While in v3, an error message is issued when attempted to reconstruct the data with the MPR extension. 

The following example contain series with duplicated frames, which causes a replicated ImagePositionPatient value within the series. The viewer interprets this as a 4D dataset, therefore cannot be reconstructed as an MPR volume: (Series 2, instance 58) https://ohif-v3.web.app/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs?StudyInstanceUIDs=1.2.840.113654.2.55.69925400202012637024302712643359784845

On the other hand, the following examples contain multiple acquisitions in a single series, but they don’t have frames with different ImageOrientationPatient values, don’t have identical ImagePositionPatient values, PixelSpacing nor identical SliceLocation values, so can load as MPR but incorrectly reconstructed (even though AcquisitionNumber changes within the series): https://viewer.imaging.datacommons.cancer.gov/viewer/1.2.840.113654.2.55.268978779666003033721491501200337886584?seriesInstanceUID=1.2.840.113654.2.55.242546250902028221188803440014023166417 (v2), https://ohif-v3.web.app/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs?StudyInstanceUIDs=1.2.840.113654.2.55.268978779666003033721491501200337886584 (v3, series 3)

https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.3098.5025.250976478345829511981090188621?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.3098.5025.295346938711185345226780058962 (v2)
https://ohif-v3.web.app/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.3098.5025.250976478345829511981090188621 (v3, series 5)

Digital Breast Tomosynthesis has no volumetric location information (i.e. no ImagePositionPatient, ImageOrientationPatient and PixelSpacing attributes), although in v2 is loaded as a single series with multiple instances (i.e. multi-slice), in v3 it loads as separate series:
v2: 
https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.2135.6389.898686400784496694508421540887 
https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.2135.6389.235710263043919072573939162133 


v3:
https://ohif-v3.web.app/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.2135.6389.235710263043919072573939162133  
https://ohif-v3.web.app/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.2135.6389.898686400784496694508421540887  

When looking at PixelSpacing issues, usually they are caused because of multiple acquisitions in a single series, so not only that attribute is not identical, but also ImagePositionPatient is not consistent, see e.g. 
https://viewer.imaging.datacommons.cancer.gov/viewer/1.2.840.113654.2.55.268978779666003033721491501200337886584?seriesInstanceUID=1.2.840.113654.2.55.242546250902028221188803440014023166417 (v2), https://ohif-v3.web.app/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.99.1071.55696427943949105811475330286060 (v3, series 2)

When searching for data slice interval difference less than 0.01, most of the data were MIP, which were displayed correctly in the viewer e.g.
https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.7009.2406.131628405171680429117301556825?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.7009.2406.213415338691851733957144596814 (v2), 

https://ohif-v3.web.app/projects/:project/locations/:location/datasets/:dataset/dicomStores/:dicomStore/study/:StudyInstanceUIDs?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2406.131628405171680429117301556825 (v3, series 2003)

@fedorov, @igoroctaviano

**Comment by fedorov** [comment]
Looking at a sample in v3, there is a reset of w/l while scrolling, see series 601 in https://ohif-v3.web.app/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.99.1071.16051849653578423672035750287473.

**Comment by james-hanks** [comment]
#3499 Design applied to PR

**Comment by igoroctaviano** [comment]
Assigned to @rodrigobasilio2022. 
@rodrigobasilio2022 please add progress updates here.

**Comment by rodrigobasilio2022** [comment]
The PR associated with this issue is merged, so @fedorov just need your final test to close this issue

**Comment by igoroctaviano** [comment]
Done!
