### ISSUE TITLE
Demo viewer failing to load in Safari

### ISSUE THREAD

**Issue by hypertelia** [OHIF/Viewers#341]
The demo viewer https://viewer.ohif.org isn't working using Safari 12.0.3. 

Steps to recreate:
- From the study list, double click a case.
- View starts to load then browser's 'webpage was reloaded because problem occurred' message is shown.
- Viewer then shows, but displays `Error: Error: request failed` message.

Working as expected in Chrome.

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

I don't have an iOS device to verify this issue, but if it's still happening on the Safarai 11.x or higher and a relatively recent OS version, please feel free to message here and I'll take a harder look at this issue.
