### ISSUE TITLE
[Bug] SEG/RTSTRUCT changes W/L after loading 

### ISSUE THREAD

**Issue by 03shek** [OHIF/Viewers#3410]
### Describe the Bug

W/L changes after loading a SEG

### Steps to Reproduce

1. Open a study on OHIFv3 demo: https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046

2. Note the auto W/L=95/35
![image](https://github.com/OHIF/Viewers/assets/115667958/d07392ab-6867-43c5-b0de-dee0d43aa9b9)

3. Drag the SEG into the viewport

4. Previous W/L has been undone to become W/L=689/315
![image](https://github.com/OHIF/Viewers/assets/115667958/03daf45b-019c-44a3-ba1b-f0c8c92cfe08)

5. Open a study on OHIFv3 demo: https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.3671.4754.298665348758363466150039312520

6. Note the auto W/L in each viewport: A=1048/524; B=3644/1822; C=173/86; D=2400/1300.
![image](https://github.com/OHIF/Viewers/assets/115667958/6996b2d9-9e11-4531-8b9b-1e358c4afc33)

7. Drag the T2 Weighted Axial SEG into viewport A

8. Previous W/L for viewports A and C have been undone.
![image](https://github.com/OHIF/Viewers/assets/115667958/5b7de195-bdeb-4f99-aee2-ccbceeef5bfe)

### The current behavior

W/L changes after loading a SEG

### The expected behavior

W/L should not change after loading a SEG

### OS

Windows 10

### Node version

16.14.0

### Browser

Chrome 111.0.0

**Comment by sedghi** [comment]
I believe this is by design. At first (before loading the SEG or RT) the viewports are StackViewport and in Stack settings we apply the per-image windowlevel, in case of the Brain MR 95/35, and after the SEG is loaded a volume viewport is mounted (since we have 3D segmentations), and for the window level the full volume range is used for calculation of the window level.

**Comment by sedghi** [comment]
actually seems like the window level for the volume viewport is picked from the window level of the middle image in stack viewport. 



![Image](https://github.com/OHIF/Viewers/assets/7490180/fbd07e51-1b89-4419-af60-868fd0562ed2)

I think it should use the range, let me look deeper

**Comment by sedghi** [comment]
Ok so here is what happens 

We can't really do a range on full volume since we don't have full scalarData to get the min and max, so we are limited to grabbing the range from the middle slice.

0. We can't carry over the stack viewport current slice window level to the volume since as you can see in [some](http://localhost:3000/viewer?StudyInstanceUIDs=1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046) of our examples each slice can have different window level

There are two things that can/should make this better 

1. If the user modifies the window level, we assume that is what user wants so we right now carry it over to the volume viewport (with SEG) with our StateSyncService
2. If the user specifies a window level in hanging protocol it should prioritize that

**Comment by sedghi** [comment]
Though there was an issue for PT which is solved after this https://github.com/cornerstonejs/cornerstone3D/pull/676/files

**Comment by 03shek** [comment]
Thanks @sedghi . Yes I believe #1 of the two recommendations you listed above would be more intuitive. #2 would be a workaround if the W/L can't be carried over to the volume viewport.

**Comment by sedghi** [comment]
Number one is already implemented

**Comment by 03shek** [comment]
Thanks for clarifying. Sorry, for the present implementation of number one on demo, it's only keeping the modified W/L for the viewport that has the SEG loaded, and not any others I had opened. Is it possible to extend the keeping of W/L for the other viewports as well?

**Comment by sedghi** [comment]
Unfortunatelly I don't follow what you are saying, the state sync bw stack and volume viewport is already implemented in master branch you can see here

[OHIF-Viewer.webm](https://github.com/OHIF/Viewers/assets/7490180/453b7fcd-841d-41a3-ae56-10319710c0ed)

**Comment by 03shek** [comment]
I'm working with the study with multiple series without entering MPR: https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1706.8374.643249677828306008300337414785

So I have toggled the W/L for each viewport.
![image](https://github.com/OHIF/Viewers/assets/115667958/6e2edd41-e3f4-4e45-bf03-9aaab0617340)

And then as soon as I load the SEG into Viewport C (since series 5 is the series the SEG was drawn on), the W/L for viewport C has been kept (like you said), but viewports A and B have defaulted again. 
![image](https://github.com/OHIF/Viewers/assets/115667958/c6e8db5e-96df-43af-9949-58a90ab14129)

Viewports A and B should be kept as the user had modified them

**Comment by sedghi** [comment]
I see now what you mean, ok let me investigate

**Comment by james-hanks** [comment]
PR #3560
