### ISSUE TITLE
[Bug] ohif viewer 60003000 error

### ISSUE THREAD

**Issue by AhroniCsM** [OHIF/Viewers#3467]
### Describe the Bug

![image](https://github.com/OHIF/Viewers/assets/104092060/a4cd81bf-1d8d-495d-bbc0-4910777d42f4)

I am using Kubernetes to run OHIF Viewer which connects to Orthanc PACS. However, I am encountering a black screen on some of the studies I am uploading. The error message I see in developer mode is 60003000. I am not sure what to do, but it is important to note that the same studies work for other viewers.

### Steps to Reproduce

I Install ohif/viewer/v4.12.51.21579

### The current behavior

black screen

### The expected behavior

display the study

### OS

Mac OS

### Node version

v1.21.14+k3s1

### Browser

Chrome

**Comment by daker** [comment]
probably you are trying to load an http url from an https url

**Comment by sedghi** [comment]
Can you check the latest master?
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing
