### ISSUE TITLE
reporting feature 

### ISSUE THREAD

**Issue by alaradi2006** [OHIF/Viewers#347]
can we add reporting feature like diagnostic report to image study

**Comment by dannyrb** [comment]
Hi, @alaradi2006.

More than happy to hear your thoughts on what an implementation of this would look like. It's likely I would point you toward creating an extension, or ask how we can make it easier to extend the app for your use case. This issue is a little old, so I'm going to close it for now. Happy to re-open it if we have more info to go over/discuss.

**Comment by randikabanura** [comment]
Is there any way to save a report to a image study?
