### ISSUE TITLE
I can’t to see the api call through inspector in google dev tool.

### ISSUE THREAD

**Issue by tanadun** [OHIF/Viewers#352]
Hi, i'm new to OHIF viewer. I have to tried your excellent demo and then i open the inspector to see how to api call in the network tab, I can see it. But when I try to install on my localhost using Orthanc without Docker as server. Why I can’t to see the api call through inspector but everything is working as well.
My environment
-	Windows 10.
-	Using Orthance without docker as server.

**these illustration of demo version on [http://ohif.org/](http://ohif.org/)**
_**Header tab**_
<img width="949" alt="demo version request" src="https://user-images.githubusercontent.com/47741545/52953329-c050d500-33b9-11e9-8e2e-269300adb950.png">

_**Preview tab**_
<img width="947" alt="demo version response" src="https://user-images.githubusercontent.com/47741545/52953334-c34bc580-33b9-11e9-91a3-adbc076dafe3.png">

**these illustration of my localhost**
_**Header tab**_
<img width="725" alt="local version request" src="https://user-images.githubusercontent.com/47741545/52953392-ebd3bf80-33b9-11e9-8355-2839ae7a5bbe.png">

_**Preview tab**_
<img width="614" alt="local version response" src="https://user-images.githubusercontent.com/47741545/52953398-f1310a00-33b9-11e9-8511-1ed85a981b89.png">

**Comment by swederik** [comment]
The demo page makes the requests from the client webpage itself, but by default the Meteor version included a server-side proxy which makes any requests to your DICOMWeb server. We did this because too many people complained about CORS issues.

You can add the requestFromBrowser: true flag to make the requests from the client (see https://github.com/OHIF/Viewers/blob/53cd12a16a8d534d922df91a170682255019d123/StandaloneViewer/StandaloneViewer/public/DICOMCloud_public.json#L13)

If you do not have CORS enabled on your server, you will see errors. The only way around this is to enable CORS by using a proxy in front of your DICOMWeb server.

**Comment by tanadun** [comment]
@swederik  Thanks for clear answer. 

The **requestFromBrowser** flag is **true** already by default after installed. 
To ensure i open viewer and see inspector again and from your great answer i tried filter only **WS**  in-sub tab then i noticed **websocket** request which is good, but I'm still wondering why don't like on demo.
_The illustration as below_
<img width="960" alt="socket tab" src="https://user-images.githubusercontent.com/47741545/53067010-e1720c80-3504-11e9-96cd-301ee5077845.png">

And another question i want to know to ensure, this repo part of **frontend** built from what framework? I understand that all created from the **Vue.js**

**Comment by tanadun** [comment]
@swederik As from my another question.

I've tried the explore more and found using **blaze js.**
Can you tell me why you choose to use blaze instead of a to another, such as **Vue JS** or **Angular**. I just wanted to know your opinion on it.

**Comment by swederik** [comment]
We get this question a lot (https://docs.ohif.org/faq/technical.html#why-is-your-framework-built-with-meteor). Vue did not exist when we started, and Angular has changed dramatically since then.

We are in the process of migrating to a React application, and would welcome any help. See https://github.com/OHIF/Viewers/pull/321

**Comment by tanadun** [comment]
@swederik 
I got it. Thank you very much for the excellent repository and great response.
