### ISSUE TITLE
How do you save a hanging protocol?

### ISSUE THREAD

**Issue by ProofOC** [OHIF/Viewers#353]
Hi,

First, thank you for all your great work on this project.  

I have built OHIFViewer (full thing, not the standalone viewer) according to the documentation and have it working with a local Orthanc via DICOMweb.  I'm able to load studies and see images successfully.  

I cannot, however, figure out how to create/save (and then later apply) a hanging protocol.  I assume this is the functionality I need if I want to essentially "bookmark" the layout of series/images for a particular study and quickly return to that state later.  I see there is a ohif-hanging-protocol package and a (blank) area in the documentation related to hanging protocols, but I do not see anything obvious exposed in the viewer.  Can anyone tell me which buttons to click?  Or am I misunderstanding this feature?

Thanks for your help!

**Comment by swederik** [comment]
We used to have a UI for editing / saving hanging protocols, but we removed it because it wasn't really being used enough and it didn't feel worthwhile to maintain it.

We were adding it into the UI here: https://github.com/OHIF/Viewers/blob/master/OHIFViewer/client/components/flexboxLayout/flexboxLayout.html#L10

using the protocolEditor template (https://github.com/OHIF/Viewers/blob/master/Packages/ohif-hanging-protocols/client/components/protocolEditor/protocolEditor.html#L1).

You might be able to add it back it, but I can't promise it will work automatically.

We were saving HPs to MongoDB by default. I think now we are just pre-populating a few of them in the client. You can check here for how to configure a protocolstore: https://github.com/OHIF/Viewers/tree/master/Packages/ohif-hanging-protocols/client/protocolStore

**Comment by ProofOC** [comment]
Understood, thank you for the references!
