### ISSUE TITLE
[Feature Request] OHIF should support US Region Calibration - Sequence Of Ultra Sound Regions (0018,6011)

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3721]
### What feature or change would you like to see made?

Changes to make include...

- parsing each region
- when the length tool is applied, the region of each end point should be looked up and the appropriate measurement calculated and units displayed

### Why should we prioritize this feature?

By supporting this, measurements on ultrasounds will be calibrated properly and the correct units will be displayed.

**Comment by james-hanks** [comment]
@sedghi to reach out during office hours/post to request ultrasound users for more data to help support use case

**Comment by beavermml** [comment]
is there an update on this? its weird that OHIF viewer display correctly the measurement (mm) when using dicomlocal but when the same file is being used by dicomjson, it returned back to pixels

**Comment by sedghi** [comment]
@beavermml Is your data ultrasound? have you read this? https://docs.ohif.org/faq#what-are-the-list-of-required-metadata-for-the-ohif-viewer-to-work

**Comment by sedghi** [comment]
Based on our interviews with users, here is our plan





Based on different types that (https://dicom.innolitics.com/ciods/us-image/us-region-calibration/00186011/00186014) we will target for now two types, the Tissue and Velocity type since they are the most common types. 

##  Region Data Type Tissue

1. the calibrations will get added to handle correct scaling for each region if the full annotation lies within the same region, and the unit will get properly calculated (mm)

![image](https://github.com/OHIF/Viewers/assets/7490180/5b0003a0-7efa-432a-ad9b-709d7c4c94f8)

2. If there are multiple regions and the measurement crosses the region it should be identified and gives pixel measurement


## Region Data Type Velocity

![image](https://github.com/OHIF/Viewers/assets/7490180/7cd9008e-a268-4baf-b4a7-eef554cddee9)

The probe tool will get augmented to be able to give the `y` axis coordinate on the region based on the locations and baseline

Another tool will get implemented (USRegionClickTool) that has two modes, vertical or horizontal which requires two clicks and give either horizontal or vertical measurements of the unit (often time)

**Comment by james-hanks** [comment]
Need to add ultrasound bidirectional tool to More Tools menu

**Comment by james-hanks** [comment]
See icon in #3819
