### ISSUE TITLE
No Plugin to render images 

### ISSUE THREAD

**Issue by atony88** [OHIF/Viewers#373]
I am trying to use the react project components.But I am not able to render the DICOM files as there is no `PLUGIN` coming from `ohif` so the `availablePlugins` list is empty and if I set the `defaultViewportPlugin`, it just renders a black screen.

I was wondering if I need any specific configurations for the plugin.
Thanks.

**Comment by dannyrb** [comment]
@atony88 are you still having this issue with the latest version of the `react` branch? There are some rough docs on `extensions` and `modules` currently in Draft PR: https://deploy-preview-393--ohif.netlify.com/advanced/extensions.html

**Comment by dannyrb** [comment]
This issue is a little stale, so I'm going to close it for now. Please feel free to start up the conversation again ^_^

For what it's worth, we've recently revamped all of our docs for version 2. I intend to expand on our plugin/extensions documentation further over the next 2-months as we refine and improve that functionality as part of our ongoing partnership with key integrators 👍
