### ISSUE TITLE
[Feature Request] When creating a new segmentation in [Segmentation Mode] there is no way to tell which series is being segmented

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3790]
### What feature or change would you like to see made?

When a user opens any study (with more than one series) in [Segmentation Mode] and adds a new segmentation, that segmentation will be based upon one series.  Many series may share that Frame of Reference and it will display on all of those, however, the segmentation is linked directly to only 1.  

It appears whichever panel is selected when the "New Segmentation" is clicked will become the reference image for the segmentation.  When saving the DICOM SEG back to PACS and then loading it in basic mode it will pull up that reference image set.

In this example I made the hair on CTAC (Top left), eyes on CTSTD (top right), Nose on AC256 (bottom left) and Mouth  on NAC (bottom right)

![image](https://github.com/OHIF/Viewers/assets/112980389/902d7e28-c321-42d8-bfac-c672b1b65959)

The issue is there is no way to know which segmentation is linked to what series when segmenting in segmentation mode.

Additionally All the Segment 1's seem to be linked by colour.  If I change it for one Segmentation it changes for all.

![image](https://github.com/OHIF/Viewers/assets/112980389/a914ea68-e1fe-46b5-a60d-569d23cc8139)

Perhaps a better example would be in a 4D CT.   A user would want a different segmentation on each breathing phase.  Right now the only way I have any idea which is which is by making sure I have the right one selected when I click new segmentation and then relabelling them.

![image](https://github.com/OHIF/Viewers/assets/112980389/152f6a63-a6c0-4fc1-adc2-f3d1f7fd6039)

Somewhere it should really tell you 
1) Which series is this segmentation  linked to and 
2) Selecting a Segment should localize to the segment and highlight the correct panel.

![image](https://github.com/OHIF/Viewers/assets/112980389/818bfc46-2850-4030-89be-8f660759dd70)

### Why should we prioritize this feature?

Right now this feature works okay with a couple series and users who think to label their segmentations.  But when you get to larger series where a user wants to segment on one as opposed to another it's going to get very confusing if the user doesn't know which series a segmentation is linked to.

**Comment by sedghi** [comment]
I think it makes sense

**Comment by JennyLeePMH** [comment]
Hi all,

I hope to make things easier by summarizing the requirements of this issue.  These requirements would applies to both basic and segmentation mode.

On the segmentation panel, for each dicom segmentation 
- For each segment, we should indicate what is the primary series it was originally contoured.  We should follow the same display format as annotation.  
- When user clicks on a segment, the viewport of the primary series should be highlighted and navigate to the segment.    

Say, Segmentation 1 has Segment 1, and Segmentation 2 has Segment 1.  Currently, changing the colour of (Segmentation 1, Segment 1) also changes the colour of (Segmentation 2 Segment 1).  This should not happen.

On the viewport, 
- Say segment A is contoured on series A.  Then, the segment A should displayed with **solid** boundary line on series A.  
- For any series B in the study sharing the same FoR as series A, the segment A should be displayed with **dotted** boundary line of the same colour.  This gives a clear meaning that the segment can be visualized on series B because it shares the same physical space; but it was not where it was contoured.  This is also what Raystation does.

**Comment by james-hanks** [comment]
We will discuss during our design review and provide update design once we have decided how to approach

**Comment by fedorov** [comment]
I think this is related to this issue: https://github.com/OHIF/Viewers/issues/3421

**Comment by sedghi** [comment]
This is the design 

![Uploading CleanShot 2024-02-21 at 13.40.28.png…]()
