### ISSUE TITLE
[Bug] The start date and end date cannot be set on the same day on the calendar on the study list screen.

### ISSUE THREAD

**Issue by VetsImaging** [OHIF/Viewers#3870]
### Describe the Bug

Now, I am using v3.7.0 (release) on my local Windows11.
On the study list screen, the start date and end date cannot be set on the same day on the calendar.
We need to choose 2 days at least, although we want to choose only 1 day.
If we click "Today" button, we can choose 1 day, but it should be only today.
We can't choose past 1 day.
<img width="1438" alt="スクリーンショット 2023-12-29 15 35 40" src="https://github.com/OHIF/Viewers/assets/145171303/6b6a994d-8dc6-49fd-a94a-9bdcfcbef922">

### Steps to Reproduce

1. git clone https://github.com/OHIF/Viewers.git
2. cd ./Viewers
3. git checkout tags/v3.7.0
4. yarn install
5. yarn run dev:orthanc

### The current behavior

On the study list screen, the start date and end date cannot be set on the same day on the calendar.
We need to choose 2 days at least, although we want to choose only 1 day.
If we click "Today" button, we can choose 1 day, but it should be only today.
We can't choose past 1 day.

### The expected behavior

On the study list screen, the start date and end date be able to set on the same day on the calendar.
We should choose past 1 day.

### OS

Windows11 pro

### Node version

node v16.20.0 , yarn v1.22.19

### Browser

Chrome120.0.6099.130

**Comment by tzuccher** [comment]
This bug is reproducible by using the pop-up calendar provided. The calendar date selector will not allow date entry of the same date in the start and end date fields:
Version number: 3.8.0-beta.47
Commit hash: df2f50748e98283db458b0cb2fb20931d536b161
Tested on a mac (sonoma 14) + chrome browser (v120)

Steps to reproduce:
1. From the study list, select the Study Date - Start Date field = the calendar pop-up will display
2. Select a start date from the calendar that you know a study exists (ex: May-11-2023) = the start date populates 
4. Focus is now on the end date field and the calendar pop is displayed with focus on May 11, 2023 = the same date as the start date
![image](https://github.com/OHIF/Viewers/assets/143200290/ab077e17-861a-4ed4-94c7-30b0bd599dcc)

5. However, I cannot select that date to have it auto-entered into the end date field. When I select May 11, the date is highlighted in dark blue, the next day May 12 becomes highlighted in light blue as a suggested date. I do not select that and nothing happens. Selecting May 11 (dark blue date) does not do anything

With the above said **I can however manually edit the end date to be the same as the start date**:
- Click in the end date field and enter in the numerical values by copying and pasting the start date into the end date field: 05/11/2023. This does enter the dates in the end date field and the study list returns the one study that matches the entered start date and end date of May 11, 2023
![image](https://github.com/OHIF/Viewers/assets/143200290/8cb4aca1-a22b-4416-83d2-873a673d085f)

**Comment by sedghi** [comment]
@IbrahimCSAE take a look at this one https://ui.shadcn.com/docs/components/date-picker

**Comment by sedghi** [comment]
We released [OHIF 3.9](https://github.com/OHIF/Viewers/tree/release/3.9) which address this issue
