### ISSUE TITLE
[3.9-SB] Revamp Study Browser Panel Design: Redesign study browser panel with optimized layout and visual indicators.

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4096]
### What feature or change would you like to see made?

Redesign the Study Browser panel to align with the modern design of other viewer components. This should include:

- Reducing wasted space and optimizing layout
- Adding viewport indicators (e.g., dropdown to add display set as overlay to active viewport)
- Incorporating visual indicators for display set status (loading, prefetching, warnings, etc.)
- Adding sorting functions and sorting UI selector (series date, series number etc.)
- Adding thumbnail and no thumbnail views
- Explore horizontal view of the study browser 
- Better prior display support
- Better sop class handler splitting support
- study prefetcher

### Why should we prioritize this feature?

The Study Browser panel has the oldest design and does not conform to the new UI standards. Revamping its design will provide a more consistent user experience across the application. Additionally, optimizing the layout and adding visual indicators will improve usability and make it easier for users to understand the state of display sets.

**Comment by sedghi** [comment]
related https://github.com/OHIF/Viewers/issues/3363

**Comment by igoroctaviano** [comment]
Use Case: Handling Mixed SOP Classes in a Series

When a series contains multiple SOP classes, such as both video and images (where both could be considered secondary capture), the viewer should split them into distinct display sets. This can be achieved through a custom SOP class handler or via the UI. The options include:

Separate Display Sets: Create separate display sets for each type of content (video and images), ensuring they are easily identifiable as belonging to the same series. This can be done by: Implementing a custom SOP class handler to manage the split. 

Combined Display Set: Develop a special kind of display set that can contain both types of data, clearly indicating that they originate from the same series. This could involve: Creating a new display set format that integrates both videos and images while maintaining clarity.

Enhanced Viewport: Introduce a new kind of viewport capable of displaying a stack of images alongside video. However, this approach might lead to confusion (just a thought).

**Comment by james-hanks** [comment]
Current need to finish ticket:

- Displayset warning messages
- Series number is no longer present
- We need modality in the list view atleast or both (thumbnail and list)
- Tracking identifer in the tracking panel
- RT/SEG/SR labels etc in thumbnail view
- border around images

**Comment by IbrahimCSAE** [comment]
https://github.com/OHIF/Viewers/pull/4254

**Comment by IbrahimCSAE** [comment]
This is done and merged code-wise. pending feedback from the community for the new iteration

**Comment by james-hanks** [comment]
Response from community feedback:

* Change layout so that empty thumbnail (like seg) defaults to list view beneath the other thumbnails
* Add More Options (...) button to study panel and add tag browser option to that button
* Change default filter to all

**Comment by dan-rukas** [comment]
@IbrahimCSAE I'm added a visual for each of the changes above.

## Non thumbnail items in grid view 
This is a behavior update, no design changes to components

<img width="687" alt="Screenshot 2024-09-28 at 9 32 08 AM" src="https://github.com/user-attachments/assets/491c2a99-9477-4358-b284-58516be9c6bf">


## Action button on Series items
This design was already completed, but since we had no actions, we didn't implement it. This will use the Button component (ghost variant) and the [DropdownMenu component from this PR](https://github.com/OHIF/Viewers/pull/4387)
<img width="412" alt="Screenshot 2024-09-28 at 9 33 30 AM" src="https://github.com/user-attachments/assets/b5b39e87-0ca9-4092-a6e0-4fc886370d25">


## Default to "ALL" when anything is opened from the Study List
No design changes, this is just a behavior change that "All" in the select menu will be the default when open
<img width="360" alt="Screenshot 2024-09-28 at 9 36 45 AM" src="https://github.com/user-attachments/assets/d235d988-bb90-48e0-8163-e916e8057237">

**Comment by sedghi** [comment]
Done in 
- https://github.com/OHIF/Viewers/pull/4254
- https://github.com/OHIF/Viewers/pull/4417
