### ISSUE TITLE
[Bug] Deletion of Structured Reports miss authorization token

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [OHIF/Viewers#4364]
### Describe the Bug

When deleting a structured report, the request is missing the Authorization token, the endpoint in my API is never reached because of that.

### Steps to Reproduce

1. Open the viewer and make a measurement
2. Create the report
 
![image](https://github.com/user-attachments/assets/62967d34-8a44-47d8-ab69-2f513ec247e5)

3. Delete the report: click 'yes' on the "Delete report" pop-up
 
![image](https://github.com/user-attachments/assets/ad752a77-3004-453b-8e7e-62af841cda13)

### The current behavior

A request is made with those params:
![image](https://github.com/user-attachments/assets/40ff50c0-f5f6-4ec7-ad7e-4af1026bae24)

It ends in error 401

### The expected behavior

From another request in the page, I copied the Authorization token, right-clicked on the 'delete SR' and selected 'edit and re-send'. I added the Authorization header and pasted the value. Sending this new request is now working and received on my API

### OS

Windows 10

### Node version

v18.14.1

### Browser

Firefox 130.0 (64 bits)

EDIT: I forgot to mention but I'm using ohif/app version 3.9.0-beta.76

**Comment by IbrahimCSAE** [comment]
I can't reproduce this locally, the headers are attached as expected, it doesn't make sense that i wouldn't be attached for SR since the dicom web datasource uses the same method to attach the headers to all request types, so either they would all work or none at all.<br><br>See here:<br><br>[https://github.com/OHIF/Viewers/blob/52378b6124fabca5b7119ee8e7e1d2d272a857d0/extensions/default/src/DicomWebDataSource/index.js#L254](https://github.com/OHIF/Viewers/blob/52378b6124fabca5b7119ee8e7e1d2d272a857d0/extensions/default/src/DicomWebDataSource/index.js#L254)
