### ISSUE TITLE
Embedding the OHIF Viewer in existing ASP.NET Web application 

### ISSUE THREAD

**Issue by wi55em** [OHIF/Viewers#480]
I followed the _Getting Started_ document from here: https://docs.ohif.org/essentials/getting-started.html#developing and did not have any issues. Worked perfectly. I can access the standalone viewer from localhost:5000.

But now i'm trying to follow this guide: https://docs.ohif.org/deployment/recipes/embedded-viewer.html and have the viewer work on my web app. I followed the 5 steps there, created a DICOMVw.html with every dependencies and scripts as described in the guide above. Then, I created a button on one of my pages to redirect to the DICOMVw.html but I am getting a white page (basically no content at all) when I run the app (on Google Chrome). From this point on, i am lost.

Is there anything I am missing ? Any files I need to change ? I took a look at CodeSandbox example but that only shows the HTML file.. which I copy/pasted in my DICOMVw.html.

My only guess right now is that my html file is not able to get to the OHIFStandaloneViewer app location in the root folder of my web app.
I don't have an idea how I can resolve that issue and I hope I may have a bit of help from you here.

Thank you
Wissem

**Comment by dannyrb** [comment]
👋 Hi @wi55em, thanks for taking the time to leave feedback and report your issue. You may be one of the first few people that are reading and trying out the docs I wrote, so I am incredibly appreciative of details around any pain points.

It looks like I broke @swederik's original sandbox when I updated configuration values to come from `window.config` if not specified with `props` in the PWA version of the Viewer.

Here is an updated code sandbox: https://codesandbox.io/s/ohif-viewer-script-tag-usage-b3st9
Here is a GIST that contains the index.html contents: https://gist.github.com/dannyrb/e2a65c9657ba270f7459eda7387e733f

You'll notice the primary difference is how/where the configuration is specified.

I'll update the documentation/links with this working example. If I've not explained clearly enough, let me know where you're getting stuck and I'll try to assist further. Thanks for bringing it to my attention!

> Quick note: While this works for a basic embedded example, if you build the PWA version, host it on your site, and use an `iframe` to achieve similar "embedded" functionality you'll have a bit more control, and the global deps (like bootstrap) won't leak and impact the rest of the page's content.

**Comment by dannyrb** [comment]
Updates will be live after this is merged: https://github.com/OHIF/Viewers/pull/481

**Comment by wi55em** [comment]
Thanks a lot for your quick response and also for the quick note ! I will be doing that as soon as I'll be able to fix my issues. 

The documentation is clear and straightforward. At least for the part that I have been reading today. I am currently going over the whole documentation and should be done by the end of this week.

As for my issue, I tried out the new "index.html" file and I am getting this result.

![image](https://user-images.githubusercontent.com/35816694/58206906-a3c18300-7caf-11e9-9eb9-629d6d642920.png)

I am still guessing that I may have a directory issue or something of this kind.

**Comment by dannyrb** [comment]
Do you see any non-200 network requests in the inspector network tab? Or console warnings/errors?

I believe you see that error when the React route matching can't determine a route match.

Hmmm... Try creating a directory named `/DICOMVw`, naming your file `index.html` and changing the routerBaseName value to `/DICOMVw`? That _might_ do the trick.

**Comment by wi55em** [comment]
From the developer tool of Chrome, I only see 200 network requests and no warnings/errors in the console.

I followed the next steps you mentioned. Same result.

I have a quick question that may resolve the issue depending on your answer. Step 2 in the guide says:
![image](https://user-images.githubusercontent.com/35816694/58280975-e9458500-7d6f-11e9-902a-341cdbdc16e5.png)
which I supposed to be the content of the build folder that was created using yarn run build:package. Is that right ?

This is the screenshot showing content of the build folder in my disk.
![image](https://user-images.githubusercontent.com/35816694/58281130-5f49ec00-7d70-11e9-97cc-3c50855129ed.png)

**Comment by wi55em** [comment]
@dannyrb I still have the same issue I mentioned above. 

In my ASP.NET Web forms application, I have on my default webpage an iframe in which I set the source to "index.html" which refers to the index.html that is found in the build folder created by _yarn run build:web_. When the program runs, no console errors.. no warnings and network status are all 200s and "OK".

I copied the content of the build folder into the root of my app. So basically the path "/" is the default homepage. I don't think I have a path issue anymore. I don't know what is causing this.

I tried the same thing with the public folder, and even with the complete Viewer folder but I get the same "Sorry, this page does not exist" error showing on the webpage.

Thanks for everything so far, I hope that it might trigger you an idea or something on how I can solve this error.

**Comment by dannyrb** [comment]
Here is our simple script tag CodeSandbox: https://codesandbox.io/s/ohif-viewer-script-tag-usage-b3st9
Here is a _new_ example that iframes that page: https://codesandbox.io/s/ohif-viewer-iframe-test-wln1l

If you can create a CodeSandbox or a minimal reproduction in a GitHub repo, I can take a closer look.

**Comment by wi55em** [comment]
Ok thanks a lot ! I'll be back.

**Comment by wi55em** [comment]
@dannyrb Hi, Danny
The link below is a github repository of the solution file and its packages that is launched using Visual Studio (VS): https://github.com/wi55em/DICOMViewer. If you have VS installed in your computer you can just double click the solution (.sln) file and then run the app. It should open on your default browser.

Details: 

- I cloned the Viewer in the _AspNetWebFormsApp_ folder - and followed all the steps from the documentation.

- Also, in the same _AspNetWebFormsApp_ folder, you should find the _Default.aspx_ file which is the main web page that includes my **iframe** of the index.html. The index.html is found in the _Viewers_ folder.

Note: I am aware that I may be asking for too much. I appreciate every seconds and minutes of your contribution and help in my project so far. I know you may have other priorities and this is why I am ready to offer you my help. I would gladly accept to help you add some details in your documentation or improve anything you seem to be lacking somewhere. Please do not hesitate to ask for my contribution as well. 

Thank you !

**Comment by dannyrb** [comment]
1. I had to run this in package manager console to remove a server error:

`Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r`

On first load:

![image](https://user-images.githubusercontent.com/5797588/58981979-7db4dc00-87a1-11e9-9843-f00f87179acb.png)

2. Next, I had to provide my own build output, as the original output was not included in the GitHub repository. Inspecting the iFrame now gives us some errors:

![image](https://user-images.githubusercontent.com/5797588/58982809-4e9f6a00-87a3-11e9-8145-3e8f6f1a219d.png)

3. After fixing all of those include urls in the build output's `index.html` we get output like this:

![image](https://user-images.githubusercontent.com/5797588/58983025-cec5cf80-87a3-11e9-9f4f-58918c40e004.png)

4. Okay, so we're serving our content from something other than domain's root, so we need to update the `routerBasename` value in `config/default.js`. Here's what I updated it to in order to match our iFrame's target:

`routerBasename: '/Viewer/index.html',`

Which gives us:

![image](https://user-images.githubusercontent.com/5797588/58983245-65928c00-87a4-11e9-9910-f6ab5c53c222.png)

5. Final step, because we'll see that we're still unable to load images in the viewer. Our image loader scripts have a hard time importing if we serve a file instead of establishing a root directory. So let's change our iframe source and `routerBasename` to just the new root directory for our viewer:

- `routerBasename: '/Viewer',`
- iFrame src attribute: `/Viewer`

Our app is now able to find the image loader scripts and codecs:

![image](https://user-images.githubusercontent.com/5797588/58983608-36c8e580-87a5-11e9-860a-8d748463396a.png)


There you go. That's the magic. I think there are a couple of ways we could make this easier to debug and less error prone. I'll likely create separate issues stemming from this one to address those pain points. I've attached the updated solution as a zip if you don't want to follow the steps I've laid out above.

FireFox Send Download URL: https://send.firefox.com/download/d180684a32dd88fc/#bNGY4bWz8hIEww8njTXPRQ
(Good for 7 days, or first 100 downloads)

**Comment by wi55em** [comment]
@dannyrb 
OMG !! It worked and It was a silly mistake.. I feel stupid right now. Thanks a lot Danny ! 
I thought that the iFrame src attribute was supposed to point to the index. I've always had my iframe src attribute like this `src="/Viewer/index.html"` when It was supposed to be `src="/Viewer"`

Thanks for your time Danny ! I appreciate everything you have done for me and I hope my issue would help other developers. I will probably still stay around and contribute to the project as best as I can. :)

**Comment by yadavvirus** [comment]
@dannyrb can you please give me above solution zip file. if you have
