### ISSUE TITLE
dicomWeb application/dicom Accept Header

### ISSUE THREAD

**Issue by tillmon** [OHIF/Viewers#482]
According to this source https://cloud.google.com/healthcare/docs/how-tos/dicomweb:

> When you store a DICOM instance directly, only the application/dicom Accept Header is required.

However the viewer always request `multipart/related; type="application/octet-stream"`, is there an option to configure this?

**Comment by dannyrb** [comment]
Does the additional header have a negative impact?

**Comment by tillmon** [comment]
Sorry, I quoted the wrong part. I meant retrieving a study, not storing. The request header send to the server has `accept: multipart/related; type="application/octet-stream"`. Is is possible to accept: `application/dicom`?

**Comment by swederik** [comment]
Are you talking about the individual image requests? In that case, it's using octet-stream because we are using [WADO-RS RetrieveFrames](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.4) to pull only the pixel data. The study metadata was previously retrieved via WADO-RS Retrieve Metadata at the Study level.

If you want to retrieve the entire DICOM instance instead, you can switch to using WADO-URI. Just change these two lines to 'wadouri':

https://github.com/OHIF/Viewers/blob/6f4f098671be6c511fc303f52ccd870d6ee340fa/public/config/public_dicomweb.js#L11-L12

**Comment by tillmon** [comment]
Thank you! That was the change I was looking for.
