### ISSUE TITLE
Move SVGs for File / Folder in Google Cloud Uploader to react-viewerbase

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#653]
We should just use the <Icon> component for these so they don't sit in the assets folder.

These ones:
https://github.com/OHIF/Viewers/blob/master/public/assets/Button_File.svg
https://github.com/OHIF/Viewers/blob/master/public/assets/Button_Folder.svg

**Comment by romulobordezani** [comment]
Won't fix: in the Slack Channel was decided by @swederik and @dannyrb to keep these SVG buttons here for now, they are not exactly Icons and break the Icon Component Show Room.

![Screen Shot 2019-07-11 at 3 25 49 PM](https://user-images.githubusercontent.com/3472146/61324106-033b9b00-a7e8-11e9-8a30-92ddb1e1e9c1.png)

We could put more efforts on it and make a complete Component Element Button in react-viewerbase in the future, instead of just move it to there.
