### ISSUE TITLE
Study count not showing total number of studies

### ISSUE THREAD

**Issue by tiimoS** [OHIF/Viewers#669]
Study count should show the total number of studies in the upper right hand corner, as it used to with v1. Currently, it shows the number of studies on the displayed page. If there are more studies than the page can hold, it will simply show either 5; 10; 25; 50 or 100, depending on the rows per page setting.

**Comment by swederik** [comment]
You bring up a good point.... 

Originally we were querying and getting all of the pages, so we would know how many studies there were. Now, though, we are only querying page-by-page, because queries that return too many results will run too slowly. We no longer know how many pages there are, and just provide next/previous buttons.

So maybe that giant number becomes sort of useless if the number is greater than rows per page.

Not sure if we should do anything about this.

**Comment by tiimoS** [comment]
I understand. Well, in that case the count is more or less obsolete, since there is no added value in displaying the number of studies on the page that largely on the top of the page, if you also see this setting in the pagination settings at the bottom of the page.

**Comment by dannyrb** [comment]
Maybe we should remove this unless its mapped/provided? If we improve our documentation around providing custom/mapped JSON, this feels like something we would still want to show if we had the information.

**Comment by dannyrb** [comment]
Scoped and added to the backlog: https://github.com/OHIF/Viewers/issues/890
