### ISSUE TITLE
Switching layout resets active tool

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#704]
To reproduce:
- Load a study (e.g. https://viewer.ohif.org/viewer/1.2.840.113619.2.5.1762583153.215519.978957063.78)
- Turn on length tool, make a measurement
- Change the layout to e.g. 1x3
- Note that the active tool is now somehow W/L, but the actual Icon that is highlighted is Length

See video of the bug:

https://www.dropbox.com/s/gjp4v61phw5njdp/jul-22-2019%2015-07-41.mp4?dl=0

**Comment by dannyrb** [comment]
You'll notice that this issue is additive, so it's not actually caused by the layout changer. IE.

- Load a study
- Turn on the length tool, make a measurement
- Change the layout to e.g. 1x3
- Note that `WWWC` is now active for all viewports  <-- Bug 🐛
- Turn on the length tool, make a measurement
- Change the layout to e.g. 1x2
- Length tool is still active <-- 👍 

`react-cornerstone-viewport`, when mounted, iterates over the `availableTools` prop and calls `cornerstoneTools.setToolActive(toolName, options)'`. This would apply to all enabled elements.

For whoever grabs this, take a peak at the component's `setActiveTool` method. It's called in a few different places, and is the culprit for this issue.

While props like `availableTools` and `activeTool` are handy if you're whipping up a quick example with a single viewport, they can really make multi-viewport management a pain. A better long-term solution would be to:

- Make sure any calls made by `react-cornerstone-viewport` are isolated to it's `enabledElement`
- Indicate that props like `availableTools` and `activeTool` should be reserved for use cases where you need a single viewport
    - The exception being where you want to actively manage these to force very specific behavior where all visible viewports may not have the same tools activated
- Initialize the available tools in the extension's configuration hook
- Set the default active tools in the extension's configuration hook
- Don't change the active tool or bindings via props; instead use commands in `@ohif/extension-cornerstone`
    - If `globalToolSync` is enabled, we don't need to actively manage/sync tool modes as we enable/disable elements
    - Toolbar buttons _should_ have access to the state they need
