### ISSUE TITLE
cannot read property "logRequests" of undefined

### ISSUE THREAD

**Issue by itcthienkhiem** [OHIF/Viewers#74]
Dear ad, 
I'm running  web but it cannot show image? do you have commit all source in github? Please see in images?
![1](https://cloud.githubusercontent.com/assets/2140355/25987721/607008ba-371f-11e7-9588-90a5cbe7846f.PNG)
![2](https://cloud.githubusercontent.com/assets/2140355/25987724/64b828bc-371f-11e7-8df5-fc2f25c65467.PNG)

**Comment by itcthienkhiem** [comment]
fixed.

**Comment by swederik** [comment]
Your config was missing requestOptions.logRequests

See:
https://github.com/OHIF/Viewers/blob/b112387f8987bb9f88995b2759819393cd39b6d7/config/orthancDICOMWeb.json#L14

We now provide defaults for these in the schema: https://github.com/OHIF/Viewers/blob/131d64854cb2eceff056a15ccb12c34b9e2baaa7/Packages/ohif-servers/both/schema/servers.js#L25

Thanks for the report!

**Comment by swederik** [comment]
Reopened because I just saw this issue. It is related to DICOMWeb and looks like it happens when 'options' are undefined here: 

https://github.com/OHIF/Viewers/blob/af4b8b45f54d2b449719a597f0a8c6abd1c60905/Packages/ohif-dicom-services/server/DICOMWeb/getBulkData.js#L206

and here:

https://github.com/OHIF/Viewers/blob/af4b8b45f54d2b449719a597f0a8c6abd1c60905/Packages/ohif-dicom-services/server/DICOMWeb/getJSON.js

This may also be preventing bulk data retrieval over DICOMWeb.

**Comment by zachasme** [comment]
I am also experiencing this bug when manually inserting server options. I does not happen using a config file.
