### ISSUE TITLE
Length measurement in MPR

### ISSUE THREAD

**Issue by bhavesh-pandey** [OHIF/Viewers#743]
Hi,

Can we have the length measurement tool in MPR also which is available in normal view. Can it be enabled from somewhere? Or is this a planned feature? I searched in issues but didn't get.

https://5c-public.s3.ap-south-1.amazonaws.com/Measurement+in+MPR.png

Thanks

**Comment by dannyrb** [comment]
Hello @bhavesh-pandey,

Because the MPR implementation is using `VTK.js` under the hood, we can't reuse the `length` tool provided by our 2D viewports (which use `cornerstone.js`). We would be more than happy to accept a PR, and it should be easier to accomplish with the recent changes to `VTK.js`'s "SVG Widget Manager", but it's not on our immediate roadmap to do so ourselves.

**Comment by dannyrb** [comment]
Scoped and added to backlog: #894
