### ISSUE TITLE
How to remove the connecting circle on tools like length, rectangle etc

### ISSUE THREAD

**Issue by vimalgupta** [OHIF/Viewers#750]
Hi

How can we remove the end point connector (circles) while drawing the length or other tools like rectangle etc. for example if we draw an length measurement it gets drawn with line and two circles. we want to remove the circles and required only the line. How can we achieve it.

**Comment by dannyrb** [comment]
I believe you're asking about Cornerstone's Annotation Tool's "Handles".

Annotations are currently provided via our `@ohif/extension-cornerstone` extension. Cornerstone adds tools using the library `cornerstone-tools`. Most "annotation" tools have the ability to hide their handles unless the annotation is being "hovered". For example, here is where the `Length` tool uses the `drawHandlesOnHover` configuration value to determine if handles should be drawn:

https://github.com/cornerstonejs/cornerstoneTools/blob/109e8fdc4a1c890ba8bf267f91dbb2c5a4eb27d5/src/tools/annotation/LengthTool.js#L137

I don't believe there is a way to set this behavior for all tools; but you should be able to modify it for individual tools in this repo by searching for "availableTools" and modifying the configuration of the tool(s) you would like to see this behavior for.

As we work toward exposing per extension configuration, this would be a nice to have so that users aren't required to fork for such a small change.
