### ISSUE TITLE
When using the default coniguration, how does the app know that it can trust server.dcmjs.org? [Question] [v2.x]

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#755]
When using the default config (https://github.com/OHIF/Viewers/blob/master/public/config/default.js) the application will be sending an http request to a pacs hosted at server.dcmjs.org 

Why is a CORS error not triggered by the browser? How does the browser now that it can trust the foreign website? If I change the server to one of mine, a CORS error is logged to the console and a black screen appears.

I found nothing on the [nginx config file](https://github.com/OHIF/Viewers/blob/master/docker/Viewer-v2.x/default.conf)

I can see that the [example implementations](https://github.com/OHIF/Viewers/blob/master/docker/Nginx-Orthanc/config/nginx.conf) add an Access-Control-Allow-Origin to every request by configuring nginx, but the [default implementation](https://github.com/OHIF/Viewers/blob/master/docker/Viewer-v2.x/default.conf) is so much cleaner. How is it done?

**Comment by TZubiri** [comment]
My best guess is that the configuration files are sometimes read at runtime, but they are sometimes read at build time. I am changing the configuration files after building, so there must be some code responsible for setting the Access-Control-Allow-Origin headers based on the configuration, but since I am changing the configuration at runtime, these changes don't propagate to the request code, which is using the stale configuration.

**Comment by dannyrb** [comment]
@TZubiri, the default implementation is cleaner because we're connecting to a public PACS that is managed by someone else (in this case, `dcmjs.org`). They've done the heavy lifting on their server to ensure that appropriate headers are set. You don't see the implementation details, because they're abstracted away.

`dcmjs.org`'s server is setting the `access-control-allow-*` headers in its RESPONSE to our REQUEST for resources (data from it's PACS). They tell our browser what kind of requests are permitted.

![image](https://user-images.githubusercontent.com/5797588/62591274-1567a100-b89d-11e9-8be7-7ec4fa8d73d9.png)

More on CORS, what it is, and why we need it: https://www.codecademy.com/articles/what-is-cors

**Comment by TZubiri** [comment]
Silly me, the server is supposed to set the access control header.

Thanks!

**Comment by TZubiri** [comment]
Silly me, the server is supposed to set the access control header.

Thanks!
