### ISSUE TITLE
 functionality Save to Archive

### ISSUE THREAD

**Issue by kusiroll** [OHIF/Viewers#758]
How do I implement the  functionality Save to Archive,  I am using the meteor version 1.x and would like to implement the save to archive. I can see it has been implemented as seen in the image below but the version i am currently running does not have this functionality. Can someone help me with this and exactly what packages to upgrade.

![image](https://user-images.githubusercontent.com/35647493/62751997-58f01580-ba2b-11e9-8f18-92281ef4d036.png)

![95636A4688AA4EB9A7602499F0CFC106](https://user-images.githubusercontent.com/35647493/62751842-d6ffec80-ba2a-11e9-804d-07e96ca995bb.png)

**Comment by dannyrb** [comment]
There is no easy way to upgrade from v1 to v2. For most, it will be a matter of adopting v2 entirely, and then porting any "secret sauce" you added for your v1 fork to work for/with version 2's extensions.

"Save to Archive" is not currently supported, but we would be willing to review and merge PRs that add support. A solution would likely need to use DICOMWeb's STOW-RS to send DICOM Structured Reports back.

Depending on your needs, we could add the "Save to Archive" button, and provide a hook that receives application data when pressed, and you can then persist it with your mechanism of choice. This would also be possible with a custom Panel Extension.

Related:
- https://github.com/OHIF/Viewers/issues/68
- https://github.com/OHIF/Viewers/issues/591
- https://github.com/OHIF/Viewers/issues/729

**Comment by kusiroll** [comment]
Thanks, @dannyrb was this implemented in version 1 meteor? if yes where can I find it?

**Comment by dannyrb** [comment]
I actually joined the project right around the time v1 was deprecated, so I'm not positive. I "think" this is where the logic lives:

https://github.com/OHIF/Viewers/blob/v1.x/Packages/ohif-measurement-table/client/configuration/dataExchange.js#L15-L30

Note: This same repository and in the `v1.x` branch

**Comment by gmer16** [comment]
Hi guys, 

congratulations for the work done so far with v2, this is already an amazing piece of software.
I have a question regarding the "Save to Archive" functionality.
I've been doing some work to try to migrate some of the SR ROI functionality from v1 to v2.
I've had some success with the Length annotations (I'm able to save the SR to Orthanc), even if there are still some details that need fixing. I've tried to do the same with the Polyline annotations, that I previously added to the viewer. 
I filled up the _getTID300RepresentationArguments(tool)_ function inside _dcmjs/src/adapters/Cornerstone/FreehandMouse.js_ in the following way:

' static getTID300RepresentationArguments(tool) {

        const points = tool.handles.points;
        const lengths = [];

        return {
            points,
            lengths
        };
    }

I've tried to provide the data according to the format described in _dcmjs/src/utilities/TID300/Polyline.js_.
The SR generation processed called through _MeasurementReport.generateReport()_ makes some progress, but at some point stops with the following error, before being able to save the report to Orthanc:

`Error: There are undefined values at the array naturalValue in DicomMetaDictionary.denaturalizeValue`

Do you have some idea of what might be the problem here?
Thanks again

**Comment by dannyrb** [comment]
CC: @JamesAPetts 

@gmer16, do you have any additional code you can share to assist? This should _probably_ be a separate issue unless you're trying to port and contribute the `Save To Archive` feature wholesale.

James has the most experience with dcmjs, so I've tagged him to see if he has any immediate thoughts.

**Comment by gmer16** [comment]
Thanks @dannyrb, I fixed that issue making the following changes to  _dcmjs/src/utilities/TID300/Polyline.js_ 
`
function expandPoints(points) {

    const allPoints = [];

    points.forEach(point => {
        allPoints.push(point.x);
        allPoints.push(point.y);
    });
    return allPoints;
}
`
Now the report is saved to Orthanc.

**Comment by pieper** [comment]
@gmer16 is that a fix that should be pushed into dcmjs?  Would you provide a PR?

**Comment by dannyrb** [comment]
CC: @galelis
