### ISSUE TITLE
How to add new tool to the React based Ohif viewer like Reset or RectangleRoi.

### ISSUE THREAD

**Issue by viss3595** [OHIF/Viewers#809]
Hello Team,

I want to add some new custom tool to react based ohif viewer like a Reset button or Rectangle roi Button. so which steps I follow or Which files I need to change. And give me if any documentation available for understanding the Architecture.

**Comment by MathisGuilhin** [comment]
Hello @viss3595 

If i'm right, the current Viewer version already has these tools.

Still, if you want to create a custom tool, you can use cornerstoneTools library, I've been there myself and got through
You need to fork [cornerstoneTools](https://github.com/cornerstonejs/cornerstoneTools) and link it to your project (with yalc for example). Then, on the same principle of existing tools, you create yours.
Then to add it to the toolbar, you have to modify the [cornerstone toolbarModule](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone/src/toolbarModule.js). Finally, modify [setupTools](https://github.com/OHIF/Viewers/blob/master/platform/viewer/src/setupTools.js) to add your tool, and then I think it should be fine

I opened an issue to ask how to make cornerstoneTools part of the source code so we don't have to link it because it's not very convenient. You can follow it [here](https://github.com/OHIF/Viewers/issues/808)

**Comment by dannyrb** [comment]
Related to the already slated config docs. Going to close.
