### ISSUE TITLE
Slow display on hospital site

### ISSUE THREAD

**Issue by fredericcervenansky** [OHIF/Viewers#824]
Hello,

I work with @MathisGuilhin and we have successfully deployed OHIF in hospital (except for one problem withe CORS Policy we are fixing). The interrogation of the PACS and the visualization of a patient occurs without any problem whatever the modality. 
Except that sometimes, (often with MR or CT modalities), the display time of a patient is long, too long. A patient with 15, 20 series will take 2 minutes to display, which is a problem, for us, in clinical routine. Receiving metadata takes time, while between parsing metadata and receiving images, it is extremely fast.  So I was wondering why? Each request is asynchronous, right? Is it a problem with the hospital wado server (PACS is not directly accessed)?
Thanks.

**Comment by swederik** [comment]
Hi Frederic,

OK so here are the steps to load a study (on WADO-RS):
- Call the WADO-RS RetrieveMetadata endpoint at the study level to get the entire study's DICOM metadata
- Retrieve the pixel data for each instance frame individually via WADO-RS RetrieveFrames

Could you check your Network panel in Chrome to show the time that each of these requests are taking (and the size of the metadata payload)? It would help us understand what the bottleneck is.

A simple optimization which you should definitely do if you haven't already is to gzip the responses from your PACS server by passing the data through a proxy like Nginx. A more complex optimization is to pre-request and cache all the metadata JSON responses from your PACS into something like Apache Trafficserver (https://trafficserver.apache.org). What type of WADO server are you using?

One thing that has come up recently is that with large studies, the initial RetrieveMetadata call can be a bit slow. I have seen it on the order of seconds though, not minutes.

We have one idea for addressing this, if it is indeed the issue. The viewer load would switch to:
- Retrieve the list of series via QIDO-RS including the StudyInstanceUID
- Retrieve the metadata for each Series individually using WADO-RS RetrieveMetadata at the series level
- Retrieve each image frame individually via WADO-RS RetrieveFrames

CC @salimkanoun because he also had issues with this.

**Comment by fredericcervenansky** [comment]
Hi Eric,

You are welcome to come and test with us, since you are in Lyon too.
For example, with a patient I have 79 MB metadata payload and 1.4 min pending and another with 2,9 min for 119 MB.
I'm pretty sure I won't have the rights to pre-request all JSON responses because the GE PACS, here, is already in production and massive requests won't be allowed from IT guys.
I think I will try to modify the retrieveMetadata method in the way you describe.

**Comment by swederik** [comment]
79mb seems way too large to be just the metadata. How many instances are in
that study? Does the json response include pixel data or something? Do you
have a deidentified copy? What type of data is it?

**Comment by fredericcervenansky** [comment]
11 series were identified in that study, no pixel data in the response. Each transaction/request for image was visible in network panel, after metatdata parsing. We will have to deal for specific protocols with a large number of instances.
Unfortunately, we can't share these MR data.

**Comment by swederik** [comment]
I'm going to close this because we opened #836 to scope the task to fix the issue. Thanks for the report!
