### ISSUE TITLE
`rootPath` independent icons in toolbar

### ISSUE THREAD

**Issue by hauleth** [OHIF/Viewers#92]
I am currently trying to build URL independent StandaloneViewer however in such case some icons aren't displayed.

![zrzut ekranu 2017-07-17 16 54 32](https://user-images.githubusercontent.com/291639/28274253-b37c4238-6b10-11e7-80b0-47ff8b4d112e.png)

**Comment by swederik** [comment]
I think you need to set ROOT_URL when building it. Did you follow https://github.com/OHIF/Viewers/blob/master/StandaloneViewer/README.md ?

**Comment by hauleth** [comment]
Also some of these icons could be replaced with FA icons:

- series - `fa-list`
- zoom - `fa-search`
- pan - `fa-arrows`
- length - `fa-expand`
- annotate - `fa-sticky-note-o`
- more - `fa-cog`

@swederik almost. As I need it to be URL independent I used `meteor-build-client ../myOutputFolder -u default` as I cannot assume result URL in any way.

**Comment by hauleth** [comment]
Any update?

**Comment by swederik** [comment]
Could you try this again with the latest master? I just merged https://github.com/OHIF/Viewers/commit/8957b4ed8b454af899d7cae33a865445ec654e16 which might fix it (not sure).

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

For what it's worth, we're trying to do a better job at tracking feature requests, building scope/requirements for items we would accept PRs for, and show which items we have planned for development in the near future. Refactoring how we handle icons is one such item:

https://github.com/OHIF/Viewers/projects/3#card-21678289
