### ISSUE TITLE
Improve control over logging

### ISSUE THREAD

**Issue by akosijoy** [OHIF/Viewers#93]
Hello,

Not really sure if this is called an issue, but where might I find the log files? I can't seem to find any log files anywhere

Thank you

**Comment by atisman89** [comment]
Same question here. For example, where does OHIF.log.info(...) go?
Also, is there a way to redirect the OHIF.log to the browser console? Thanks!

**Comment by dannyrb** [comment]
We're getting ready to formally announce version 2 of the OHIF Viewer. After the announcement, version 1 issues will receive lower priority support. As this issue is a bit stale, I'm going to close it for now. 

For what it's worth, we're trying to do a better job at tracking feature requests, building scope/requirements for items we would accept PRs for, and show which items we have planned for development in the near future. You can see our very early stage roadmap here: https://github.com/OHIF/Viewers/projects/3

As we're moving away from Meteor in Version 2, I'm not sure logging is as big of a concern. If you feel it's something you would find beneficial, please feel free to create a new issue ^_^
