### ISSUE TITLE
"Uncaught exception: undefined" when loading images into Viewer

### ISSUE THREAD

**Issue by d0v1k** [OHIF/Viewers#95]
Im not using dockers everything is configure by the docs.
But when i click on the patient name it doesnt load the images.
![github](https://user-images.githubusercontent.com/1725589/28451982-cb480194-6df0-11e7-9cdf-e94ed2143549.PNG)

**Comment by swederik** [comment]
That's a very odd issue. It looks like it retrieved the study metadata correctly. I have no idea where this exception is happening or what is causing it. Do you have any more information?

* Does this happen for all images?
* Does this happen on a development version or in production (looks like production due to the filenames)?
