### ISSUE TITLE
Is docker no longer supported?

### ISSUE THREAD

**Issue by TZubiri** [OHIF/Viewers#950]
Previous to the monorepo there was a really neat [Dockerfile](https://github.com/OHIF/Viewers/blob/v2.x-premono/Dockerfile), which I can't find in master. Yet I can find a .[dockerignore](https://github.com/OHIF/Viewers/blob/master/platform/viewer/.dockerignore) file.

**Comment by dannyrb** [comment]
👋 Hi @TZubiri, we've been slow to update our automated Docker Image publish. I _just_ merged this:

- https://github.com/OHIF/Viewers/pull/952

Running this `docker run -p 3000:80 ohif/viewer:latest` appears to successfully pull the image, and host the latest version of the viewer (accessible at http://localhost:3000/). I can tell, because the updates you made for the Toolbar button are present🎉 

Our docker support could definitely be better. If you have any thoughts around improving it, please don't hesitate to make suggestions or draft PRs.
