### ISSUE TITLE
where is the image source (ie VNA) defined in the latestDocker Hub version ?

### ISSUE THREAD

**Issue by sglanger** [OHIF/Viewers#956]
question says it all. thx

**Comment by swederik** [comment]
I believe it is copied into the nginx location here:

https://github.com/OHIF/Viewers/blob/5b523c2afaabd56972abf275594ca6da139c8bfc/.docker/Viewer-v2.x/entrypoint.sh#L10-L15

So it should be here: `/usr/share/nginx/html/config/default.js` (in the container)

**Comment by dannyrb** [comment]
Actually, probably a couple of small fixes required to make the entrypoint for Google Cloud work as expected. I don't have a good client ID to test, but...

`/usr/share/nginx/html/app-config.js` is likely the file you're looking for.
You can replace it with a similarly named filed that follows our app configuration format.
`<repo-root>/platform/viewer/public/config/default.js` is a good example.

The `entrypoint.sh` is outdated because we no longer output _every_ configuration file in our source as part of the build output. This really shouldn't even be handled in the entrypoint, as users can just swap out the simple config file with their own.

Hopefully that helps. Let me know if you encounter issues.

**Comment by sglanger** [comment]
Close, there is no folder called "config"

its just

/usr/share/nginx/html/default.js



________________________________
